(()=>{
'use strict';
const PRIVACY_VERSION='beta-privacy-2026-09-23';
const SENSITIVE_VERSION='beta-sensitive-2026-09-23';
const PROJECT_REF='uopzveejnztbovncqbpq';
const VERSION='20260924-local-sanitization1';
const $=selector=>document.querySelector(selector);
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
let checking=false,privacyReady=false,sensitiveReady=false,sensitiveContinuation=null;

function hasPrivacy(consent){return Object.hasOwn(consent||{},'privacy_current')?consent.privacy_current===true:consent?.privacy_version===PRIVACY_VERSION}
function hasSensitive(consent){return Object.hasOwn(consent||{},'sensitive_current')?consent.sensitive_current===true:consent?.sensitive_version===SENSITIVE_VERSION}
function applyConsent(consent={}){privacyReady=hasPrivacy(consent);sensitiveReady=hasSensitive(consent);window.dispatchEvent(new CustomEvent('flyt:consent-changed',{detail:{privacy:privacyReady,sensitive:sensitiveReady}}))}
function closeAccount(){$('#flytAccountPanel')?.remove()}
function closeSensitive(){sensitiveContinuation=null;$('#flytSensitiveConsent')?.remove()}
function panelShell(inner){return `<div role="dialog" aria-modal="true" aria-label="Konto og personvern" style="width:min(410px,100%);max-height:90dvh;overflow:auto;background:#fffaf7;border:1px solid var(--line);border-radius:28px;padding:22px;box-shadow:0 28px 80px #3b211b55"><div class="row"><div class="grow"><div class="ey">Konto</div><h2 style="font:500 28px/1.1 Georgia;margin:5px 0">Konto og personvern</h2></div><button id="flytAccountClose" class="pill">Lukk</button></div>${String(inner||'').replaceAll('Flyt','HverdagsOss')}</div>`}
function overlay(id,markup,z=520){const el=document.createElement('div');el.id=id;el.style.cssText=`position:fixed;inset:0;z-index:${z};background:#3a211ba8;display:flex;align-items:center;justify-content:center;padding:max(18px,env(safe-area-inset-top)) 18px max(18px,env(safe-area-inset-bottom));overflow:auto`;el.innerHTML=markup;document.body.appendChild(el);return el}

function privacyMarkup(){return `<div role="dialog" aria-modal="true" aria-labelledby="flytConsentTitle" style="width:min(420px,100%);max-height:92dvh;overflow:auto;background:#fffaf7;border:1px solid var(--line);border-radius:28px;padding:24px;box-shadow:0 28px 80px #3b211b55"><div class="logo" style="font-size:34px">HverdagsOss</div><div class="ey" style="margin-top:16px">Personvern</div><h1 id="flytConsentTitle" style="font:500 30px/1.08 Georgia;margin:8px 0 10px">Før dere starter</h1><p class="sub">HverdagsOss lagrer kontoen din og det dere deler i husholdningen, som gjøremål, gjennomføringer, dagsform og anerkjennelser. Det delte innholdet er synlig for partneren du kobler deg med.</p><div class="card" style="margin-top:16px"><strong>Intime funksjoner er av</strong><p class="sub" style="margin-bottom:0">Du trenger ikke samtykke til intime opplysninger for å bruke Hjem, Gjøre, vanlig dagsform, Sett eller Belønning. Slike funksjoner kan aktiveres separat senere.</p></div><label style="display:flex;align-items:flex-start;gap:10px;margin:16px 0;text-align:left"><input id="flytPrivacyAck" type="checkbox" style="margin-top:4px;transform:scale(1.2);accent-color:var(--accent)"><span>Jeg har lest <a href="./privacy.html" target="_blank" rel="noopener" style="color:var(--deep);font-weight:800">personverninformasjonen</a> og forstår hva som deles med partneren min.</span></label><button id="flytConsentAccept" class="primary full" disabled>Godta og fortsett</button><button id="flytConsentLogout" class="secondary full" style="margin-top:10px">Ikke nå</button><p id="flytConsentStatus" class="sub" role="status" aria-live="polite" style="min-height:22px;margin-bottom:0"></p></div>`}
function showPrivacy(){if($('#flytConsentGate'))return;const el=overlay('flytConsentGate',privacyMarkup());const ack=$('#flytPrivacyAck'),go=$('#flytConsentAccept');ack.onchange=()=>{go.disabled=!ack.checked};go.onclick=acceptPrivacy;$('#flytConsentLogout').onclick=()=>window.FlytSync?.logout?.();el.addEventListener('keydown',event=>{if(event.key==='Escape')$('#flytConsentLogout')?.click()})}
async function acceptPrivacy(){const go=$('#flytConsentAccept'),status=$('#flytConsentStatus');if(!$('#flytPrivacyAck')?.checked)return;go.disabled=true;if(status)status.textContent='Lagrer…';try{const {error}=await window.FlytSync.rpc('accept_privacy_terms',{p_privacy_version:PRIVACY_VERSION});if(error)throw error;privacyReady=true;$('#flytConsentGate')?.remove();window.dispatchEvent(new CustomEvent('flyt:consent-changed',{detail:{privacy:true,sensitive:sensitiveReady}}));await window.FlytSync.bootstrap?.()}catch(error){privacyReady=false;if(status)status.textContent='Kunne ikke lagre akkurat nå. Prøv igjen.';go.disabled=false}}

function sensitiveMarkup(){return `<div role="dialog" aria-modal="true" aria-labelledby="flytSensitiveTitle" style="width:min(410px,100%);max-height:90dvh;overflow:auto;background:#fffaf7;border:1px solid var(--line);border-radius:28px;padding:24px;box-shadow:0 28px 80px #3b211b55"><div class="ey">Valgfri funksjon</div><h2 id="flytSensitiveTitle" style="font:500 29px/1.1 Georgia;margin:7px 0 10px">Aktiver privat innsjekk?</h2><p class="sub">«Mellom dere» kan lagre det du selv registrerer om nærhet og lyst. Opplysningene deles bare med partneren din og brukes ikke for å beregne oppgaver eller poeng.</p><label style="display:flex;align-items:flex-start;gap:10px;margin:16px 0;text-align:left"><input id="flytSensitiveAck" type="checkbox" style="margin-top:4px;transform:scale(1.2);accent-color:var(--accent)"><span>Jeg samtykker uttrykkelig til behandling av opplysninger jeg velger å registrere om intimitet og seksualliv.</span></label><button id="flytSensitiveAccept" class="primary full" disabled>Aktiver privat innsjekk</button><button id="flytSensitiveCancel" class="secondary full" style="margin-top:10px">Ikke nå</button><p id="flytSensitiveStatus" class="sub" role="status" aria-live="polite" style="min-height:22px;margin-bottom:0"></p></div>`}
function requestSensitive(onGranted){if(sensitiveReady){onGranted?.();return Promise.resolve(true)}closeSensitive();sensitiveContinuation=typeof onGranted==='function'?onGranted:null;const el=overlay('flytSensitiveConsent',sensitiveMarkup(),540),ack=$('#flytSensitiveAck'),go=$('#flytSensitiveAccept');ack.onchange=()=>{go.disabled=!ack.checked};$('#flytSensitiveCancel').onclick=closeSensitive;el.addEventListener('click',event=>{if(event.target===el)closeSensitive()});go.onclick=acceptSensitive;return Promise.resolve(false)}
async function acceptSensitive(){const go=$('#flytSensitiveAccept'),status=$('#flytSensitiveStatus');if(!$('#flytSensitiveAck')?.checked)return;go.disabled=true;if(status)status.textContent='Aktiverer…';try{const {error}=await window.FlytSync.rpc('accept_sensitive_consent',{p_sensitive_version:SENSITIVE_VERSION});if(error)throw error;sensitiveReady=true;const continuation=sensitiveContinuation;closeSensitive();window.dispatchEvent(new CustomEvent('flyt:consent-changed',{detail:{privacy:privacyReady,sensitive:true}}));continuation?.()}catch(error){if(status)status.textContent='Kunne ikke aktivere akkurat nå. Prøv igjen.';go.disabled=false}}

async function refreshConsent(){if(!window.FlytSync?.rpc)return{};const {data,error}=await window.FlytSync.rpc('get_my_beta_consent',{});if(error)throw error;applyConsent(data||{});return data||{}}
async function checkConsent(){if(checking||!window.FlytSync?.rpc)return;if(!window.FlytSync?.getContext?.()?.user_id){applyConsent({});return}checking=true;try{await refreshConsent();if(!privacyReady)showPrivacy();else $('#flytConsentGate')?.remove()}catch(error){privacyReady=false}finally{checking=false}}
function clearLocalState(){window.FlytSync?.clearPrivateLocalData?.();window.FlytLocalData?.clearPrivateState?.()}
function clearLocalAuth(){clearLocalState();try{for(let i=localStorage.length-1;i>=0;i--){const key=localStorage.key(i);if(key&&(key===`sb-${PROJECT_REF}-auth-token`||(key.includes(PROJECT_REF)&&key.includes('auth-token'))))localStorage.removeItem(key)}}catch(error){}try{for(let i=sessionStorage.length-1;i>=0;i--){const key=sessionStorage.key(i);if(key&&key.includes(PROJECT_REF)&&key.includes('auth-token'))sessionStorage.removeItem(key)}}catch(error){}}

function partnerCard(ctx){
  const me=ctx?.user_id,partner=(ctx?.members||[]).find(member=>member.id!==me);
  if(partner)return `<div class="card"><div class="ey">Partnerkobling</div><strong style="display:block;margin-top:6px">Koblet til ${esc(partner.display_name||'partner')}</strong><p class="sub">Dere deler husholdningsdata frem til en av dere kobler fra.</p><button id="flytDisconnectPartner" class="secondary full" style="color:#a63c31;border-color:#dfb0a6">Koble fra partner</button><button id="flytPartnerSupport" class="secondary full" style="margin-top:8px">Få hjelp med partnerkoblingen</button></div>`;
  if(ctx?.household)return `<div class="card"><div class="ey">Partnerkobling</div><strong style="display:block;margin-top:6px">Ingen partner koblet</strong><p class="sub">Invitasjonskoder utløper etter sju dager. Når du lager en ny kode, blir den gamle ugyldig.</p><button id="flytRotateInvite" class="secondary full">Lag ny invitasjonskode</button><button id="flytPartnerSupport" class="secondary full" style="margin-top:8px">Få hjelp med partnerkoblingen</button></div>`;
  return `<div class="card"><div class="ey">Partnerkobling</div><strong style="display:block;margin-top:6px">Ingen partner koblet</strong><p class="sub">Du kan opprette eller bli med i en ny husholdning fra startsiden.</p><button id="flytPartnerSupport" class="secondary full">Få hjelp med partnerkoblingen</button></div>`;
}
function open(){
  closeAccount();
  const ctx=window.FlytSync?.getContext?.(),cloud=!!ctx?.user_id,el=overlay('flytAccountPanel','',410);
  const sensitiveCard=sensitiveReady?`<div class="card"><strong>Privat innsjekk er aktiv</strong><p class="sub">Du kan registrere nærhet og lyst i «Mellom dere». Du kan slå av funksjonen når som helst uten å miste Hjem, Gjøre, Sett eller Belønning.</p><button id="flytWithdrawConsent" class="secondary full">Slå av og slett mine intime data</button></div>`:`<div class="card"><strong>Private funksjoner er av</strong><p class="sub">Kjerneproduktet fungerer som vanlig. Aktiver bare hvis du vil bruke «Mellom dere» for opplysninger om nærhet og lyst.</p><button id="flytEnableSensitive" class="secondary full">Les mer og aktiver</button></div>`;
  const cloudBody=`${partnerCard(ctx)}<div class="card"><strong>Dataene deres</strong><p class="sub">Konto, oppsett, gjøremål, gjennomføringer, vanlig dagsform og anerkjennelser lagres for å levere den delte husholdningen.</p><a class="secondary full" style="display:flex;align-items:center;justify-content:center;text-decoration:none" href="./privacy.html" target="_blank" rel="noopener">Les personverninformasjonen</a></div>${sensitiveCard}<div class="card" style="border-color:#edc5bc;background:#fff6f3"><strong>Slett konto</strong><p class="sub">Dette sletter kontoen og personopplysninger knyttet til deg. Partnerens egne data beholdes.</p><button id="flytDeleteAccount" class="secondary full" style="color:#a63c31;border-color:#dfb0a6">Slett kontoen min</button></div>`;
  const localBody=`<div class="card"><strong>Lokal modus</strong><p class="sub">Denne modusen lagrer bare HverdagsOss-data på denne enheten og har ingen sky-konto koblet til.</p><button id="flytDeleteLocal" class="secondary full" style="color:#a63c31;border-color:#dfb0a6">Slett lokale data</button></div>`;
  el.innerHTML=panelShell(cloud?cloudBody:localBody);el.addEventListener('click',event=>{if(event.target===el)closeAccount()});$('#flytAccountClose').onclick=closeAccount;
  if(cloud){
    $('#flytEnableSensitive')?.addEventListener('click',()=>{closeAccount();requestSensitive(()=>window.FlytOss?.render?.({refresh:true}))});
    $('#flytWithdrawConsent')?.addEventListener('click',confirmWithdraw);
    $('#flytDisconnectPartner')?.addEventListener('click',confirmDisconnect);
    $('#flytRotateInvite')?.addEventListener('click',async()=>{closeAccount();await window.FlytSync?.rotateInviteCode?.()});
    $('#flytPartnerSupport')?.addEventListener('click',openPartnerSupport);
    $('#flytDeleteAccount').onclick=confirmDelete;
  }else $('#flytDeleteLocal').onclick=()=>{clearLocalAuth();location.reload()}
}
function openPartnerSupport(){closeAccount();window.FlytBetaUI?.open?.('Jeg trenger hjelp med partnerkoblingen. ')}
function confirmDisconnect(){
  const panel=$('#flytAccountPanel'),ctx=window.FlytSync?.getContext?.(),partner=(ctx?.members||[]).find(member=>member.id!==ctx?.user_id);
  if(!panel||!partner)return;
  panel.innerHTML=panelShell(`<div class="card" style="border-color:#edc5bc;background:#fff6f3"><div class="ey">Partnerkobling</div><h3 style="margin:7px 0">Koble fra ${esc(partner.display_name||'partner')}?</h3><p class="sub">Tilgangen stopper umiddelbart for dere begge. Invitasjonskoden blir ugyldig, og den delte husholdningen med oppsett, gjøremål, historikk, poeng, meldinger og anerkjennelser slettes permanent.</p><p class="sub"><strong>Kontoene beholdes.</strong> Begge kan senere opprette eller bli med i en ny husholdning.</p><label class="label" for="flytDisconnectWord">Skriv KOBLE FRA for å bekrefte</label><input id="flytDisconnectWord" class="field" autocomplete="off" autocapitalize="characters" placeholder="KOBLE FRA"><button id="flytDisconnectConfirm" class="primary full" disabled style="margin-top:10px">Koble fra og slett fellesdata</button><button id="flytDisconnectCancel" class="secondary full" style="margin-top:10px">Avbryt</button><button id="flytDisconnectSupport" class="secondary full" style="margin-top:8px">Få hjelp først</button><p id="flytDisconnectStatus" class="sub" role="status" aria-live="polite" style="min-height:22px;margin-bottom:0"></p></div>`);
  $('#flytAccountClose').onclick=closeAccount;const input=$('#flytDisconnectWord'),go=$('#flytDisconnectConfirm');input.oninput=()=>{go.disabled=input.value.trim().toUpperCase()!=='KOBLE FRA'};$('#flytDisconnectCancel').onclick=open;$('#flytDisconnectSupport').onclick=openPartnerSupport;go.onclick=disconnectPartner;
}
async function disconnectPartner(){
  const go=$('#flytDisconnectConfirm'),status=$('#flytDisconnectStatus');if($('#flytDisconnectWord')?.value.trim().toUpperCase()!=='KOBLE FRA')return;go.disabled=true;if(status)status.textContent='Kobler fra og sletter fellesdata…';
  try{const {data,error}=await window.FlytSync.rpc('disconnect_partner',{});if(error)throw error;if(!data?.ok)throw new Error('DISCONNECT_FAILED');closeAccount();clearLocalState();window.FlytSync?.handleDisconnected?.('Partnerkoblingen er avsluttet. Fellesdataene er slettet, og kontoen din er klar for en ny husholdning.')}catch(error){if(status)status.textContent='Kunne ikke koble fra akkurat nå. Prøv igjen eller kontakt support.';go.disabled=false}
}
function confirmWithdraw(){const panel=$('#flytAccountPanel');if(!panel)return;panel.innerHTML=panelShell(`<div class="card"><div class="ey">Privat innsjekk</div><h3 style="margin:7px 0">Slå av og slette dine intime data?</h3><p class="sub">Dine registreringer om nærhet og lyst og sensitive hendelser du selv har opprettet fjernes. Konto, dagsform, gjøremål, anerkjennelser og partnerens egne data beholdes.</p><button id="flytWithdrawConfirm" class="primary full">Slå av og slett</button><button id="flytWithdrawCancel" class="secondary full" style="margin-top:10px">Avbryt</button><p id="flytWithdrawStatus" class="sub" role="status" aria-live="polite" style="min-height:22px;margin-bottom:0"></p></div>`);$('#flytAccountClose').onclick=closeAccount;$('#flytWithdrawCancel').onclick=open;$('#flytWithdrawConfirm').onclick=withdrawSensitive}
async function withdrawSensitive(){const go=$('#flytWithdrawConfirm'),status=$('#flytWithdrawStatus');go.disabled=true;if(status)status.textContent='Sletter intime data…';try{const {error}=await window.FlytSync.rpc('withdraw_sensitive_consent',{});if(error)throw error;sensitiveReady=false;closeAccount();window.dispatchEvent(new CustomEvent('flyt:consent-changed',{detail:{privacy:privacyReady,sensitive:false}}));await window.FlytSync.bootstrap?.()}catch(error){if(status)status.textContent='Kunne ikke fullføre akkurat nå.';go.disabled=false}}
function confirmDelete(){const panel=$('#flytAccountPanel');if(!panel)return;panel.innerHTML=panelShell(`<div class="card" style="border-color:#edc5bc;background:#fff6f3"><div class="ey">Permanent sletting</div><h3 style="margin:7px 0">Slette HverdagsOss-kontoen?</h3><p class="sub">Kontoen kan ikke gjenopprettes. Partnerens egne data beholdes dersom partneren fortsatt bruker husholdningen.</p><label class="label" for="flytDeleteWord">Skriv SLETT for å bekrefte</label><input id="flytDeleteWord" class="field" autocomplete="off" autocapitalize="characters" placeholder="SLETT"><button id="flytDeleteConfirm" class="primary full" disabled style="margin-top:10px">Slett permanent</button><button id="flytDeleteCancel" class="secondary full" style="margin-top:10px">Avbryt</button><p id="flytDeleteStatus" class="sub" role="status" aria-live="polite" style="min-height:22px;margin-bottom:0"></p></div>`);$('#flytAccountClose').onclick=closeAccount;const input=$('#flytDeleteWord'),go=$('#flytDeleteConfirm');input.oninput=()=>{go.disabled=input.value.trim().toUpperCase()!=='SLETT'};$('#flytDeleteCancel').onclick=open;go.onclick=deleteAccount}
async function deleteAccount(){const go=$('#flytDeleteConfirm'),status=$('#flytDeleteStatus');if($('#flytDeleteWord')?.value.trim().toUpperCase()!=='SLETT')return;go.disabled=true;if(status)status.textContent='Sletter konto og data…';try{const {error}=await window.FlytSync.rpc('delete_my_account',{});if(error)throw error;clearLocalAuth();document.body.innerHTML='<div class="login"><div class="loginbox"><div class="logo">HverdagsOss</div><div class="ey">Konto slettet</div><h1 style="font:500 30px Georgia">Dataene dine er slettet</h1><p class="sub">Du sendes tilbake til start.</p></div></div>';setTimeout(()=>location.replace('./'),700)}catch(error){if(status)status.textContent='Slettingen kunne ikke fullføres. Prøv igjen eller send en tilbakemelding i beta-menyen.';go.disabled=false}}
function install(){checkConsent();setInterval(()=>{const gate=$('#betaGate');if(gate&&!gate.classList.contains('hidden'))checkConsent()},1500)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
window.FlytAccountUI={open,checkConsent,refreshConsent,requestSensitive,isConsentReady:()=>privacyReady===true,hasSensitiveConsent:()=>sensitiveReady===true,version:VERSION};
})();
