(()=>{
'use strict';
const PRIVACY_VERSION='beta-privacy-2026-08-27';
const SENSITIVE_VERSION='beta-sensitive-2026-08-27';
const PROJECT_REF='uopzveejnztbovncqbpq';
const $=s=>document.querySelector(s);
let checking=false;
function currentConsent(c){return c?.privacy_version===PRIVACY_VERSION&&c?.sensitive_version===SENSITIVE_VERSION}
function closeAccount(){$('#flytAccountPanel')?.remove()}
function consentMarkup(){return `<div role="dialog" aria-modal="true" aria-labelledby="flytConsentTitle" style="width:min(420px,100%);max-height:92dvh;overflow:auto;background:#fffaf7;border:1px solid var(--line);border-radius:28px;padding:24px;box-shadow:0 28px 80px #3b211b55"><div class="logo" style="font-size:34px">fl<b>y</b>t</div><div class="ey" style="margin-top:16px">Privat beta</div><h1 id="flytConsentTitle" style="font:500 30px/1.08 Georgia;margin:8px 0 10px">Før dere starter</h1><p class="sub">Flyt er laget for to personer og kan inneholde personlige opplysninger om hverdagen, samlivet, nærhet, ønsker og behov. Det du deler i den felles husholdningen blir synlig for partneren du kobler deg med.</p><div class="card" style="margin-top:16px"><strong>Dette lagres i betaen</strong><p class="sub" style="margin-bottom:0">Konto og navn, husholdningsoppsett, gjøremål og gjennomføringer, poeng, status og behov, Sett, Fristelser og tilbakemeldinger. Data lagres i Supabase i EU-regionen.</p></div><label style="display:flex;align-items:flex-start;gap:10px;margin:16px 0 10px;text-align:left"><input id="flytPrivacyAck" type="checkbox" style="margin-top:4px;transform:scale(1.2);accent-color:var(--accent)"><span>Jeg har lest <a href="./privacy.html" target="_blank" rel="noopener" style="color:var(--deep);font-weight:800">personverninformasjonen</a> og forstår at data deles med partneren jeg kobler meg med.</span></label><label style="display:flex;align-items:flex-start;gap:10px;margin:10px 0 16px;text-align:left"><input id="flytSensitiveAck" type="checkbox" style="margin-top:4px;transform:scale(1.2);accent-color:var(--accent)"><span>Jeg samtykker uttrykkelig til at Flyt kan behandle opplysninger jeg selv velger å registrere om samliv, nærhet, seksuelle ønsker og andre sensitive forhold for å levere funksjonene i appen.</span></label><button id="flytConsentAccept" class="primary full" disabled>Godta og fortsett</button><button id="flytConsentLogout" class="secondary full" style="margin-top:10px">Ikke nå</button><p id="flytConsentStatus" class="sub" style="min-height:22px;margin-bottom:0"></p></div>`}
function showConsent(){if($('#flytConsentGate'))return;const el=document.createElement('div');el.id='flytConsentGate';el.style.cssText='position:fixed;inset:0;z-index:520;background:linear-gradient(145deg,#efb99d,#fff1e8 60%,#e9aa87);display:flex;align-items:center;justify-content:center;padding:max(18px,env(safe-area-inset-top)) 18px max(18px,env(safe-area-inset-bottom));overflow:auto';el.innerHTML=consentMarkup();document.body.appendChild(el);const a=$('#flytPrivacyAck'),b=$('#flytSensitiveAck'),go=$('#flytConsentAccept');const sync=()=>{go.disabled=!(a.checked&&b.checked)};a.onchange=sync;b.onchange=sync;go.onclick=acceptConsent;$('#flytConsentLogout').onclick=()=>{clearLocalAuth();location.reload()}}
async function acceptConsent(){const go=$('#flytConsentAccept'),status=$('#flytConsentStatus');if(!$('#flytPrivacyAck')?.checked||!$('#flytSensitiveAck')?.checked)return;go.disabled=true;if(status)status.textContent='Lagrer samtykket…';try{const {error}=await window.FlytSync.rpc('accept_beta_consent',{p_privacy_version:PRIVACY_VERSION,p_sensitive_version:SENSITIVE_VERSION});if(error)throw error;$('#flytConsentGate')?.remove();await window.FlytSync.bootstrap?.()}catch(e){if(status)status.textContent='Kunne ikke lagre samtykket akkurat nå. Prøv igjen.';go.disabled=false}}
async function checkConsent(){if(checking||!window.FlytSync?.rpc)return;checking=true;try{const {data,error}=await window.FlytSync.rpc('get_my_beta_consent',{});if(error)return;if(!currentConsent(data))showConsent();else $('#flytConsentGate')?.remove()}catch(e){}finally{checking=false}}
function clearLocalAuth(){try{localStorage.removeItem('flyt_local_mode_v1');localStorage.removeItem('flyt_state_v5');for(let i=localStorage.length-1;i>=0;i--){const k=localStorage.key(i);if(k&&(k===`sb-${PROJECT_REF}-auth-token`||(k.includes(PROJECT_REF)&&k.includes('auth-token'))))localStorage.removeItem(k)}}catch(e){}try{for(let i=sessionStorage.length-1;i>=0;i--){const k=sessionStorage.key(i);if(k&&k.includes(PROJECT_REF)&&k.includes('auth-token'))sessionStorage.removeItem(k)}}catch(e){}}
function panelShell(inner){return `<div role="dialog" aria-modal="true" aria-label="Konto og personvern" style="width:min(410px,100%);max-height:90dvh;overflow:auto;background:#fffaf7;border:1px solid var(--line);border-radius:28px;padding:22px;box-shadow:0 28px 80px #3b211b55"><div class="row"><div class="grow"><div class="ey">Konto</div><h2 style="font:500 28px/1.1 Georgia;margin:5px 0">Konto og personvern</h2></div><button id="flytAccountClose" class="pill">Lukk</button></div>${inner}</div>`}
function open(){closeAccount();const ctx=window.FlytSync?.getContext?.(),cloud=!!ctx?.user_id,el=document.createElement('div');el.id='flytAccountPanel';el.style.cssText='position:fixed;inset:0;z-index:410;background:#3a211b88;display:flex;align-items:center;justify-content:center;padding:20px';const cloudBody=`<div class="card"><strong>Dataene deres</strong><p class="sub">Oppsett, gjennomføringer, poeng og samlivsrelaterte opplysninger lagres i den delte husholdningen. Partneren du er koblet med kan se det som er delt der.</p><a class="secondary full" style="display:flex;align-items:center;justify-content:center;text-decoration:none" href="./privacy.html" target="_blank" rel="noopener">Les personverninformasjonen</a></div><div class="card" style="border-color:#edc5bc;background:#fff6f3"><strong>Slett konto</strong><p class="sub">Dette sletter kontoen og personopplysninger knyttet til deg. Dersom partneren blir igjen, beholdes partnerens husholdning. Dine egne registreringer fjernes der det er mulig, og gjenværende navnehenvisninger anonymiseres.</p><button id="flytDeleteAccount" class="secondary full" style="color:#a63c31;border-color:#dfb0a6">Slett kontoen min</button></div>`;const localBody=`<div class="card"><strong>Lokal modus</strong><p class="sub">Denne modusen lagrer bare Flyt-data på denne enheten og har ingen sky-konto koblet til.</p><button id="flytDeleteLocal" class="secondary full" style="color:#a63c31;border-color:#dfb0a6">Slett lokale data</button></div>`;el.innerHTML=panelShell(cloud?cloudBody:localBody);el.addEventListener('click',e=>{if(e.target===el)closeAccount()});document.body.appendChild(el);$('#flytAccountClose').onclick=closeAccount;if(cloud)$('#flytDeleteAccount').onclick=confirmDelete;else $('#flytDeleteLocal').onclick=()=>{clearLocalAuth();location.reload()}}
function confirmDelete(){const panel=$('#flytAccountPanel');if(!panel)return;panel.innerHTML=panelShell(`<div class="card" style="border-color:#edc5bc;background:#fff6f3"><div class="ey">Permanent sletting</div><h3 style="margin:7px 0">Slette Flyt-kontoen?</h3><p class="sub">Kontoen kan ikke gjenopprettes. Partnerens egne data beholdes dersom partneren fortsatt bruker husholdningen.</p><label class="label" for="flytDeleteWord">Skriv SLETT for å bekrefte</label><input id="flytDeleteWord" class="field" autocomplete="off" autocapitalize="characters" placeholder="SLETT"><button id="flytDeleteConfirm" class="primary full" disabled style="margin-top:10px">Slett permanent</button><button id="flytDeleteCancel" class="secondary full" style="margin-top:10px">Avbryt</button><p id="flytDeleteStatus" class="sub" style="min-height:22px;margin-bottom:0"></p></div>`);$('#flytAccountClose').onclick=closeAccount;const input=$('#flytDeleteWord'),go=$('#flytDeleteConfirm');input.oninput=()=>{go.disabled=input.value.trim().toUpperCase()!=='SLETT'};$('#flytDeleteCancel').onclick=open;go.onclick=deleteAccount}
async function deleteAccount(){const go=$('#flytDeleteConfirm'),status=$('#flytDeleteStatus');if($('#flytDeleteWord')?.value.trim().toUpperCase()!=='SLETT')return;go.disabled=true;if(status)status.textContent='Sletter konto og data…';try{const {error}=await window.FlytSync.rpc('delete_my_account',{});if(error)throw error;clearLocalAuth();document.body.innerHTML='<div class="login"><div class="loginbox"><div class="logo">fl<b>y</b>t</div><div class="ey">Konto slettet</div><h1 style="font:500 30px Georgia">Dataene dine er slettet</h1><p class="sub">Du sendes tilbake til start.</p></div></div>';setTimeout(()=>location.replace('./'),700)}catch(e){if(status)status.textContent='Slettingen kunne ikke fullføres. Prøv igjen eller send en tilbakemelding i beta-menyen.';go.disabled=false}}
function install(){checkConsent();setInterval(()=>{const gate=$('#betaGate');if(gate&&!gate.classList.contains('hidden'))checkConsent()},1500)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
window.FlytAccountUI={open,checkConsent,version:'20260827-2350'};
})();