(()=>{
'use strict';
const $=s=>document.querySelector(s);
const bridge=()=>window.FlytBridge;
function ensureButton(){const top=document.querySelector('.top > div');if(!top||$('#betaHelpBtn'))return;const b=document.createElement('button');b.id='betaHelpBtn';b.className='pill';b.textContent='Beta';top.prepend(b)}
function close(){$('#betaPanel')?.remove()}
function open(){close();const el=document.createElement('div');el.id='betaPanel';el.style.cssText='position:fixed;inset:0;z-index:175;background:#3a211b88;display:flex;align-items:center;justify-content:center;padding:22px';el.innerHTML=`<div role="dialog" aria-modal="true" style="width:min(390px,100%);max-height:88dvh;overflow:auto;background:#fffaf7;border:1px solid #ead8d0;border-radius:26px;padding:22px;box-shadow:0 24px 70px #3b211b55"><div class="ey">Privat beta</div><h2 style="font:500 28px/1.12 Georgia;margin:10px 0 10px">Hjelp oss å teste Flyt</h2><p class="sub">Flyt lagrer oppsett, gjennomføringer, poeng og samlivsrelaterte statusopplysninger for husholdningen din. Opplysningene deles kun med den partneren du er koblet med i Flyt.</p><div class="card"><strong>Personvern i beta</strong><p class="sub">Bruk bare appen hvis du er komfortabel med å dele disse opplysningene med partneren din. Ikke legg inn informasjon du ikke ønsker lagret i tjenesten.</p></div><label class="label">Tilbakemelding eller feil</label><textarea id="betaFeedbackText" class="field" rows="5" style="min-height:120px;resize:vertical" placeholder="Hva skjedde, og hva forventet du skulle skje?"></textarea><div style="display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:16px"><button id="betaClose" class="secondary">Lukk</button><button id="betaSend" class="primary">Send</button></div><p id="betaFeedbackStatus" class="sub" style="min-height:22px;margin-bottom:0"></p></div>`;el.addEventListener('click',e=>{if(e.target===el)close()});document.body.appendChild(el);$('#betaClose').onclick=close;$('#betaSend').onclick=send}
async function send(){const text=$('#betaFeedbackText')?.value.trim(),status=$('#betaFeedbackStatus');if(!text){if(status)status.textContent='Skriv litt om hva som skjedde.';return}if(status)status.textContent='Sender…';try{const ctx=window.FlytSync?.getContext?.(),s=bridge()?.getState?.(),context=JSON.stringify({view:s?.view||null,version:'beta-20260824',userAgent:navigator.userAgent.slice(0,180),household:ctx?.household?.id?'connected':'none'});const {error}=await window.FlytSync.rpc('submit_beta_feedback',{p_message:text,p_context:context});if(error)throw error;if(status)status.textContent='Takk. Tilbakemeldingen er lagret.';$('#betaFeedbackText').value=''}catch(e){if(status)status.textContent='Kunne ikke sende akkurat nå.'}}
document.addEventListener('click',e=>{if(e.target.closest('#betaHelpBtn')){e.preventDefault();open()}},true);
window.addEventListener('DOMContentLoaded',ensureButton);let tries=0;const timer=setInterval(()=>{ensureButton();if($('#betaHelpBtn')||++tries>40)clearInterval(timer)},100);
window.FlytBetaUI={open,close,version:'20260824-1628'};
})();