(()=>{
'use strict';
const $=s=>document.querySelector(s);
const bridge=()=>window.FlytBridge;
function ensureButton(){const top=document.querySelector('.top > div');if(!top||$('#betaHelpBtn'))return;const b=document.createElement('button');b.id='betaHelpBtn';b.className='pill';b.textContent='Beta';top.prepend(b)}
function close(){$('#betaPanel')?.remove()}
function dialog(){return $('#betaPanel')?.querySelector?.('[data-beta-dialog]')||null}
function showSuccess(){const box=dialog();if(!box)return;box.innerHTML=`<div class="ey">Privat beta</div><h2 style="font:500 28px/1.12 Georgia;margin:10px 0">Takk! Tilbakemeldingen er sendt.</h2><p class="sub">Den er lagret for HverdagsOss-teamet.</p><button id="betaClose" class="primary full" style="margin-top:16px">Lukk</button>`;$('#betaClose')?.addEventListener('click',close)}
function open(){close();const el=document.createElement('div');el.id='betaPanel';el.style.cssText='position:fixed;inset:0;z-index:175;background:#3a211b88;display:flex;align-items:center;justify-content:center;padding:22px';el.innerHTML=`<div data-beta-dialog role="dialog" aria-modal="true" style="width:min(390px,100%);max-height:88dvh;overflow:auto;background:#fffaf7;border:1px solid #ead8d0;border-radius:26px;padding:22px;box-shadow:0 24px 70px #3b211b55"><div class="ey">Privat beta</div><h2 style="font:500 28px/1.12 Georgia;margin:10px 0 10px">Hjelp oss å teste HverdagsOss</h2><p class="sub">HverdagsOss lagrer oppsett, gjennomføringer, poeng og samlivsrelaterte statusopplysninger for husholdningen din. Opplysningene deles kun med den partneren du er koblet med i HverdagsOss.</p><div class="card"><strong>Personvern i beta</strong><p class="sub">Bruk bare appen hvis du er komfortabel med å dele disse opplysningene med partneren din. Ikke legg inn informasjon du ikke ønsker lagret i tjenesten.</p></div><label class="label">Tilbakemelding eller feil</label><textarea id="betaFeedbackText" class="field" rows="5" style="min-height:120px;resize:vertical" placeholder="Hva skjedde, og hva forventet du skulle skje?"></textarea><div style="display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:16px"><button id="betaClose" class="secondary">Lukk</button><button id="betaSend" class="primary">Send</button></div><p id="betaFeedbackStatus" class="sub" role="status" style="min-height:22px;margin-bottom:0"></p></div>`;el.addEventListener('click',event=>{if(event.target===el)close()});document.body.appendChild(el);$('#betaClose')?.addEventListener('click',close);$('#betaSend')?.addEventListener('click',send)}
async function send(){const panel=$('#betaPanel'),input=$('#betaFeedbackText'),status=$('#betaFeedbackStatus'),button=$('#betaSend'),text=input?.value.trim();if(!panel||!input||!button)return;if(!text){if(status)status.textContent='Skriv litt om hva som skjedde.';return}button.disabled=true;button.setAttribute('aria-busy','true');if(status)status.textContent='Sender…';try{const rpc=window.FlytSync?.rpc;if(typeof rpc!=='function')throw new Error('Feedback service unavailable');const ctx=window.FlytSync?.getContext?.(),state=bridge()?.getState?.(),context=JSON.stringify({view:state?.view||null,version:'beta-20260914-feedback2',userAgent:navigator.userAgent.slice(0,180),household:ctx?.household?.id?'connected':'none'});const {error}=await rpc('submit_beta_feedback',{p_message:text,p_context:context});if(error)throw error;if(!panel.isConnected)return;showSuccess()}catch(error){if(status)status.textContent='Kunne ikke sende. Prøv igjen.';button.disabled=false;button.removeAttribute('aria-busy')}}document.addEventListener('click',event=>{if(event.target.closest('#betaHelpBtn')){event.preventDefault();open()}},true);window.addEventListener('DOMContentLoaded',ensureButton);let tries=0;const timer=setInterval(()=>{ensureButton();if($('#betaHelpBtn')||++tries>40)clearInterval(timer)},100);window.FlytBetaUI={open,close,version:'20260914-feedback2'};})();
