(()=>{
'use strict';
const $=s=>document.querySelector(s);
const bridge=()=>window.FlytBridge;
let mode='day',partnerCtx=null,loadingPartner=false;
const LABEL={low:'Lav',med:'Middels',high:'Høy'};
const NEED_LABEL={relief:'Avlastning',closeness:'Nærhet',sex:'Sex',initiative:'Initiativ',alone:'Alenetid',quiet:'Ro'};
const FIELD_LABEL={energy:'Energi',capacity:'Overskudd',closeness:'Nærhet',desire:'Sexlyst',stress:'Stress'};
function monday(){const d=new Date(),x=new Date(d),day=(x.getDay()+6)%7;x.setHours(0,0,0,0);x.setDate(x.getDate()-day);return x}
function today(){const d=new Date();const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`}
function dayIndex(){return ((new Date().getDay()+6)%7)+1}
function dayName(){return new Intl.DateTimeFormat('nb-NO',{weekday:'long'}).format(new Date()).replace(/^./,c=>c.toUpperCase())}
function greeting(){const h=new Date().getHours();if(h<10)return 'God morgen';if(h<17)return 'God dag';return 'God kveld'}
function weekComps(s){const m=monday();return (s.completions||[]).filter(c=>new Date(c.date)>=m)}
function todayComps(s){const d=today();return (s.completions||[]).filter(c=>c.date===d)}
function dueToday(t){if(t.type!=='daily'||t.kind!=='house')return false;const f=Math.max(0,Number(t.freq||0));return dayIndex()<=Math.min(7,f)}
function totalWeekly(s){return (s.tasks||[]).filter(t=>t.kind==='house').reduce((a,t)=>a+Number(t.freq||0)*Number(t.pts||0),0)}
function doneWeekly(s){return weekComps(s).filter(c=>c.kind==='house').reduce((a,c)=>a+Number(c.housePts||0),0)}
function dailyGoal(s){return (s.tasks||[]).filter(dueToday).reduce((a,t)=>a+Number(t.pts||0),0)}
function doneToday(s){const due=new Set((s.tasks||[]).filter(dueToday).map(t=>t.id));return todayComps(s).filter(c=>c.kind==='house'&&due.has(c.taskId)).reduce((a,c)=>a+Number(c.housePts||0),0)}
function dayPct(s){const g=dailyGoal(s);return g?Math.min(100,Math.round(doneToday(s)/g*100)):100}
function weekPct(s){const g=totalWeekly(s);return g?Math.round(doneWeekly(s)/g*700):0}
function tabs(){return `<div class="segments" style="margin:14px 0 18px"><button type="button" data-homeui-mode="day" class="${mode==='day'?'on':''}">Dag · ${dayName()}</button><button type="button" data-homeui-mode="week" class="${mode==='week'?'on':''}">Uke</button></div>`}
function currentName(s){const n=window.FlytSync?.myName?.();return String(n||s.user||'Meg').trim()||'Meg'}
function age(ts){if(!ts)return 'Ikke oppdatert ennå';const m=Math.max(0,Math.round((Date.now()-new Date(ts).getTime())/60000));if(m<2)return 'Oppdatert nå';if(m<60)return `Oppdatert for ${m} min siden`;const h=Math.round(m/60);if(h<24)return `Oppdatert for ${h} t siden`;return `Oppdatert for ${Math.round(h/24)} d siden`}
function changeText(ev){const c=ev?.changes||{};const parts=[];for(const k of ['energy','capacity','closeness','desire','stress']){if(c[k])parts.push(`${FIELD_LABEL[k]}: ${LABEL[c[k].to]||c[k].to}`)}if(c.needs){const before=new Set(c.needs.from||[]),after=new Set(c.needs.to||[]),added=[...after].filter(x=>!before.has(x)).map(x=>NEED_LABEL[x]||x),removed=[...before].filter(x=>!after.has(x)).map(x=>NEED_LABEL[x]||x);if(added.length)parts.push(`Trenger ${added.join(', ')}`);if(removed.length)parts.push(`Ikke lenger ${removed.join(', ')}`)}return parts.slice(0,3).join(' · ')||'Dagsformen er oppdatert'}
function partnerCard(){const p=partnerCtx?.partner,events=Array.isArray(partnerCtx?.events)?partnerCtx.events:[];if(!p)return '<div class="card"><strong>Partner akkurat nå</strong><p class="sub">Partneren er ikke koblet til ennå.</p></div>';const s=p.status;if(!s)return `<div class="card"><strong>${p.display_name||'Partner'} akkurat nå</strong><p class="sub">Har ikke delt dagsform ennå.</p></div>`;const needs=(s.needs||[]).map(k=>NEED_LABEL[k]||k);const heads=events.length?`<div style="margin:10px 0 12px"><div class="ey">Heads-up</div>${events.slice(0,2).map(ev=>`<div class="card" style="margin:8px 0;padding:12px"><strong>${ev.actor_name||p.display_name} har oppdatert dagsformen</strong><div class="taskmeta" style="margin-top:4px">${changeText(ev)}</div></div>`).join('')}</div>`:'';return `<div class="section"><div class="ey">Partner akkurat nå</div>${heads}<div class="card hero"><div class="row"><div class="grow"><strong>${p.display_name||'Partner'}</strong><div class="taskmeta">${age(s.updated_at)}</div></div>${events.length?`<span class="tag">${events.length} ny${events.length>1?'e':''}</span>`:''}</div><div style="margin-top:10px">${[['Energi',s.energy],['Overskudd',s.capacity],['Nærhet',s.closeness],['Sexlyst',s.desire],['Stress',s.stress]].map(([n,v])=>`<div class="row" style="padding:5px 0"><span class="grow">${n}</span><span class="tag">${LABEL[v]||'Middels'}</span></div>`).join('')}</div>${needs.length?`<div style="display:flex;flex-wrap:wrap;gap:7px;margin-top:11px">${needs.map(n=>`<span class="tag">${n}</span>`).join('')}</div>`:'<p class="sub" style="margin-bottom:0">Ingen behov markert akkurat nå.</p>'}</div></div>`}
async function loadPartner(){if(loadingPartner||!window.FlytSync?.rpc)return;loadingPartner=true;try{const {data,error}=await window.FlytSync.rpc('get_home_partner_context');if(error)throw error;partnerCtx=data||null;render({resetScroll:false});if((partnerCtx?.events||[]).length)window.FlytSync.rpc('mark_status_events_read').catch(()=>{})}catch(e){console.warn('Flyt Hjem partnerstatus kunne ikke hentes',e)}finally{loadingPartner=false}}
function render({resetScroll=false}={}){const s=bridge()?.getState?.(),c=$('#content');if(!s||!c)return;const pos=resetScroll?0:c.scrollTop,name=currentName(s),dp=dayPct(s),wp=weekPct(s),goal=dailyGoal(s),done=doneToday(s),weekly=totalWeekly(s),wdone=doneWeekly(s),day=((new Date().getDay()+6)%7)+1,expected=day*100,delta=wp-expected;c.dataset.flytOwner='home';if(mode==='day'){c.innerHTML=`<div class="ey">Husholdningsmotor</div><h1 class="title">${greeting()}, ${name}</h1><p class="sub">I dag skal kjennes som en dag, ikke som en syvendedel av en uke.</p>${tabs()}<div class="card hero"><div class="row"><div class="grow"><strong>${dayName()}</strong><p>${dp>=100?'Dagens faste gjøremål er i mål.':'Dere er '+dp+'% gjennom dagens faste gjøremål.'}</p></div><span class="tag">${dp}%</span></div><div class="progress"><i style="width:${Math.min(100,dp)}%"></i></div></div><div class="stat"><div><b>${dp}%</b><span>I dag</span></div><div><b>${done}</b><span>dagspoeng</span></div><div><b>${goal}</b><span>dagens mål</span></div></div>${partnerCard()}<div class="card"><strong>${dp>=100?'Dagen er tatt.':'Mer initiativ. Mindre masing.'}</strong><p class="sub">${dp>=100?'Alt som var dagsbundet er gjort. Fleksible ukeoppgaver kan fortsatt tas hvis dere har driv.':'Ta noe før det blir spurt om. Det gir både personlig poeng og flyt i huset.'}</p></div>`}else{c.innerHTML=`<div class="ey">Husholdningsmotor</div><h1 class="title">${greeting()}, ${name}</h1><p class="sub">Her ser dere hele ukerytmen, uten at den får lov til å definere om mandagen føltes bra.</p>${tabs()}<div class="card hero"><div class="row"><div class="grow"><strong>Ukebanken</strong><p>${delta>=0?`Dere ligger ${delta}% foran ukerytmen.`:`Dere ligger ${Math.abs(delta)}% bak ukerytmen.`}</p></div><span class="tag">${wp}/700%</span></div><div class="progress"><i style="width:${Math.min(100,wp/7)}%"></i></div></div><div class="stat"><div><b>${wp}%</b><span>Uken</span></div><div><b>${wdone}</b><span>gjort</span></div><div><b>${weekly}</b><span>ukepoeng</span></div></div>${partnerCard()}<div class="card"><strong>Ukemålet er retning, ikke dom.</strong><p class="sub">Fleksible oppgaver kan tas når det passer. Dagsvisningen forteller om dagens faktiske belastning.</p></div>`}document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('on',b.dataset.view==='home'));c.scrollTop=pos;requestAnimationFrame(()=>{c.scrollTop=pos});if(!partnerCtx&&!loadingPartner)loadPartner()}
document.addEventListener('click',e=>{const nav=e.target.closest('#nav button[data-view="home"]');if(nav){e.preventDefault();e.stopImmediatePropagation();const s=bridge()?.getState?.();if(s&&s.view!=='home')bridge().setState({...s,view:'home'});partnerCtx=null;render({resetScroll:true});return}const tab=e.target.closest('[data-homeui-mode]');if(tab){e.preventDefault();e.stopImmediatePropagation();mode=tab.dataset.homeuiMode==='week'?'week':'day';render({resetScroll:true})}},true);
window.FlytHomeUI={render};
})();
