(()=>{
'use strict';
const $=s=>document.querySelector(s);
const bridge=()=>window.FlytBridge;
const VERSION='20260902-0100';
let mode='day',partnerCtx=null,loadingPartner=false;
const LABEL={low:'Lav',med:'Middels',high:'Høy'};
const NEED_LABEL={relief:'Avlastning',closeness:'Nærhet',sex:'Intimitet',initiative:'Initiativ',alone:'Alenetid',quiet:'Ro'};
const FIELD_LABEL={energy:'Energi',capacity:'Overskudd',closeness:'Nærhet',desire:'Lyst',stress:'Stress'};
const QUICK_META={need:{label:'Behov',icon:'♡',tone:'#80558f',bg:'#f3edf7'},wish:{label:'Ønske',icon:'☆',tone:'#c85d35',bg:'#fff0e8'},practical:{label:'Praktisk',icon:'✓',tone:'#4d8464',bg:'#edf5ef'},reward:{label:'Poengbelønning',icon:'♢',tone:'#c84457',bg:'#faecef'}};
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function taskReference(value){return window.FlytTaskLanguage?.taskReference?.(value)||`oppgaven «${String(value||'gjøremålet').trim()}»`}
function monday(){const d=new Date(),x=new Date(d),day=(x.getDay()+6)%7;x.setHours(0,0,0,0);x.setDate(x.getDate()-day);return x}
function today(){const d=new Date();const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`}
function monthKey(){return today().slice(0,7)}
function isoToday(){const n=new Date().getDay();return n===0?7:n}
function preferredDays(t){return [...new Set((Array.isArray(t?.preferredDays)?t.preferredDays:[]).map(Number).filter(n=>n>=1&&n<=7))]}
function scheduledToday(t){const days=preferredDays(t);return !days.length||days.includes(isoToday())}
function dayName(){return new Intl.DateTimeFormat('nb-NO',{weekday:'long'}).format(new Date()).replace(/^./,c=>c.toUpperCase())}
function greeting(){const h=new Date().getHours();if(h<6)return 'Hei';if(h<10)return 'God morgen';if(h<17)return 'God dag';return 'God kveld'}
function weekComps(s){const m=monday();return (s.completions||[]).filter(c=>new Date(c.date+'T12:00:00')>=m)}
function monthComps(s){const ym=monthKey();return (s.completions||[]).filter(c=>String(c.date||'').startsWith(ym))}
function todayComps(s){const d=today();return (s.completions||[]).filter(c=>c.date===d)}
function dailyTasks(s){return (s.tasks||[]).filter(t=>t.kind==='house'&&t.type==='daily')}
function todayTasks(s){return window.FlytDayPlan?.planTasks?.(s,today())||dailyTasks(s).filter(scheduledToday)}
function weeklyTasks(s){return (s.tasks||[]).filter(t=>t.kind==='house'&&t.type==='flex')}
function monthlyTasks(s){return (s.tasks||[]).filter(t=>t.kind==='house'&&t.type==='period')}
function goalFor(tasks){return tasks.reduce((a,t)=>a+Math.max(1,Number(t.freq||1))*Number(t.pts||0),0)}
function doneFor(comps,tasks){const ids=new Set(tasks.map(t=>String(t.id)));return comps.filter(c=>c.kind==='house'&&ids.has(String(c.taskId))).reduce((a,c)=>a+Number(c.housePts||0),0)}
function dailyGoal(s){return todayTasks(s).reduce((a,t)=>a+Number(t.pts||0),0)}
function doneToday(s){const completed=new Set(todayComps(s).filter(c=>c.kind==='house').map(c=>String(c.taskId)));return todayTasks(s).reduce((a,t)=>a+(completed.has(String(t.id))?Number(t.pts||0):0),0)}
function dayPlanProgress(s){const fromModule=window.FlytDayPlan?.progress?.(s,today());if(fromModule)return fromModule;const tasks=todayTasks(s),doneIds=new Set(todayComps(s).map(c=>String(c.taskId)));return{done:tasks.filter(t=>doneIds.has(String(t.id))).length,total:tasks.length,tasks}}
function todayPointTotal(s){return todayComps(s).reduce((sum,c)=>sum+Number(c.taskSnapshot?.pts??c.housePts??0),0)}
function totalWeekly(s){return goalFor([...dailyTasks(s),...weeklyTasks(s)])}
function doneWeekly(s){const cs=weekComps(s);return [...dailyTasks(s),...weeklyTasks(s)].reduce((sum,t)=>{const matches=cs.filter(c=>c.kind==='house'&&String(c.taskId)===String(t.id));const count=t.type==='daily'?new Set(matches.map(c=>String(c.date||''))).size:matches.length;const goal=Math.max(1,Number(t.freq||1));return sum+Math.min(goal,count)*Number(t.pts||0)},0)}
function totalMonthly(s){return goalFor(monthlyTasks(s))}
function doneMonthly(s){return doneFor(monthComps(s),monthlyTasks(s))}
function pct(done,goal){return goal?Math.min(100,Math.round(done/goal*100)):0}
function tabs(){return `<div class="segments homeSegments" style="grid-template-columns:repeat(3,minmax(0,1fr));margin:14px 0 18px"><button type="button" data-homeui-mode="day" class="${mode==='day'?'on':''}">${dayName()}</button><button type="button" data-homeui-mode="week" class="${mode==='week'?'on':''}">Uke</button><button type="button" data-homeui-mode="month" class="${mode==='month'?'on':''}">Måned</button></div>`}
function currentName(s){const n=window.FlytSync?.myName?.();return String(n||s.user||'Meg').trim()||'Meg'}
function partnerName(s){const fromRpc=partnerCtx?.partner?.display_name;if(fromRpc)return fromRpc;const members=window.FlytSync?.getContext?.()?.members||[],p=members.find(m=>m.display_name&&m.display_name!==s?.user);return p?.display_name||Object.keys(s?.points||{}).find(n=>n!==s?.user)||'Partner'}
function age(ts){if(!ts)return 'Ikke oppdatert ennå';const m=Math.max(0,Math.round((Date.now()-new Date(ts).getTime())/60000));if(m<2)return 'Oppdatert nå';if(m<60)return `Oppdatert for ${m} min siden`;const h=Math.round(m/60);if(h<24)return `Oppdatert for ${h} t siden`;return `Oppdatert for ${Math.round(h/24)} d siden`}
function changeText(ev){const c=ev?.changes||{},parts=[];for(const k of ['energy','capacity','closeness','desire','stress'])if(c[k])parts.push(`${FIELD_LABEL[k]}: ${LABEL[c[k].to]||c[k].to}`);if(c.needs){const before=new Set(c.needs.from||[]),after=new Set(c.needs.to||[]),added=[...after].filter(x=>!before.has(x)).map(x=>NEED_LABEL[x]||x),removed=[...before].filter(x=>!after.has(x)).map(x=>NEED_LABEL[x]||x);if(added.length)parts.push(`Trenger ${added.join(', ')}`);if(removed.length)parts.push(`Ikke lenger ${removed.join(', ')}`)}return parts.slice(0,3).join(' · ')||'Dagsformen er oppdatert'}
function partnerRequest(s,type,name){return (Array.isArray(s?.seenRequests)?s.seenRequests:[]).filter(r=>r&&r.type===type&&r.by===name&&!r.deleted&&!r.done).sort((a,b)=>Number(b.createdAt||b.id||0)-Number(a.createdAt||a.id||0))[0]||null}
function partnerReward(s,name){return (Array.isArray(s?.rewards)?s.rewards:[]).filter(r=>r&&r.by===name).sort((a,b)=>Number(b.createdAt||b.id||0)-Number(a.createdAt||a.id||0))[0]||null}
function statusSummaryMarkup(status){if(!status)return '<div style="margin-top:13px;color:var(--muted);font-size:14px">Har ikke delt dagsform ennå.</div>';const needs=(status.needs||[]).map(k=>NEED_LABEL[k]||k),energy=LABEL[status.energy]||'Middels',capacity=LABEL[status.capacity]||'Middels',stress=LABEL[status.stress]||'Middels';return `<div style="margin-top:14px;padding:12px 13px;border:1px solid #efd8cf;border-radius:15px;background:#fffaf7"><div style="font-size:15.5px;line-height:1.45;color:var(--ink)">Energi <strong>${esc(energy)}</strong> <span style="color:#bda69d">·</span> Overskudd <strong>${esc(capacity)}</strong> <span style="color:#bda69d">·</span> Stress <strong>${esc(stress)}</strong></div>${needs.length?`<div style="margin-top:7px;font-size:15.5px;line-height:1.35;color:var(--deep);font-weight:700">Trenger: <strong>${esc(needs.slice(0,2).join(' · '))}</strong></div>`:''}</div>`}
function quickRow(kind,item,{empty,destination,badge}={}){const m=QUICK_META[kind],text=item?.text||item?.title||empty||'Ingen aktive',isNew=kind!=='reward'&&item&&!item.seen;return `<button type="button" data-home-destination="${destination}" style="width:100%;display:grid;grid-template-columns:42px minmax(0,1fr) auto;align-items:center;gap:10px;text-align:left;border:0;border-top:1px solid var(--line);background:#fffdfb;padding:10px 12px;color:var(--ink);font:inherit"><span aria-hidden="true" style="width:38px;height:38px;border-radius:50%;display:grid;place-items:center;background:${m.bg};color:${m.tone};font-size:23px;font-weight:700">${m.icon}</span><span style="min-width:0"><strong style="display:block;color:${m.tone};font-size:13px;line-height:1.15">${m.label}</strong><span style="display:block;margin-top:2px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;font-size:14px">${esc(text)}</span></span><span style="display:flex;align-items:center;gap:7px">${isNew?'<span class="tag" style="background:#ffe5df;color:#ad4a3c">Ny</span>':badge?`<span class="taskmeta">${esc(badge)}</span>`:''}<span aria-hidden="true" style="font-size:24px;color:var(--muted);line-height:1">›</span></span></button>`}
function partnerCard(s){const p=partnerCtx?.partner,name=partnerName(s),status=p?.status,events=Array.isArray(partnerCtx?.events)?partnerCtx.events:[],need=partnerRequest(s,'need',name),wish=partnerRequest(s,'wish',name),practical=partnerRequest(s,'practical',name),reward=partnerReward(s,name),rewardBadge=reward?.requiresPoints?`${Math.max(1,Number(reward.cost)||1)} p`:reward?'Åpen':'';return `<div class="card" style="padding:0;overflow:hidden;margin-top:18px;background:linear-gradient(145deg,#fff2ea,#fffaf7);border-color:#efd2c7;box-shadow:0 12px 30px #8b554314"><div style="padding:17px 17px 15px"><div class="row" style="align-items:center"><div aria-hidden="true" style="width:46px;height:46px;flex:0 0 46px;border-radius:50%;display:grid;place-items:center;background:#fac0aa;color:#ad4a3c;font-size:25px">♡</div><div class="grow" style="margin-left:11px"><strong style="display:block;font:600 23px/1.05 Georgia,serif">${esc(name)} akkurat nå</strong><div class="taskmeta" style="margin-top:4px;color:#9a8178">${status?age(status.updated_at):'Dagsform ikke oppdatert ennå'}</div></div>${events.length?`<span class="tag">${events.length} ny${events.length>1?'e':''}</span>`:''}</div>${statusSummaryMarkup(status)}</div><div style="border-top:1px solid var(--line);border-bottom:1px solid var(--line);overflow:hidden">${quickRow('need',need,{empty:'Ingen aktivt behov',destination:'seen'})}${quickRow('wish',wish,{empty:'Ingen aktivt ønske',destination:'seen'})}${quickRow('practical',practical,{empty:'Ingen praktisk beskjed',destination:'seen'})}${quickRow('reward',reward,{empty:'Ingen poengbelønning akkurat nå',destination:'rewards',badge:rewardBadge})}</div><div style="display:flex;justify-content:center;gap:10px;padding:12px 14px"><button type="button" class="small" data-home-destination="seen" style="border:0;background:transparent;color:var(--deep);font-weight:850">Se behov og ønsker</button><span class="taskmeta" aria-hidden="true">·</span><button type="button" class="small" data-home-destination="rewards" style="border:0;background:transparent;color:var(--deep);font-weight:850">Belønninger</button></div></div>`}
function journeyKey(s){const id=window.FlytSync?.getContext?.()?.user_id;return id?`user:${id}`:`name:${currentName(s)}`}
function firstWinSeen(s){return new Set(Array.isArray(s?.coupleJourney?.firstWinSeenBy)?s.coupleJourney.firstWinSeenBy:[]).has(journeyKey(s))}
function markFirstWinSeen(s){const key=journeyKey(s),seen=new Set(Array.isArray(s?.coupleJourney?.firstWinSeenBy)?s.coupleJourney.firstWinSeenBy:[]);seen.add(key);bridge()?.setState?.({...s,coupleJourney:{...(s.coupleJourney||{}),firstWinSeenBy:[...seen]}});window.FlytSync?.queueSave?.()}
function hasPartner(){const context=window.FlytSync?.getContext?.();return (context?.members||[]).some(member=>String(member.id)!==String(context?.user_id))}
function firstWinMarkup(s){
  if(!s?.setupDone||!hasPartner()||!window.FlytCoupleInsights)return'';
  const win=window.FlytCoupleInsights.firstSharedWin(s),name=partnerName(s);
  if(win.stage==='completed'){
    if(firstWinSeen(s))return'';
    return `<section class="card" data-first-win-card="completed" style="margin:14px 0;border-color:#dce5ce;background:linear-gradient(145deg,#fbfdf7,#edf3e5)"><div class="row" style="align-items:flex-start"><div aria-hidden="true" style="width:44px;height:44px;display:grid;place-items:center;border-radius:15px;background:#fff;font-size:24px">✓</div><div class="grow"><div class="ey" style="color:#607644">Første felles seier</div><strong style="display:block;font:600 21px/1.2 Georgia;margin-top:5px">Dere fullførte ${esc(taskReference(win.taskName))} sammen</strong><p class="sub" style="margin:7px 0 0">Én tok initiativ eller spurte. Den andre svarte. Handlingen ble gjort. Det er Flyt-løkken.</p></div></div><button type="button" class="primary full" data-first-win-finish="1" style="margin-top:14px">Se hva dere får til sammen</button></section>`;
  }
  if(win.stage==='awaiting'){
    const mine=win.request?.by===s.user;
    return `<section class="card" data-first-win-card="awaiting" style="margin:14px 0;border-color:#dfe6d2;background:linear-gradient(145deg,#fffdf9,#f4f5eb)"><div class="ey">Første felles seier · nesten i mål</div><strong style="display:block;font:600 21px/1.2 Georgia;margin-top:6px">${mine?'Din del er gjort':`${name} har fullført ${esc(taskReference(win.taskName))}`}</strong><p class="sub" style="margin:7px 0 0">${mine?`Når ${esc(name)} har sett det, er den første felles løkken komplett.`:'Se handlingen og send gjerne et lite takk. Da lander seieren hos dere begge.'}</p><button type="button" class="primary full" data-home-destination="seen" style="margin-top:14px">Åpne Sett</button></section>`;
  }
  if(win.stage==='started'||win.stage==='accepted'){
    const mine=win.request?.by===s.user,label=win.stage==='accepted'?'Avtalt – nå gjenstår handlingen':mine?`Invitasjonen til samarbeid er sendt`:`${name} har startet deres første felles seier`;
    return `<section class="card" data-first-win-card="active" style="margin:14px 0;border-color:#e7cfc4;background:linear-gradient(145deg,#fffdf9,#fff1e9)"><div class="ey">Første felles seier · ${win.stage==='accepted'?'2 av 3':'1 av 3'}</div><strong style="display:block;font:600 21px/1.2 Georgia;margin-top:6px">${esc(label)}</strong><p class="sub" style="margin:7px 0 0">${esc(win.taskName)} · ${win.stage==='accepted'?'Når den er utført, har dere fullført hele løkken.':'Se og svar i Sett.'}</p><button type="button" class="primary full" data-home-destination="seen" style="margin-top:14px">${win.stage==='accepted'?'Fullfør i Sett':'Åpne Sett'}</button></section>`;
  }
  return'';
}
function startFirstWin(taskId){const s=bridge()?.getState?.(),task=(s?.tasks||[]).find(item=>String(item.id)===String(taskId));if(!s||!task)return;const item=window.FlytCoupleCore?.makeInitiative?.({state:s,task,partnerName:partnerName(s)})||null;if(!item)return;bridge().setState({...s,seenRequests:[{...item,journeyKey:'first_shared_win'},...(s.seenRequests||[])],coupleJourney:{...(s.coupleJourney||{}),firstWinStartedAt:s.coupleJourney?.firstWinStartedAt||new Date().toISOString()}});window.FlytSync?.queueSave?.();bridge()?.toast?.(`Første felles seier er startet med ${taskReference(task.name)}`);render({resetScroll:false});window.FlytSeenRequestAlert?.checkAlerts?.()}
async function loadPartner(){if(loadingPartner||!window.FlytSync?.rpc)return;loadingPartner=true;try{const {data,error}=await window.FlytSync.rpc('get_home_partner_context');if(error)throw error;partnerCtx=data||null;if(bridge()?.getState?.()?.view==='home')render({resetScroll:false});if((partnerCtx?.events||[]).length)window.FlytSync.rpc('mark_status_events_read').catch(()=>{})}catch(e){console.warn('Flyt Hjem partnerstatus kunne ikke hentes',e)}finally{loadingPartner=false}}
function statsMarkup(p,done,goal,label,pointsLabel,goalLabel){return `<div class="stat homeStats"><div><b>${p}%</b><span>${label}</span></div><div><b>${done}</b><span>${pointsLabel}</span></div><div><b>${goal}</b><span>${goalLabel}</span></div></div>`}
function settleScroll(c,pos,forceTop){const target=forceTop?0:Math.max(0,pos||0);c.style.overflowAnchor='none';const apply=()=>{c.scrollTop=target};apply();requestAnimationFrame(()=>{apply();requestAnimationFrame(apply)});setTimeout(()=>{apply();c.style.overflowAnchor=''},90)}
function render({resetScroll=false}={}){
  const s=bridge()?.getState?.(),c=$('#content');
  if(!s||!c||s.view!=='home')return;
  const pos=resetScroll?0:c.scrollTop,name=currentName(s),plan=dayPlanProgress(s),dayPct=plan.total?Math.round(plan.done/plan.total*100):0,dayPoints=todayPointTotal(s),dayRegistrations=todayComps(s).length,wg=totalWeekly(s),wd=doneWeekly(s),wp=pct(wd,wg),mg=totalMonthly(s),md=doneMonthly(s),mp=pct(md,mg);
  c.dataset.flytOwner='home';
  let intro,hero,stats,tail;
  if(mode==='day'){
    intro='Ett blikk på hva dere trenger – og ett konkret neste steg.';
    hero=`<div class="card hero"><div class="row"><div class="grow"><strong>Dagens plan</strong><p>${!plan.total?'Dagen er åpen. Legg til det som er viktig i dag.':plan.done>=plan.total?'Alt i dagens plan er gjort.':plan.done?`${plan.done} fullført · ${plan.total-plan.done} gjenstår.`:`${plan.total} gjøremål ligger i planen. Tilpass det som ikke passer i dag.`}</p></div><span class="tag">${plan.done?`${plan.done} gjort`:'Åpen'}</span></div><div class="progress"><i style="width:${dayPct}%"></i></div></div>`;
    stats=`<div class="stat homeStats"><div><b>${plan.done}</b><span>gjort fra planen</span></div><div><b>${dayPoints}</b><span>poeng i dag</span></div><div><b>${dayRegistrations}</b><span>registreringer</span></div></div>`;
    tail=`<div class="card"><strong>${!plan.total?'Ingen fast lås på dagen.':plan.done>=plan.total?'Dagens plan er tatt.':'Planen kan tilpasses.'}</strong><p class="sub">${!plan.total?'Hele gjøremålsbiblioteket er tilgjengelig under Gjøre.':plan.done>=plan.total?'Ekstra gjøremål kan fortsatt registreres og gir poeng.':'Legg til, fjern eller flytt gjøremål under Gjøre dersom dagen blir annerledes enn oppsettet.'}</p></div>`;
  }else if(mode==='week'){
    intro='Se retningen for uken, uten å gjøre forholdet til et regneark.';
    hero=`<div class="card hero"><div class="row"><div class="grow"><strong>Ukemålet</strong><p>${!wg?'Ingen gjøremål med ukerytme er valgt ennå.':wp>=100?'Ukens mål er nådd.':`Dere er ${wp}% gjennom ukens mål.`}</p></div><span class="tag">${wp}%</span></div><div class="progress"><i style="width:${wp}%"></i></div></div>`;
    stats=statsMarkup(wp,wd,wg,'Uken','ukepoeng','ukens mål');
    tail=`<div class="card"><strong>${!wg?'Ingen ukerytme ennå.':'Ukemålet er retning, ikke tak.'}</strong><p class="sub">${!wg?'Gjøremål kan legges til i Oppsett når dere ønsker dem.':'Ekstra utføringer registreres og gir poeng, men målet teller etter valgt rytme: dager per uke eller ganger per uke.'}</p></div>`;
  }else{
    intro='De større rytmene som lett forsvinner i en travel hverdag.';
    hero=`<div class="card hero"><div class="row"><div class="grow"><strong>Månedsmålet</strong><p>${!mg?'Ingen gjøremål med månedsrytme er valgt ennå.':mp>=100?'Månedens mål er nådd.':`Dere er ${mp}% gjennom månedens mål.`}</p></div><span class="tag">${mp}%</span></div><div class="progress"><i style="width:${mp}%"></i></div></div>`;
    stats=statsMarkup(mp,md,mg,'Måneden','månedspoeng','månedens mål');
    tail=`<div class="card"><strong>${!mg?'Ingen månedsrytme ennå.':'Måneden viser de større rytmene.'}</strong><p class="sub">${!mg?'Månedlige gjøremål kan legges til i Oppsett når dere trenger dem.':'Målet teller ønsket antall ganger, men ekstra utføringer er fortsatt lov og blir registrert.'}</p></div>`;
  }
  const first=firstWinMarkup(s);
  c.innerHTML=`<div class="ey">Hjem · Dere i dag</div><h1 class="title">Dere i dag</h1><p class="sub">${greeting()}, ${esc(name)}. ${intro}</p><div id="homeNudgeMount" ${first?'data-first-win-active="1"':''} aria-live="polite">${first}</div>${tabs()}${hero}${stats}${partnerCard(s)}${tail}`;
  document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('on',b.dataset.view==='home'));
  settleScroll(c,pos,resetScroll);
  if(!partnerCtx&&!loadingPartner)loadPartner();
  queueMicrotask(()=>window.FlytNudgeUI?.augment?.());
}
function claim({resetScroll=false}={}){const s=bridge()?.getState?.();if(s?.view!=='home')return false;render({resetScroll});return document.querySelector('#content')?.dataset.flytOwner==='home'}
document.addEventListener('click',e=>{const nav=e.target.closest('#nav button[data-view="home"]');if(nav){e.preventDefault();e.stopImmediatePropagation();nav.blur?.();const s=bridge()?.getState?.();if(s&&s.view!=='home')bridge().setState({...s,view:'home'});partnerCtx=null;render({resetScroll:true});window.FlytNudgeUI?.refreshStatus?.(true);return}const start=e.target.closest('[data-first-win-start]');if(start&&bridge()?.getState?.()?.view==='home'){e.preventDefault();e.stopImmediatePropagation();startFirstWin(start.dataset.firstWinStart);return}const finish=e.target.closest('[data-first-win-finish]');if(finish&&bridge()?.getState?.()?.view==='home'){e.preventDefault();e.stopImmediatePropagation();const s=bridge().getState();markFirstWinSeen(s);bridge().setState({...bridge().getState(),view:'us'});queueMicrotask(()=>window.FlytOss?.render?.({refresh:true,resetScroll:true}));return}const tab=e.target.closest('[data-homeui-mode]');if(tab){e.preventDefault();e.stopImmediatePropagation();tab.blur?.();mode=['day','week','month'].includes(tab.dataset.homeuiMode)?tab.dataset.homeuiMode:'day';render({resetScroll:true});return}const destination=e.target.closest('[data-home-destination]');if(destination&&bridge()?.getState?.()?.view==='home'){e.preventDefault();e.stopImmediatePropagation();const next=destination.dataset.homeDestination,s=bridge().getState();if(!['seen','rewards','us'].includes(next)||!s)return;bridge().setState({...s,view:next});queueMicrotask(()=>next==='seen'?window.FlytSeenUI?.render?.():next==='rewards'?window.FlytRewardsUI?.render?.():window.FlytOss?.render?.({refresh:true,resetScroll:true}));return}},true);
window.FlytHomeUI={render,claim,version:VERSION};
const claimSoon=()=>queueMicrotask(()=>claim({resetScroll:false}));
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',claimSoon,{once:true});else claimSoon();
window.addEventListener('pageshow',claimSoon);
})();
