(()=>{
'use strict';
const Z=300;
let activeDismiss=null;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function close(){if(activeDismiss){const dismiss=activeDismiss;activeDismiss=null;dismiss();return}document.querySelector('#flytGlobalModal')?.remove()}
function shell({ey='Flyt',title='',text='',body='',ok='OK',cancel='Avbryt',showCancel=true}={}){return new Promise(resolve=>{close();const el=document.createElement('div');el.id='flytGlobalModal';el.style.cssText=`position:fixed;inset:0;z-index:${Z};background:#3a211b88;display:flex;align-items:center;justify-content:center;padding:22px`;el.innerHTML=`<div role="dialog" aria-modal="true" style="width:min(390px,100%);max-height:88dvh;overflow:auto;background:#fffaf7;border:1px solid #ead8d0;border-radius:26px;padding:22px;box-shadow:0 24px 70px #3b211b55"><div style="font-size:11px;color:#ad4a3c;font-weight:900;letter-spacing:.12em;text-transform:uppercase">${esc(ey)}</div>${title?`<h2 style="font:500 28px/1.12 Georgia;margin:10px 0 10px">${esc(title)}</h2>`:''}${text?`<p style="color:#806d65;line-height:1.5;margin:0 0 18px">${esc(text)}</p>`:''}${body}<div style="display:grid;grid-template-columns:${showCancel?'1fr 1fr':'1fr'};gap:10px;margin-top:20px">${showCancel?`<button type="button" id="flytModalCancel" class="secondary" style="min-height:50px">${esc(cancel)}</button>`:''}<button type="button" id="flytModalOk" class="primary" style="min-height:50px">${esc(ok)}</button></div></div>`;let settled=false;const done=v=>{if(settled)return;settled=true;if(activeDismiss===dismiss)activeDismiss=null;document.removeEventListener('keydown',key);el.remove();resolve(v)},dismiss=()=>done(null),key=e=>{if(e.key==='Escape'&&showCancel){e.preventDefault();done(null)}if(e.key==='Enter'&&e.target===document.body){e.preventDefault();done(true)}};activeDismiss=dismiss;el.addEventListener('click',e=>{if(e.target===el&&showCancel)done(null)});document.body.appendChild(el);document.addEventListener('keydown',key);el.querySelector('#flytModalCancel')?.addEventListener('click',()=>done(null));el.querySelector('#flytModalOk')?.addEventListener('click',()=>done(true));requestAnimationFrame(()=>el.querySelector('#flytModalOk')?.focus({preventScroll:true}))})}
async function confirm(opts={}){return !!(await shell(opts))}
async function notice(opts={}){await shell({...opts,showCancel:false});return true}
function prompt({ey='Flyt',title='Skriv inn',text='',label='',placeholder='',value='',ok='Lagre',cancel='Avbryt',type='text',min=null,max=null}={}){return new Promise(resolve=>{close();const el=document.createElement('div');el.id='flytGlobalModal';el.style.cssText=`position:fixed;inset:0;z-index:${Z};background:#3a211b88;display:flex;align-items:center;justify-content:center;padding:22px`;el.innerHTML=`<div role="dialog" aria-modal="true" style="width:min(390px,100%);max-height:88dvh;overflow:auto;background:#fffaf7;border:1px solid #ead8d0;border-radius:26px;padding:22px;box-shadow:0 24px 70px #3b211b55"><div style="font-size:11px;color:#ad4a3c;font-weight:900;letter-spacing:.12em;text-transform:uppercase">${esc(ey)}</div><h2 style="font:500 28px/1.12 Georgia;margin:10px 0 10px">${esc(title)}</h2>${text?`<p style="color:#806d65;line-height:1.5;margin:0 0 18px">${esc(text)}</p>`:''}${label?`<label for="flytModalInput" style="display:block;font-size:12px;font-weight:850;margin-bottom:7px">${esc(label)}</label>`:''}<input id="flytModalInput" type="${type==='number'?'number':'text'}" ${type==='number'?'inputmode="numeric"':''} ${min!==null?`min="${esc(min)}"`:''} ${max!==null?`max="${esc(max)}"`:''} value="${esc(value)}" placeholder="${esc(placeholder)}" style="width:100%;min-height:50px;border:1px solid #ead8d0;border-radius:15px;background:#fff;padding:12px 14px;outline:none"><div style="display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:20px"><button type="button" id="flytModalCancel" class="secondary" style="min-height:50px">${esc(cancel)}</button><button type="button" id="flytModalOk" class="primary" style="min-height:50px">${esc(ok)}</button></div></div>`;const input=el.querySelector('#flytModalInput');let settled=false;const done=v=>{if(settled)return;settled=true;if(activeDismiss===dismiss)activeDismiss=null;el.remove();resolve(v)},dismiss=()=>done(null);activeDismiss=dismiss;el.addEventListener('click',e=>{if(e.target===el)done(null)});document.body.appendChild(el);el.querySelector('#flytModalCancel').onclick=()=>done(null);el.querySelector('#flytModalOk').onclick=()=>{const v=input.value.trim();if(!v){input.focus();input.style.borderColor='#e87961';return}done(v)};input.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();el.querySelector('#flytModalOk').click()}if(e.key==='Escape'){e.preventDefault();done(null)}});setTimeout(()=>{input.focus({preventScroll:true});input.select?.()},30)})}
window.FlytModal={confirm,prompt,notice,close,version:'20260826-0925'};
window.alert=message=>{notice({ey:'Flyt',title:'Beskjed',text:String(message||''),ok:'OK'});};
})();