(()=>{
'use strict';
if(!window.supabase)return;
const URL='https://uopzveejnztbovncqbpq.supabase.co';
const KEY='sb_publishable_uK6xd8TJhN2MY10qHSQ2GQ_7hSIr2gv';
const sb=window.supabase.createClient(URL,KEY);
const $=s=>document.querySelector(s);
const bridge=()=>window.FlytBridge;
const LEVELS=['low','med','high'];
const LABEL={low:'Lav',med:'Middels',high:'Høy'};
const NEEDS=[['relief','💛 Avlastning'],['closeness','💗 Nærhet'],['sex','🔥 Sex'],['initiative','⚡ Initiativ'],['alone','🌿 Alenetid'],['quiet','🌙 Ro']];
let ctx=null,rows=[],rendering=false;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function fastContext(){const {data,error}=await sb.rpc('get_oss_context');if(error)throw error;ctx={user_id:data?.user_id,members:Array.isArray(data?.members)?data.members:[]};rows=Array.isArray(data?.statuses)?data.statuses:[];return data}
async function legacyContext(){const a=await sb.rpc('get_my_flyt_context');if(a.error)throw a.error;const b=await sb.rpc('get_household_status');if(b.error)throw b.error;ctx={user_id:a.data?.user_id,members:Array.isArray(a.data?.members)?a.data.members:[]};rows=Array.isArray(b.data)?b.data:[];return{user_id:ctx.user_id,members:ctx.members,statuses:rows}}
async function refreshContext(){try{return await fastContext()}catch(e){console.warn('Flyt Oss fast context failed, using fallback',e);return await legacyContext()}}
function fallback(){return{user_id:ctx?.user_id,energy:'med',capacity:'med',closeness:'med',desire:'med',stress:'med',needs:[],updated_at:null}}
function mine(){return rows.find(x=>String(x.user_id)===String(ctx?.user_id))||fallback()}
function theirs(){return rows.find(x=>String(x.user_id)!==String(ctx?.user_id))||null}
function setMine(a){const row={...a,user_id:ctx?.user_id,updated_at:new Date().toISOString()};const i=rows.findIndex(x=>String(x.user_id)===String(ctx?.user_id));if(i>=0)rows[i]=row;else rows.push(row);return row}
function partnerMember(){return ctx?.members?.find(x=>String(x.id)!==String(ctx?.user_id))||null}
function age(ts){if(!ts)return 'Ikke oppdatert ennå';const m=Math.max(0,Math.round((Date.now()-new Date(ts).getTime())/60000));if(m<2)return 'Oppdatert nå';if(m<60)return `Oppdatert for ${m} min siden`;const h=Math.round(m/60);if(h<24)return `Oppdatert for ${h} t siden`;return `Oppdatert for ${Math.round(h/24)} d siden`}
function seg(k,v){return `<div class="segments">${LEVELS.map(x=>`<button type="button" data-oss-level="${k}" data-oss-value="${x}" class="${v===x?'on':''}">${LABEL[x]}</button>`).join('')}</div>`}
function card(name,key,val){return `<div class="card"><strong>${name}</strong>${seg(key,val)}</div>`}
function partnerCard(){const member=partnerMember(),p=theirs();if(!member)return '<div class="card"><p class="sub">Partneren er ikke koblet til ennå.</p></div>';if(!p)return `<div class="card"><strong>${esc(member.display_name||'Partner')}</strong><p class="sub">Har ikke delt dagsform ennå.</p></div>`;const stats=[['Energi',p.energy],['Overskudd',p.capacity],['Nærhet',p.closeness],['Sexlyst',p.desire],['Stress',p.stress]].map(([n,v])=>`<div class="row" style="padding:5px 0"><span class="grow">${n}</span><span class="tag">${LABEL[v]||'Middels'}</span></div>`).join('');const needs=(p.needs||[]).map(k=>NEEDS.find(x=>x[0]===k)?.[1]).filter(Boolean);return `<div class="card hero"><strong>${esc(member.display_name||'Partner')} akkurat nå</strong><div class="taskmeta">${age(p.updated_at)}</div><div style="margin-top:8px">${stats}</div><div class="taskmeta" style="margin-top:11px">Behov</div>${needs.length?`<div style="display:flex;flex-wrap:wrap;gap:7px;margin-top:7px">${needs.map(n=>`<span class="tag">${n}</span>`).join('')}</div>`:'<p class="sub">Ingen behov markert akkurat nå.</p>'}</div>`}
function askNotify(){const partner=partnerMember();if(!partner)return Promise.resolve(false);return new Promise(resolve=>{document.querySelector('#ossNotifyModal')?.remove();const el=document.createElement('div');el.id='ossNotifyModal';el.style.cssText='position:fixed;inset:0;z-index:300;background:#3a211b88;display:flex;align-items:center;justify-content:center;padding:22px';el.innerHTML=`<div role="dialog" aria-modal="true" style="width:min(370px,100%);background:#fffaf7;border:1px solid #ead8d0;border-radius:24px;padding:22px;box-shadow:0 24px 70px #3b211b55"><div class="ey">Dagsform</div><h2 style="font:500 27px/1.15 Georgia;margin:8px 0 8px">Varsle ${esc(partner.display_name||'partneren')}?</h2><p class="sub" style="margin-top:0">Send et lite heads-up om at dagsformen eller behovene dine har endret seg.</p><div style="display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:18px"><button type="button" id="ossNotifyNo" class="secondary">Bare oppdater</button><button type="button" id="ossNotifyYes" class="primary">Oppdater og varsle</button></div></div>`;const done=value=>{el.remove();resolve(value)};el.addEventListener('click',e=>{if(e.target===el)done(false)});document.body.appendChild(el);el.querySelector('#ossNotifyNo').onclick=()=>done(false);el.querySelector('#ossNotifyYes').onclick=()=>done(true)})}
async function save(a,notify=false){const {error}=await sb.rpc('save_my_status',{p_energy:a.energy,p_capacity:a.capacity,p_closeness:a.closeness,p_desire:a.desire,p_stress:a.stress,p_needs:a.needs||[],p_notify:!!notify});if(error)throw error;try{await refreshContext();paint({resetScroll:false})}catch(e){console.warn('Flyt Oss refresh after save failed; keeping optimistic value',e);paint({resetScroll:false})}}
function rememberView(){const b=bridge(),s=b?.getState?.();if(s&&s.view!=='us')b.setState({...s,view:'us'})}
function paint({resetScroll=false}={}){const s=bridge()?.getState?.(),c=$('#content');if(!c||s?.view!=='us')return;const pos=resetScroll?0:c.scrollTop,a=mine();c.innerHTML=`<div class="ey">Oss · Dagsform</div><h1 class="title">Hvordan har du det?</h1><p class="sub">Del kapasitet og behov akkurat nå. Partneren kan se, men ikke endre statusen din.</p>${card('Energi','energy',a.energy)}${card('Overskudd','capacity',a.capacity)}${card('Nærhet','closeness',a.closeness)}${card('Sexlyst','desire',a.desire)}${card('Stress','stress',a.stress)}<div class="section"><strong>Hva trenger du akkurat nå?</strong><p class="sub">Velg gjerne flere.</p><div class="grid2" style="margin-top:8px">${NEEDS.map(([k,n])=>`<button type="button" class="need ${(a.needs||[]).includes(k)?'on':''}" data-oss-need="${k}">${n}</button>`).join('')}</div><button type="button" id="ossClear" class="secondary full" style="margin-top:10px">Ingen behov akkurat nå</button></div><div class="section"><div class="ey">Partnerens status</div>${partnerCard()}</div>`;document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('on',b.dataset.view==='us'));c.scrollTop=pos;requestAnimationFrame(()=>{c.scrollTop=pos})}
async function render({refresh=true,resetScroll=false}={}){if(rendering)return;rendering=true;const c=$('#content');if(!c){rendering=false;return}try{if(refresh||!ctx||!rows.length)await refreshContext();paint({resetScroll})}catch(e){console.error('Flyt Oss context failed',e);if(bridge()?.getState?.()?.view!=='us')return;const pos=resetScroll?0:c.scrollTop;c.innerHTML='<div class="ey">Oss</div><h1 class="title">Dagsform</h1><div class="card"><strong>Kunne ikke hente dagsform</strong><p class="sub">Prøv igjen om et øyeblikk.</p><button type="button" class="secondary full" id="ossRetry">Prøv igjen</button></div>';c.scrollTop=pos;$('#ossRetry')?.addEventListener('click',()=>render({refresh:true,resetScroll:false}),{once:true})}finally{rendering=false}}
document.addEventListener('click',async e=>{const nav=e.target.closest('#nav button[data-view="us"]');if(nav){e.preventDefault();e.stopImmediatePropagation();rememberView();await render({refresh:true,resetScroll:true});return}const l=e.target.closest('[data-oss-level]');if(l){e.preventDefault();e.stopImmediatePropagation();const before=mine(),key=l.dataset.ossLevel,val=l.dataset.ossValue;if(before[key]===val)return;const a={...before,needs:[...(before.needs||[])]};a[key]=val;const notify=await askNotify();setMine(a);l.parentElement?.querySelectorAll('[data-oss-level]').forEach(x=>x.classList.toggle('on',x===l));save(a,notify).catch(()=>{alert('Kunne ikke lagre dagsformen akkurat nå.');render({refresh:true,resetScroll:false})});return}const n=e.target.closest('[data-oss-need]');if(n){e.preventDefault();e.stopImmediatePropagation();const before=mine(),a={...before,needs:[...(before.needs||[])]},k=n.dataset.ossNeed,i=a.needs.indexOf(k);i>=0?a.needs.splice(i,1):a.needs.push(k);const notify=await askNotify();setMine(a);n.classList.toggle('on',a.needs.includes(k));save(a,notify).catch(()=>{alert('Kunne ikke lagre behovet akkurat nå.');render({refresh:true,resetScroll:false})});return}if(e.target.closest('#ossClear')){e.preventDefault();e.stopImmediatePropagation();const before=mine();if(!(before.needs||[]).length)return;const a={...before,needs:[]},notify=await askNotify();setMine(a);document.querySelectorAll('[data-oss-need]').forEach(x=>x.classList.remove('on'));save(a,notify).catch(()=>{alert('Kunne ikke lagre behovet akkurat nå.');render({refresh:true,resetScroll:false})})}},true);
window.FlytOss={render,paint,version:'20260825-2048'};
})();