(()=>{
'use strict';
if(!window.supabase)return;
const URL='https://uopzveejnztbovncqbpq.supabase.co';
const KEY='sb_publishable_uK6xd8TJhN2MY10qHSQ2GQ_7hSIr2gv';
const sb=window.supabase.createClient(URL,KEY);
const $=s=>document.querySelector(s);
const LEVELS=['low','med','high'];
const LABEL={low:'Lav',med:'Middels',high:'Høy'};
const NEEDS=[['relief','💛 Avlastning'],['closeness','💗 Nærhet'],['sex','🔥 Sex'],['initiative','⚡ Initiativ'],['alone','🌿 Alenetid'],['quiet','🌙 Ro']];
let ctx=null,rows=[];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function context(){const {data,error}=await sb.rpc('get_my_flyt_context');if(error)throw error;ctx=data;return data}
async function statuses(){const {data,error}=await sb.rpc('get_household_status');if(error)throw error;rows=Array.isArray(data)?data:[];return rows}
function mine(){return rows.find(x=>x.user_id===ctx?.user_id)||{energy:'med',capacity:'med',closeness:'med',desire:'med',stress:'med',needs:[]}}
function theirs(){return rows.find(x=>x.user_id!==ctx?.user_id)||null}
function partnerMember(){return ctx?.members?.find(x=>x.id!==ctx?.user_id)||null}
function age(ts){if(!ts)return 'Ikke oppdatert ennå';const m=Math.max(0,Math.round((Date.now()-new Date(ts).getTime())/60000));if(m<2)return 'Oppdatert nå';if(m<60)return `Oppdatert for ${m} min siden`;const h=Math.round(m/60);if(h<24)return `Oppdatert for ${h} t siden`;return `Oppdatert for ${Math.round(h/24)} d siden`}
function seg(k,v){return `<div class="segments">${LEVELS.map(x=>`<button data-oss-level="${k}" data-oss-value="${x}" class="${v===x?'on':''}">${LABEL[x]}</button>`).join('')}</div>`}
function card(name,key,val){return `<div class="card"><strong>${name}</strong>${seg(key,val)}</div>`}
function partnerCard(){const member=partnerMember(),p=theirs();if(!member)return '<div class="card"><p class="sub">Partneren er ikke koblet til ennå.</p></div>';if(!p)return `<div class="card"><strong>${esc(member.display_name||'Partner')}</strong><p class="sub">Har ikke delt dagsform ennå.</p></div>`;const stats=[['Energi',p.energy],['Overskudd',p.capacity],['Nærhet',p.closeness],['Sexlyst',p.desire],['Stress',p.stress]].map(([n,v])=>`<div class="row" style="padding:5px 0"><span class="grow">${n}</span><span class="tag">${LABEL[v]||'Middels'}</span></div>`).join('');const needs=(p.needs||[]).map(k=>NEEDS.find(x=>x[0]===k)?.[1]).filter(Boolean);return `<div class="card hero"><strong>${esc(member.display_name||'Partner')} akkurat nå</strong><div class="taskmeta">${age(p.updated_at)}</div><div style="margin-top:8px">${stats}</div><div class="taskmeta" style="margin-top:11px">Behov</div>${needs.length?`<div style="display:flex;flex-wrap:wrap;gap:7px;margin-top:7px">${needs.map(n=>`<span class="tag">${n}</span>`).join('')}</div>`:'<p class="sub">Ingen behov markert akkurat nå.</p>'}</div>`}
async function render(){const c=$('#content');if(!c)return;try{await context();await statuses()}catch(e){c.innerHTML='<div class="ey">Oss</div><h1 class="title">Dagsform</h1><div class="card"><strong>Kunne ikke hente dagsform</strong><p class="sub">Prøv igjen om et øyeblikk.</p></div>';return}const a=mine();c.innerHTML=`<div class="ey">Oss · Dagsform</div><h1 class="title">Hvordan har du det?</h1><p class="sub">Del kapasitet og behov akkurat nå. Partneren kan se, men ikke endre statusen din.</p>${card('Energi','energy',a.energy)}${card('Overskudd','capacity',a.capacity)}${card('Nærhet','closeness',a.closeness)}${card('Sexlyst','desire',a.desire)}${card('Stress','stress',a.stress)}<div class="section"><strong>Hva trenger du akkurat nå?</strong><p class="sub">Velg gjerne flere.</p><div class="grid2" style="margin-top:8px">${NEEDS.map(([k,n])=>`<button class="need ${(a.needs||[]).includes(k)?'on':''}" data-oss-need="${k}">${n}</button>`).join('')}</div><button id="ossClear" class="secondary full" style="margin-top:10px">Ingen behov akkurat nå</button></div><div class="section"><div class="ey">Partnerens status</div>${partnerCard()}</div>`;document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('on',b.dataset.view==='us'));c.scrollTop=0}
async function save(a){const {error}=await sb.rpc('save_my_status',{p_energy:a.energy,p_capacity:a.capacity,p_closeness:a.closeness,p_desire:a.desire,p_stress:a.stress,p_needs:a.needs||[]});if(error)throw error}
document.addEventListener('click',async e=>{const nav=e.target.closest('#nav button[data-view="us"]');if(nav){e.preventDefault();e.stopImmediatePropagation();await render();return}const l=e.target.closest('[data-oss-level]');if(l){e.preventDefault();e.stopImmediatePropagation();const a={...mine(),needs:[...(mine().needs||[])]};a[l.dataset.ossLevel]=l.dataset.ossValue;try{await save(a);await render()}catch(err){alert('Kunne ikke lagre dagsformen akkurat nå.')}return}const n=e.target.closest('[data-oss-need]');if(n){e.preventDefault();e.stopImmediatePropagation();const a={...mine(),needs:[...(mine().needs||[])]},k=n.dataset.ossNeed,i=a.needs.indexOf(k);i>=0?a.needs.splice(i,1):a.needs.push(k);try{await save(a);await render()}catch(err){alert('Kunne ikke lagre behovet akkurat nå.')}return}if(e.target.closest('#ossClear')){e.preventDefault();e.stopImmediatePropagation();const a={...mine(),needs:[]};try{await save(a);await render()}catch(err){alert('Kunne ikke lagre behovet akkurat nå.')}}},true);
window.FlytOss={render};
})();