(()=>{
'use strict';

const VERSION='20260901-1200';
const $=selector=>document.querySelector(selector);
const bridge=()=>window.FlytBridge;
const LEVELS=['low','med','high'];
const LABEL={low:'Lav',med:'Middels',high:'Høy'};
const NEEDS=[['relief','💛 Avlastning'],['closeness','💗 Nærhet'],['sex','❤️‍🔥 Intimitet'],['initiative','⚡ Initiativ'],['alone','🌿 Alenetid'],['quiet','🌙 Ro']];
let ctx=null,rows=[],rendering=false,mode='week';

const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
async function rpc(name,args){const fn=window.FlytSync?.rpc;if(!fn)throw new Error('Flyt-synkronisering er ikke klar');return await fn(name,args)}
async function fastContext(){const {data,error}=await rpc('get_oss_context');if(error)throw error;ctx={user_id:data?.user_id,members:Array.isArray(data?.members)?data.members:[]};rows=Array.isArray(data?.statuses)?data.statuses:[];return data}
async function legacyContext(){const account=await rpc('get_my_flyt_context');if(account.error)throw account.error;const status=await rpc('get_household_status');if(status.error)throw status.error;ctx={user_id:account.data?.user_id,members:Array.isArray(account.data?.members)?account.data.members:[]};rows=Array.isArray(status.data)?status.data:[];return{user_id:ctx.user_id,members:ctx.members,statuses:rows}}
async function refreshContext(){try{return await fastContext()}catch(error){console.warn('Flyt Oss fast context failed, using fallback',error);return await legacyContext()}}
function fallback(){return{user_id:ctx?.user_id,energy:'med',capacity:'med',closeness:'med',desire:'med',stress:'med',needs:[],updated_at:null}}
function mine(){return rows.find(item=>String(item.user_id)===String(ctx?.user_id))||fallback()}
function theirs(){return rows.find(item=>String(item.user_id)!==String(ctx?.user_id))||null}
function setMine(value){const row={...value,user_id:ctx?.user_id,updated_at:new Date().toISOString()},index=rows.findIndex(item=>String(item.user_id)===String(ctx?.user_id));if(index>=0)rows[index]=row;else rows.push(row);return row}
function partnerMember(){return ctx?.members?.find(item=>String(item.id)!==String(ctx?.user_id))||null}
function age(value){if(!value)return'Ikke oppdatert ennå';const minutes=Math.max(0,Math.round((Date.now()-new Date(value).getTime())/60000));if(minutes<2)return'Oppdatert nå';if(minutes<60)return`Oppdatert for ${minutes} min siden`;const hours=Math.round(minutes/60);if(hours<24)return`Oppdatert for ${hours} t siden`;return`Oppdatert for ${Math.round(hours/24)} d siden`}
function segment(key,value){return `<div class="segments">${LEVELS.map(level=>`<button type="button" data-oss-level="${key}" data-oss-value="${level}" class="${value===level?'on':''}">${LABEL[level]}</button>`).join('')}</div>`}
function statusCard(name,key,value){return `<div class="card"><strong>${name}</strong>${segment(key,value)}</div>`}
function partnerCard(){const member=partnerMember(),status=theirs();if(!member)return'<div class="card"><p class="sub">Partneren er ikke koblet til ennå.</p></div>';if(!status)return`<div class="card"><strong>${esc(member.display_name||'Partner')}</strong><p class="sub">Har ikke delt dagsform ennå.</p></div>`;const stats=[['Energi',status.energy],['Overskudd',status.capacity],['Nærhet',status.closeness],['Lyst',status.desire],['Stress',status.stress]].map(([name,value])=>`<div class="row" style="padding:5px 0"><span class="grow">${name}</span><span class="tag">${LABEL[value]||'Middels'}</span></div>`).join(''),needs=(status.needs||[]).map(key=>NEEDS.find(item=>item[0]===key)?.[1]).filter(Boolean);return `<div class="card hero"><strong>${esc(member.display_name||'Partner')} akkurat nå</strong><div class="taskmeta">${age(status.updated_at)}</div><div style="margin-top:8px">${stats}</div><div class="taskmeta" style="margin-top:11px">Behov</div>${needs.length?`<div style="display:flex;flex-wrap:wrap;gap:7px;margin-top:7px">${needs.map(name=>`<span class="tag">${name}</span>`).join('')}</div>`:'<p class="sub">Ingen behov markert akkurat nå.</p>'}</div>`}
function mirrorLead(mirror){if(mirror.sharedMoments>0)return`${mirror.sharedMoments} små øyeblikk landet mellom dere`;if(mirror.chores>0)return'Dere har fått hverdagen i bevegelse';return'Denne uken begynner her'}
function metric(value,label,detail){return `<div style="padding:12px 10px;border:1px solid var(--line);border-radius:16px;background:#fff"><b style="display:block;font-size:24px">${value}</b><strong style="display:block;font-size:12px;margin-top:2px">${label}</strong><span class="taskmeta" style="display:block;margin-top:4px">${detail}</span></div>`}
function weekMarkup(state){
  const mirror=window.FlytCoupleInsights?.weeklyMirror?.(state)||{chores:0,asked:0,answered:0,completed:0,initiativeStarted:0,initiativeCompleted:0,thanks:0,invitationsSent:0,invitationsAnswered:0,invitationsAccepted:0,sharedMoments:0};
  return `<div class="ey">Oss · Ukespeil</div><h1 class="title">Sammen denne uken</h1><p class="sub">Ikke en karakter på forholdet. Bare et rolig speil av det dere faktisk har delt, svart på og fått til.</p><section class="card" style="border-color:#e1ddc9;background:linear-gradient(145deg,#fffdf8,#f1f3e8)"><div class="ey" style="color:#607644">Ukespeilet</div><strong style="display:block;font:600 25px/1.15 Georgia;margin-top:7px">${esc(mirrorLead(mirror))}</strong><p class="sub" style="margin-bottom:0">Flyt teller samspill, ikke bare avkryssede gjøremål.</p></section><div style="display:grid;grid-template-columns:1fr 1fr;gap:9px;margin:12px 0">${metric(mirror.chores,'Gjøremål gjort','Det praktiske')}${metric(mirror.answered,'Forespørsler besvart',`${mirror.asked} sendt`)}${metric(mirror.initiativeCompleted,'Initiativ fullført',`${mirror.initiativeStarted} startet`)}${metric(mirror.invitationsAnswered,'Invitasjoner besvart',`${mirror.invitationsSent} sendt`)}</div><section class="card" style="box-shadow:none"><div class="ey">Samspillsløkken</div><h2 style="font:500 22px/1.2 Georgia;margin:6px 0 12px">Fra behov til noe som faktisk skjer</h2><div style="display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:6px;text-align:center"><div><b style="font-size:20px">${mirror.asked}</b><div class="taskmeta">Spurt</div></div><div><b style="font-size:20px">${mirror.answered}</b><div class="taskmeta">Svar</div></div><div><b style="font-size:20px">${mirror.completed}</b><div class="taskmeta">Gjort</div></div><div><b style="font-size:20px">${mirror.thanks}</b><div class="taskmeta">Takk</div></div></div><div style="height:7px;border-radius:999px;background:linear-gradient(90deg,#f6cdbd,#e9aa87,#dfe8d1,#f1d8de);margin-top:13px"></div><p class="sub" style="font-size:13px;margin-bottom:0">Tallene er til refleksjon, ikke konkurranse. Null kan bety at uken nettopp har begynt – eller at dere snakket utenfor Flyt.</p></section><div id="ossInvitationMount" aria-live="polite"></div>`;
}
function statusMarkup(){const status=mine();return `<div class="ey">Oss · Dagsform</div><h1 class="title">Hvordan har du det?</h1><p class="sub">Del kapasitet og behov akkurat nå. Partneren kan se, men ikke endre statusen din.</p>${statusCard('Energi','energy',status.energy)}${statusCard('Overskudd','capacity',status.capacity)}${statusCard('Nærhet','closeness',status.closeness)}${statusCard('Lyst','desire',status.desire)}${statusCard('Stress','stress',status.stress)}<div class="section"><strong>Hva trenger du akkurat nå?</strong><p class="sub">Velg gjerne flere.</p><div class="grid2" style="margin-top:8px">${NEEDS.map(([key,name])=>`<button type="button" class="need ${(status.needs||[]).includes(key)?'on':''}" data-oss-need="${key}">${name}</button>`).join('')}</div><button type="button" id="ossClear" class="secondary full" style="margin-top:10px">Ingen behov akkurat nå</button></div><div class="section"><div class="ey">Partnerens status</div>${partnerCard()}</div>`}
function viewTabs(){return `<div class="segments" style="grid-template-columns:1fr 1fr;margin:0 0 18px"><button type="button" data-oss-view="week" class="${mode==='week'?'on':''}">Ukespeil</button><button type="button" data-oss-view="status" class="${mode==='status'?'on':''}">Dagsform</button></div>`}
function askNotify(){const partner=partnerMember();if(!partner)return Promise.resolve(false);return new Promise(resolve=>{document.querySelector('#ossNotifyModal')?.remove();const element=document.createElement('div');element.id='ossNotifyModal';element.style.cssText='position:fixed;inset:0;z-index:300;background:#3a211b88;display:flex;align-items:center;justify-content:center;padding:22px';element.innerHTML=`<div role="dialog" aria-modal="true" style="width:min(370px,100%);background:#fffaf7;border:1px solid #ead8d0;border-radius:24px;padding:22px;box-shadow:0 24px 70px #3b211b55"><div class="ey">Dagsform</div><h2 style="font:500 27px/1.15 Georgia;margin:8px 0 8px">Varsle ${esc(partner.display_name||'partneren')}?</h2><p class="sub" style="margin-top:0">Send et lite heads-up om at dagsformen eller behovene dine har endret seg.</p><div style="display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:18px"><button type="button" id="ossNotifyNo" class="secondary">Bare oppdater</button><button type="button" id="ossNotifyYes" class="primary">Oppdater og varsle</button></div></div>`;const done=value=>{element.remove();resolve(value)};element.addEventListener('click',event=>{if(event.target===element)done(false)});document.body.appendChild(element);element.querySelector('#ossNotifyNo').onclick=()=>done(false);element.querySelector('#ossNotifyYes').onclick=()=>done(true)})}
async function saveStatus(status,notify=false){const {error}=await rpc('save_my_status',{p_energy:status.energy,p_capacity:status.capacity,p_closeness:status.closeness,p_desire:status.desire,p_stress:status.stress,p_needs:status.needs||[],p_notify:!!notify});if(error)throw error;try{await refreshContext();paint({resetScroll:false})}catch(error){console.warn('Flyt Oss refresh after save failed; keeping optimistic value',error);paint({resetScroll:false})}}
function rememberView(){const app=bridge(),state=app?.getState?.();if(state&&state.view!=='us')app.setState({...state,view:'us'})}
function paint({resetScroll=false}={}){const state=bridge()?.getState?.(),content=$('#content');if(!content||state?.view!=='us')return;const position=resetScroll?0:content.scrollTop;content.dataset.flytOwner='oss-ui';content.innerHTML=`${viewTabs()}${mode==='week'?weekMarkup(state):statusMarkup()}`;document.querySelectorAll('#nav button').forEach(button=>button.classList.toggle('on',button.dataset.view==='us'));content.scrollTop=position;requestAnimationFrame(()=>{content.scrollTop=position});if(mode==='week')queueMicrotask(()=>window.FlytCoupleInvitations?.augment?.())}
async function render({refresh=true,resetScroll=false}={}){if(rendering)return;rendering=true;const content=$('#content');if(!content){rendering=false;return}try{if(refresh||!ctx||!rows.length)await refreshContext();paint({resetScroll})}catch(error){console.error('Flyt Oss context failed',error);if(bridge()?.getState?.()?.view!=='us')return;const position=resetScroll?0:content.scrollTop;content.innerHTML='<div class="ey">Oss</div><h1 class="title">Ukespeil og dagsform</h1><div class="card"><strong>Kunne ikke hente Oss akkurat nå</strong><p class="sub">Prøv igjen om et øyeblikk.</p><button type="button" class="secondary full" id="ossRetry">Prøv igjen</button></div>';content.scrollTop=position;$('#ossRetry')?.addEventListener('click',()=>render({refresh:true,resetScroll:false}),{once:true})}finally{rendering=false}}

document.addEventListener('click',async event=>{
  const nav=event.target.closest('#nav button[data-view="us"]');
  if(nav){event.preventDefault();event.stopImmediatePropagation();rememberView();await render({refresh:true,resetScroll:true});return}
  const tab=event.target.closest('[data-oss-view]');
  if(tab&&bridge()?.getState?.()?.view==='us'){event.preventDefault();event.stopImmediatePropagation();mode=tab.dataset.ossView==='status'?'status':'week';paint({resetScroll:true});return}
  const level=event.target.closest('[data-oss-level]');
  if(level){event.preventDefault();event.stopImmediatePropagation();const before=mine(),key=level.dataset.ossLevel,value=level.dataset.ossValue;if(before[key]===value)return;const status={...before,needs:[...(before.needs||[])]};status[key]=value;const notify=await askNotify();setMine(status);level.parentElement?.querySelectorAll('[data-oss-level]').forEach(button=>button.classList.toggle('on',button===level));saveStatus(status,notify).catch(()=>{alert('Kunne ikke lagre dagsformen akkurat nå.');render({refresh:true,resetScroll:false})});return}
  const need=event.target.closest('[data-oss-need]');
  if(need){event.preventDefault();event.stopImmediatePropagation();const before=mine(),status={...before,needs:[...(before.needs||[])]},key=need.dataset.ossNeed,index=status.needs.indexOf(key);index>=0?status.needs.splice(index,1):status.needs.push(key);const notify=await askNotify();setMine(status);need.classList.toggle('on',status.needs.includes(key));saveStatus(status,notify).catch(()=>{alert('Kunne ikke lagre behovet akkurat nå.');render({refresh:true,resetScroll:false})});return}
  if(event.target.closest('#ossClear')){event.preventDefault();event.stopImmediatePropagation();const before=mine();if(!(before.needs||[]).length)return;const status={...before,needs:[]},notify=await askNotify();setMine(status);document.querySelectorAll('[data-oss-need]').forEach(button=>button.classList.remove('on'));saveStatus(status,notify).catch(()=>{alert('Kunne ikke lagre behovet akkurat nå.');render({refresh:true,resetScroll:false})})}
},true);

window.FlytOss={render,paint,version:VERSION};
})();
