(()=>{
'use strict';
const $=s=>document.querySelector(s);
const bridge=()=>window.FlytBridge;
let installed=false;
const state=()=>bridge()?.getState?.()||null;
const save=s=>{bridge()?.setState?.(s);window.FlytSync?.queueSave?.()};
function localDate(d=new Date()){const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`}
function plusDays(ds,n){const d=new Date(ds+'T12:00:00');d.setDate(d.getDate()+n);return localDate(d)}
function list(s){return Array.isArray(s?.plannedTasks)?s.plannedTasks:[]}
function owners(){const ctx=window.FlytSync?.getContext?.(),names=Array.isArray(ctx?.members)?ctx.members.map(m=>m.display_name).filter(Boolean):[];return [...new Set(['Begge',...names,'Ingen fast'])]}
function mode(){const on=document.querySelector('[data-task-mode].on');return on?.dataset.taskMode==='week'?'week':'day'}
function visible(s){const m=mode(),all=list(s);if(m==='day')return all.filter(x=>x.date===localDate()).sort((a,b)=>Number(a.createdAt||0)-Number(b.createdAt||0));const start=localDate(),end=plusDays(start,13);return all.filter(x=>x.date>=start&&x.date<=end).sort((a,b)=>a.date.localeCompare(b.date)||Number(a.createdAt||0)-Number(b.createdAt||0))}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function card(s,x){const when=new Date(x.date+'T12:00:00').toLocaleDateString('nb-NO',{weekday:'short',day:'numeric',month:'short'}),mine=x.doneBy===s.user,doneBy=x.done&&x.doneBy?` · Gjort av ${esc(x.doneBy)}`:'';return `<div class="card"><div class="row"><div class="grow"><strong>${esc(x.title)}</strong><div class="taskmeta">${when}${x.owner?' · '+esc(x.owner):''}${doneBy}${x.reminder&&x.reminder!=='none'?' · '+(x.reminder==='dayBefore'?'Påminnelse dagen før':'Påminnelse samme dag'):''} · ${Number(x.points||0)} ekstrapoeng</div></div>${x.done?'<span class="tag">Ekstra ✓</span>':''}</div><div class="row" style="margin-top:10px">${!x.done?`<button type="button" class="small" data-planned-done="${x.id}">+ Gjort</button>`:mine?`<button type="button" class="small" data-planned-undo="${x.id}">− Angre</button>`:''}<button type="button" class="small" data-planned-delete="${x.id}">Slett</button></div></div>`}
function section(s){const items=visible(s),label=mode()==='day'?'Ekstraoppgaver i dag':'Kommende ekstraoppgaver';return `<div class="section" id="plannedSection"><div class="ey">${label}</div><p class="sub"><strong>Ekstraoppgaver</strong> er enkeltstående ting utenfor rutinene. Ekstrapoeng vises separat og påvirker ikke faste mål eller 700 %-flyten.</p>${items.length?items.map(x=>card(s,x)).join(''):'<div class="card"><span class="sub">Ingen ekstraoppgaver planlagt her.</span></div>'}<button type="button" id="openPlannedForm" class="secondary full">+ Planlegg ekstraoppgave</button><div id="plannedForm" class="card hidden"><strong>Ny ekstraoppgave</strong><label><span class="label">Hva skal gjøres?</span><input id="plannedTitle" class="field" placeholder="F.eks. tannlege med barn"></label><label><span class="label">Dato</span><input id="plannedDate" class="field" type="date" value="${localDate()}"></label><label><span class="label">Ansvarlig</span><select id="plannedOwner" class="field">${owners().map(o=>`<option>${esc(o)}</option>`).join('')}</select></label><label><span class="label">Påminnelse</span><select id="plannedReminder" class="field"><option value="none">Ingen</option><option value="dayBefore">Dagen før</option><option value="sameDay">Samme dag</option></select></label><label><span class="label">Ekstrapoeng</span><input id="plannedPoints" class="field" type="number" min="0" value="30"></label><button type="button" id="savePlannedTask" class="primary full">Legg til</button><button type="button" id="cancelPlannedForm" class="secondary full" style="margin-top:8px">Avbryt</button></div></div>`}
function paint(){const s=state(),c=$('#content');if(!s||!c||s.view!=='tasks')return;$('#plannedSection')?.remove();const edit=c.querySelector('[data-open-new-setup],[data-open-setup]');const wrap=document.createElement('div');wrap.innerHTML=section(s);const node=wrap.firstElementChild;if(edit)edit.before(node);else c.appendChild(node)}
function hook(){if(installed||!window.FlytTasksUI?.render)return;installed=true;const original=window.FlytTasksUI.render.bind(window.FlytTasksUI);window.FlytTasksUI.render=(opts)=>{original(opts);queueMicrotask(paint)};paint()}
function rerender(){window.FlytTasksUI?.render?.({resetScroll:false});queueMicrotask(paint)}
document.addEventListener('click',e=>{
 const open=e.target.closest('#openPlannedForm');if(open){e.preventDefault();e.stopImmediatePropagation();$('#plannedForm')?.classList.remove('hidden');return}
 const cancel=e.target.closest('#cancelPlannedForm');if(cancel){e.preventDefault();e.stopImmediatePropagation();$('#plannedForm')?.classList.add('hidden');return}
 const add=e.target.closest('#savePlannedTask');if(add){e.preventDefault();e.stopImmediatePropagation();const s=state(),title=$('#plannedTitle')?.value.trim(),date=$('#plannedDate')?.value;if(!s||!title||!date){bridge()?.toast?.('Legg inn oppgave og dato');return}const x={id:'planned_'+Date.now(),title,date,owner:$('#plannedOwner')?.value||'Begge',reminder:$('#plannedReminder')?.value||'none',points:Math.max(0,Number($('#plannedPoints')?.value)||0),createdAt:Date.now(),done:false,doneBy:null,doneAt:null};save({...s,plannedTasks:[...list(s),x]});rerender();bridge()?.toast?.('Ekstraoppgaven er planlagt');return}
 const done=e.target.closest('[data-planned-done]');if(done){e.preventDefault();e.stopImmediatePropagation();const s=state(),items=list(s).map(x=>({...x})),x=items.find(x=>x.id===done.dataset.plannedDone);if(!s||!x||x.done)return;x.done=true;x.doneBy=s.user;x.doneAt=new Date().toISOString();const points={...(s.points||{})};points[s.user]=(points[s.user]||0)+Number(x.points||0);save({...s,plannedTasks:items,points});rerender();bridge()?.toast?.(`Ekstraoppgave registrert · +${x.points||0} ekstrapoeng`);return}
 const undo=e.target.closest('[data-planned-undo]');if(undo){e.preventDefault();e.stopImmediatePropagation();const s=state(),items=list(s).map(x=>({...x})),x=items.find(x=>x.id===undo.dataset.plannedUndo);if(!s||!x||!x.done||x.doneBy!==s.user)return;const points={...(s.points||{})};points[s.user]=Math.max(0,(points[s.user]||0)-Number(x.points||0));x.done=false;x.doneBy=null;x.doneAt=null;save({...s,plannedTasks:items,points});rerender();return}
 const del=e.target.closest('[data-planned-delete]');if(del){e.preventDefault();e.stopImmediatePropagation();const s=state(),x=list(s).find(x=>x.id===del.dataset.plannedDelete);if(!s||!x)return;if(x.done){bridge()?.toast?.('Angre registreringen før du sletter');return}if(confirm('Slette denne ekstraoppgaven?')){save({...s,plannedTasks:list(s).filter(x=>x.id!==del.dataset.plannedDelete)});rerender()}return}
 const nav=e.target.closest('#nav button[data-view="tasks"],[data-task-mode]');if(nav)setTimeout(()=>{hook();paint()},0)
},true);
let tries=0;const timer=setInterval(()=>{hook();if(installed||++tries>40)clearInterval(timer)},100);
window.FlytPlannedUI={paint,version:'20260824-0956'};
})();