(()=>{
'use strict';
const $=s=>document.querySelector(s);
const bridge=()=>window.FlytBridge;
let installed=false,formOpen=false;
const state=()=>bridge()?.getState?.()||null;
const save=s=>{bridge()?.setState?.(s);window.FlytSync?.queueSave?.()};
function localDate(d=new Date()){const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`}
function plusDays(ds,n){const d=new Date(ds+'T12:00:00');d.setDate(d.getDate()+n);return localDate(d)}
function list(s){return Array.isArray(s?.plannedTasks)?s.plannedTasks:[]}
function owners(){const ctx=window.FlytSync?.getContext?.(),names=Array.isArray(ctx?.members)?ctx.members.map(m=>m.display_name).filter(Boolean):[];return [...new Set(['Begge',...names,'Ingen fast'])]}
function mode(){return window.FlytRecurrenceUI?.getMode?.()||'day'}
function visible(s){const m=mode(),all=list(s);if(m==='day')return all.filter(x=>x.date===localDate()).sort((a,b)=>Number(a.createdAt||0)-Number(b.createdAt||0));if(m==='week'){const start=localDate(),end=plusDays(start,13);return all.filter(x=>x.date>=start&&x.date<=end).sort((a,b)=>a.date.localeCompare(b.date)||Number(a.createdAt||0)-Number(b.createdAt||0))}const ym=localDate().slice(0,7);return all.filter(x=>String(x.date||'').startsWith(ym)).sort((a,b)=>a.date.localeCompare(b.date)||Number(a.createdAt||0)-Number(b.createdAt||0))}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function card(s,x){const when=new Date(x.date+'T12:00:00').toLocaleDateString('nb-NO',{weekday:'short',day:'numeric',month:'short'}),mine=x.doneBy===s.user,doneBy=x.done&&x.doneBy?` · Gjort av ${esc(x.doneBy)}`:'';return `<div class="card"><div class="row"><div class="grow"><strong>${esc(x.title)}</strong><div class="taskmeta">${when}${x.owner?' · '+esc(x.owner):''}${doneBy}${x.reminder&&x.reminder!=='none'?' · '+(x.reminder==='dayBefore'?'Påminnelse dagen før':'Påminnelse samme dag'):''} · ${Number(x.points||0)} ekstrapoeng</div></div>${x.done?'<span class="tag">Ekstra ✓</span>':''}</div><div class="row" style="margin-top:10px">${!x.done?`<button type="button" class="small" data-planned-done="${x.id}">+ Gjort</button>`:mine?`<button type="button" class="small" data-planned-undo="${x.id}">− Angre</button>`:''}<button type="button" class="small" data-planned-delete="${x.id}">Slett</button></div></div>`}
function section(s){const items=visible(s),m=mode(),label=m==='day'?'Ekstraoppgaver i dag':m==='week'?'Ekstraoppgaver denne perioden':'Ekstraoppgaver denne måneden';return `<div class="section" id="plannedSection"><div class="ey">${label}</div><p class="sub"><strong>Ekstraoppgaver</strong> er enkeltstående ting utenfor rutinene. Ekstrapoeng vises separat og påvirker ikke faste mål.</p>${items.length?items.map(x=>card(s,x)).join(''):'<div class="card"><span class="sub">Ingen ekstraoppgaver planlagt her.</span></div>'}<button type="button" id="openPlannedForm" class="secondary full">+ Planlegg ekstraoppgave</button></div>`}
function paint(){const s=state(),c=$('#content');if(!s||!c||s.view!=='tasks')return;const pos=c.scrollTop,maxBefore=Math.max(0,c.scrollHeight-c.clientHeight),atBottom=maxBefore-pos<28,old=$('#plannedSection'),edit=c.querySelector('[data-open-new-setup],[data-open-setup]'),wrap=document.createElement('div');wrap.innerHTML=section(s);const node=wrap.firstElementChild;if(old)old.replaceWith(node);else if(edit)edit.before(node);else c.appendChild(node);const restore=()=>{const max=Math.max(0,c.scrollHeight-c.clientHeight);c.scrollTop=atBottom?max:Math.min(pos,max)};restore();requestAnimationFrame(restore)}
function closeForm(){formOpen=false;$('#plannedModal')?.remove()}
function openForm(){if(formOpen)return;formOpen=true;const el=document.createElement('div');el.id='plannedModal';el.style.cssText='position:fixed;inset:0;z-index:155;background:#3a211b88;display:flex;align-items:center;justify-content:center;padding:22px';el.innerHTML=`<div role="dialog" aria-modal="true" style="width:min(390px,100%);max-height:88dvh;overflow:auto;background:#fffaf7;border:1px solid #ead8d0;border-radius:26px;padding:22px;box-shadow:0 24px 70px #3b211b55"><div class="ey">Ekstraoppgave</div><h2 style="font:500 28px/1.12 Georgia;margin:10px 0 16px">Planlegg ekstraoppgave</h2><label><span class="label">Hva skal gjøres?</span><input id="plannedTitle" class="field" autocomplete="off" placeholder="F.eks. tannlege med barn"></label><label><span class="label">Dato</span><input id="plannedDate" class="field" type="date" value="${localDate()}"></label><label><span class="label">Ansvarlig</span><select id="plannedOwner" class="field">${owners().map(o=>`<option>${esc(o)}</option>`).join('')}</select></label><label><span class="label">Påminnelse</span><select id="plannedReminder" class="field"><option value="none">Ingen</option><option value="dayBefore">Dagen før</option><option value="sameDay">Samme dag</option></select></label><label><span class="label">Ekstrapoeng</span><input id="plannedPoints" class="field" type="number" min="0" value="30"></label><div style="display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:18px"><button type="button" id="cancelPlannedForm" class="secondary">Avbryt</button><button type="button" id="savePlannedTask" class="primary">Legg til</button></div></div>`;el.addEventListener('click',e=>{if(e.target===el)closeForm()});document.body.appendChild(el);setTimeout(()=>$('#plannedTitle')?.focus(),30)}
function hook(){if(installed)return;installed=true;paint()}
function rerender(){window.FlytRecurrenceUI?.render?.({resetScroll:false})||window.FlytTasksUI?.render?.({resetScroll:false});setTimeout(paint,0)}
document.addEventListener('click',async e=>{
 const open=e.target.closest('#openPlannedForm');if(open){e.preventDefault();e.stopImmediatePropagation();openForm();return}
 const cancel=e.target.closest('#cancelPlannedForm');if(cancel){e.preventDefault();e.stopImmediatePropagation();closeForm();return}
 const add=e.target.closest('#savePlannedTask');if(add){e.preventDefault();e.stopImmediatePropagation();const s=state(),title=$('#plannedTitle')?.value.trim(),date=$('#plannedDate')?.value;if(!s||!title||!date){bridge()?.toast?.('Legg inn oppgave og dato');return}const x={id:'planned_'+Date.now(),title,date,owner:$('#plannedOwner')?.value||'Begge',reminder:$('#plannedReminder')?.value||'none',points:Math.max(0,Number($('#plannedPoints')?.value)||0),createdAt:Date.now(),done:false,doneBy:null,doneAt:null};save({...s,plannedTasks:[...list(s),x]});closeForm();rerender();bridge()?.toast?.('Ekstraoppgaven er planlagt');return}
 const done=e.target.closest('[data-planned-done]');if(done){e.preventDefault();e.stopImmediatePropagation();const s=state(),items=list(s).map(x=>({...x})),x=items.find(x=>String(x.id)===String(done.dataset.plannedDone));if(!s||!x||x.done)return;x.done=true;x.doneBy=s.user;x.doneAt=new Date().toISOString();const points={...(s.points||{})};points[s.user]=(points[s.user]||0)+Number(x.points||0);save({...s,plannedTasks:items,points});rerender();bridge()?.toast?.(`Ekstraoppgave registrert · +${x.points||0} ekstrapoeng`);return}
 const undo=e.target.closest('[data-planned-undo]');if(undo){e.preventDefault();e.stopImmediatePropagation();const s=state(),items=list(s).map(x=>({...x})),x=items.find(x=>String(x.id)===String(undo.dataset.plannedUndo));if(!s||!x||!x.done||x.doneBy!==s.user)return;const points={...(s.points||{})};points[s.user]=Math.max(0,(points[s.user]||0)-Number(x.points||0));x.done=false;x.doneBy=null;x.doneAt=null;save({...s,plannedTasks:items,points});rerender();return}
 const del=e.target.closest('[data-planned-delete]');if(del){e.preventDefault();e.stopImmediatePropagation();const s=state(),x=list(s).find(x=>String(x.id)===String(del.dataset.plannedDelete));if(!s||!x)return;if(x.done){bridge()?.toast?.('Angre registreringen før du sletter');return}const yes=window.FlytModal?await window.FlytModal.confirm({ey:'Ekstraoppgave',title:'Slette ekstraoppgaven?',text:'Oppgaven fjernes fra planen.',ok:'Slett'}):false;if(yes){save({...s,plannedTasks:list(s).filter(x=>String(x.id)!==String(del.dataset.plannedDelete))});rerender()}return}
},true);
let tries=0;const timer=setInterval(()=>{if(window.FlytTasksUI?.render){hook();clearInterval(timer)}else if(++tries>80)clearInterval(timer)},100);
window.FlytPlannedUI={paint,openForm,closeForm,version:'20260824-1457'};
})();