(()=>{
'use strict';
const $=s=>document.querySelector(s);
const bridge=()=>window.FlytBridge;
const ORDER=['Barn','Kjøkken','Vask & klær','Stue','Bad','Soverom','Dyr','Hage & ute','Bil','Innkjøp','Vedlikehold','Planlegging & admin','Personlig investering','Egendefinert'];
const OSLO_TIME_ZONE='Europe/Oslo';
let mode='day',installed=false,painting=false;
function state(){return bridge()?.getState?.()||null}
function save(next){bridge()?.setState?.(next);window.FlytSync?.queueSave?.()}
function localDate(d=new Date()){const parts=Object.fromEntries(new Intl.DateTimeFormat('nb-NO',{timeZone:OSLO_TIME_ZONE,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(d).filter(x=>x.type!=='literal').map(x=>[x.type,x.value]));return `${parts.year}-${parts.month}-${parts.day}`}
function dayName(d=new Date()){return new Intl.DateTimeFormat('nb-NO',{timeZone:OSLO_TIME_ZONE,weekday:'long'}).format(d).replace(/^./,c=>c.toUpperCase())}
function addDays(key,n){const [y,m,d]=String(key).split('-').map(Number),next=new Date(Date.UTC(y,m-1,d+n));return next.toISOString().slice(0,10)}
function weekRange(at=new Date()){const key=localDate(at),[y,m,d]=key.split('-').map(Number),weekday=new Date(Date.UTC(y,m-1,d)).getUTCDay(),start=addDays(key,-((weekday+6)%7));return{start,end:addDays(start,6)}}
function validDateKey(value){return /^\d{4}-\d{2}-\d{2}$/.test(String(value||''))}
function period(t){return t?.type==='daily'?'day':t?.type==='period'?'month':'week'}
function category(t){const raw=(t.cat||'').trim();if(raw==='Husdyr')return'Dyr';if(raw==='Utearbeid')return'Hage & ute';if(raw==='Periodisk vedlikehold')return'Vedlikehold';if(raw==='Usynlig arbeid')return'Planlegging & admin';if(raw==='Hus'){if(['living','hallway'].includes(t.id))return'Stue';if(t.id==='bed')return'Soverom';if(['laundry','vacuum'].includes(t.id))return'Vask & klær';if(t.id==='trash')return'Vedlikehold'}return raw||'Hus'}
function relevant(s,t){return s.categoryRelevant?.[category(t)]!==false}
function comps(s,t,which=mode,at=new Date()){const all=(s.completions||[]).filter(c=>String(c.taskId)===String(t.id));if(which==='day')return all.filter(c=>c.date===localDate(at));if(which==='week'){const {start,end}=weekRange(at);return all.filter(c=>validDateKey(c.date)&&c.date>=start&&c.date<=end)}const ym=localDate(at).slice(0,7);return all.filter(c=>String(c.date||'').startsWith(ym))}
function completionCount(s,t,which=mode,at=new Date()){const list=comps(s,t,which,at);return t?.type==='daily'?new Set(list.map(c=>c.date)).size:list.length}
function ownCount(s,t,which=mode,at=new Date()){return comps(s,t,which,at).filter(c=>c.by===s.user).length}
function actorSummary(s,t,which=mode,at=new Date()){let list=comps(s,t,which,at);if(t?.type==='daily'){const byDate=new Map();for(const c of list){const previous=byDate.get(c.date);if(!previous||(c.by&&!previous.by))byDate.set(c.date,c)}list=[...byDate.values()]}const totals=new Map();for(const c of list){if(c.by)totals.set(c.by,(totals.get(c.by)||0)+1)}const own=totals.get(s.user)||0,others=[...totals.entries()].filter(([name])=>name!==s.user).sort(([a],[b])=>a.localeCompare(b,'nb')).map(([name,count])=>`${name} ${count}`);return[...(own?[`Du ${own}`]:[]),...others].join(' · ')}
function goal(t,which=mode){const configured=Math.max(1,Number(t?.freq)||1);return t?.type==='daily'?(which==='day'?1:Math.min(7,configured)):configured}
function progress(s,t,which=mode,at=new Date()){const count=completionCount(s,t,which,at),target=goal(t,which);return{count,goal:target,done:count>=target}}
function periodLabel(t){return period(t)==='day'?'Daglig':period(t)==='week'?'Ukentlig':'Månedlig'}
function card(s,t,{carried=false}={}){const which=carried?'day':mode,{count:n,goal:g,done}=progress(s,t,which),daily=t.type==='daily',doneToday=daily&&completionCount(s,t,'day')>=1,ownToday=daily&&ownCount(s,t,'day')>0;let meta;if(carried)meta=`${periodLabel(t)} · gjort i dag · ${t.pts} poeng${t.owner?' · '+t.owner:''}`;else if(mode==='day')meta=`${done?'Fullført · 1/1':'Ikke fullført · 0/1'} · ${t.pts} poeng${t.owner?' · '+t.owner:''}`;else meta=`${n}/${g} ${mode==='week'?'denne uken':'denne måneden'} · ${t.pts} poeng${t.owner?' · '+t.owner:''}`;const actors=mode==='week'&&!carried?actorSummary(s,t,'week'):'',complete=daily&&doneToday?'<button type="button" class="small" disabled>Gjort i dag ✓</button>':`<button type="button" class="small" data-task-complete="${t.id}">+ Gjort</button>`,undoScope=ownToday?'day':which;return `<div class="card"><div class="row"><div class="grow"><strong>${t.name}</strong><div class="taskmeta">${meta}</div>${actors?`<div class="taskmeta">${actors}</div>`:''}</div>${(carried||done)?`<span class="tag">${carried?'Gjort i dag ✓':mode==='day'?'Fullført ✓':'Mål nådd ✓'}</span>`:''}</div><div class="row" style="margin-top:10px">${complete}${ownCount(s,t,undoScope)>0?`<button type="button" class="small" data-period-undo="${t.id}" data-period-scope="${undoScope}">− Angre</button>`:''}</div></div>`}
function title(){return mode==='day'?dayName():mode==='week'?'Denne uken':'Denne måneden'}
function intro(){return mode==='day'?'Her vises dagens gjøremål. Hver daglig oppgave teller maks én gang per dag. Ukentlige og månedlige gjøremål dukker også opp her når de faktisk blir gjort i dag.':mode==='week'?'Her ser du daglige og ukentlige gjøremål samlet for mandag til søndag.':'Her ligger gjøremål som skal gjøres månedlig.'}
function settleScroll(c,pos,forceTop){const target=forceTop?0:Math.max(0,pos||0);c.style.overflowAnchor='none';const apply=()=>{c.scrollTop=target};apply();requestAnimationFrame(()=>{apply();requestAnimationFrame(apply)});setTimeout(()=>{apply();c.style.overflowAnchor=''},120)}
function render({resetScroll=false}={}){const s=state(),c=$('#content');if(!s||!c||s.view!=='tasks')return;painting=true;const beforePos=c.scrollTop,beforeMax=Math.max(0,c.scrollHeight-c.clientHeight),wasBottom=beforeMax-beforePos<36,pos=resetScroll?0:beforePos,all=(s.tasks||[]).filter(t=>relevant(s,t));if(resetScroll){delete c.dataset.flytPendingScroll;delete c.dataset.flytPendingBottom}else{c.dataset.flytPendingScroll=String(pos);c.dataset.flytPendingBottom=wasBottom?'1':'0'}let tasks=all.filter(t=>mode==='week'?period(t)!=='month':period(t)===mode),carried=[];if(mode==='day'){const dailyIds=new Set(tasks.map(t=>String(t.id))),todayIds=new Set((s.completions||[]).filter(x=>x.date===localDate()).map(x=>String(x.taskId)));carried=all.filter(t=>period(t)!=='day'&&todayIds.has(String(t.id))&&!dailyIds.has(String(t.id)))}const groups=new Map();for(const t of tasks){const k=category(t);if(!groups.has(k))groups.set(k,[]);groups.get(k).push(t)}const keys=[...groups.keys()].sort((a,b)=>{const ai=ORDER.indexOf(a),bi=ORDER.indexOf(b);return(ai<0?999:ai)-(bi<0?999:bi)||a.localeCompare(b,'nb')});c.dataset.flytOwner='recurrence';c.innerHTML=`<div class="ey">Gjøremål</div><h1 class="title">${title()}</h1><div class="segments" style="grid-template-columns:repeat(3,1fr);margin:14px 0 18px"><button type="button" data-period-mode="day" class="${mode==='day'?'on':''}">${dayName()}</button><button type="button" data-period-mode="week" class="${mode==='week'?'on':''}">Uke</button><button type="button" data-period-mode="month" class="${mode==='month'?'on':''}">Måned</button></div><p class="sub">${intro()}</p>${!tasks.length?`<div class="card">Ingen ${mode==='day'?'daglige':mode==='week'?'daglige eller ukentlige':'månedlige'} gjøremål.</div>`:''}${keys.map(k=>`<div class="section"><div class="ey">${k}</div>${groups.get(k).map(t=>card(s,t)).join('')}</div>`).join('')}${mode==='day'&&carried.length?`<div class="section"><div class="ey">Gjennomført i dag</div><p class="sub">Ukentlige og månedlige gjøremål som er gjort i dag.</p>${carried.map(t=>card(s,t,{carried:true})).join('')}</div>`:''}<button type="button" class="primary full" data-open-new-setup="1" onclick="window.FlytSetupNavGuard?.openSetup?.(1)||window.FlytTasksUI?.openSetup?.(1)" style="margin-top:18px">Rediger oppsett</button>`;document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('on',b.dataset.view==='tasks'));painting=false;if(window.FlytPlannedUI?.paint){if(resetScroll)settleScroll(c,0,true);queueMicrotask(()=>window.FlytPlannedUI.paint())}else settleScroll(c,pos,resetScroll)}
function undo(id,scope){const s=state(),t=(s?.tasks||[]).find(x=>String(x.id)===String(id));if(!s||!t)return;const list=[...(s.completions||[])];let ix=-1;const {start,end}=weekRange(),ym=localDate().slice(0,7);for(let i=list.length-1;i>=0;i--){const c=list[i];if(String(c.taskId)!==String(id)||c.by!==s.user)continue;const ok=scope==='day'?c.date===localDate():scope==='week'?validDateKey(c.date)&&c.date>=start&&c.date<=end:String(c.date||'').startsWith(ym);if(ok){ix=i;break}}if(ix<0)return;list.splice(ix,1);const points={...(s.points||{})};points[s.user]=Math.max(0,(points[s.user]||0)-Number(t.pts||0));save({...s,view:'tasks',points,completions:list});bridge()?.toast?.('Registreringen er trukket tilbake')}
function tuneSetup(){const body=$('#setupBody');if(!body||$('#setup')?.classList.contains('hidden'))return;body.querySelectorAll('[data-setup-type]').forEach(sel=>{const daily=sel.querySelector('option[value="daily"]'),weekly=sel.querySelector('option[value="flex"]'),monthly=sel.querySelector('option[value="period"]');if(daily)daily.textContent='Daglig';if(weekly)weekly.textContent='Ukentlig';if(monthly)monthly.textContent='Månedlig';const config=sel.closest('.config');if(config){config.querySelectorAll('.label').forEach(l=>{if(l.textContent.trim()==='Timing')l.textContent='Gjentas';if(l.textContent.trim()==='Ganger/uke')l.textContent='Antall per periode'})}})}
function install(){if(installed||!window.FlytTasksUI?.render)return false;installed=true;const originalOpen=window.FlytTasksUI.openSetup?.bind(window.FlytTasksUI);window.FlytTasksUI.render=render;if(originalOpen)window.FlytTasksUI.openSetup=(step=0)=>{originalOpen(step);queueMicrotask(tuneSetup)};if(window.FlytTasksDayCompleted)window.FlytTasksDayCompleted.augment=()=>{};render({resetScroll:false});return true}
document.addEventListener('click',e=>{const tab=e.target.closest('[data-period-mode]');if(tab){e.preventDefault();e.stopImmediatePropagation();tab.blur?.();mode=['day','week','month'].includes(tab.dataset.periodMode)?tab.dataset.periodMode:'day';render({resetScroll:true});return}const undoBtn=e.target.closest('[data-period-undo]');if(undoBtn){e.preventDefault();e.stopImmediatePropagation();undo(undoBtn.dataset.periodUndo,undoBtn.dataset.periodScope||mode);return}},true);
const observer=new MutationObserver(()=>{if(!painting)tuneSetup()});window.addEventListener('DOMContentLoaded',()=>{const body=$('#setupBody');if(body)observer.observe(body,{childList:true,subtree:true})});let tries=0;const timer=setInterval(()=>{if(install()||++tries>80)clearInterval(timer)},100);
window.FlytRecurrenceUI={render,tuneSetup,getMode:()=>mode,dateKey:localDate,weekRange,progress,version:'20260826-1600'};
})();
