(()=>{
'use strict';
const $=s=>document.querySelector(s);
const bridge=()=>window.FlytBridge;
const ORDER=['Barn','Kjøkken','Vask & klær','Stue','Bad','Soverom','Dyr','Hage & ute','Bil','Innkjøp','Vedlikehold','Planlegging & admin','Personlig investering','Egendefinert'];
const OSLO_TIME_ZONE='Europe/Oslo';
const BACKDATE_DAYS=7;
const DAY_SHORT=['Man','Tir','Ons','Tor','Fre','Lør','Søn'];
let mode='day',installed=false,painting=false,pickerOpen=false,suppressPickerClickUntil=0,drag=null,otherOpen=false;
function state(){return bridge()?.getState?.()||null}
function save(next){bridge()?.setState?.(next);window.FlytSync?.queueSave?.()}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function localDate(d=new Date()){const parts=Object.fromEntries(new Intl.DateTimeFormat('nb-NO',{timeZone:OSLO_TIME_ZONE,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(d).filter(x=>x.type!=='literal').map(x=>[x.type,x.value]));return `${parts.year}-${parts.month}-${parts.day}`}
function keyDate(key){return new Date(`${key}T12:00:00Z`)}
function addDays(key,n){const [y,m,d]=String(key).split('-').map(Number),next=new Date(Date.UTC(y,m-1,d+n,12));return next.toISOString().slice(0,10)}
function addMonths(ym,n){const [y,m]=String(ym).split('-').map(Number),d=new Date(Date.UTC(y,m-1+n,1,12));return d.toISOString().slice(0,7)}
function weekRangeForKey(key){const [y,m,d]=String(key).split('-').map(Number),weekday=new Date(Date.UTC(y,m-1,d,12)).getUTCDay(),start=addDays(key,-((weekday+6)%7));return{start,end:addDays(start,6)}}
function weekRange(at=new Date()){return weekRangeForKey(localDate(at))}
function validDateKey(value){return /^\d{4}-\d{2}-\d{2}$/.test(String(value||''))}
function isoDay(key){const d=keyDate(key),n=d.getUTCDay();return n===0?7:n}
function preferredDays(t){return [...new Set((Array.isArray(t?.preferredDays)?t.preferredDays:[]).map(Number).filter(n=>n>=1&&n<=7))].sort((a,b)=>a-b)}
function scheduledFor(t,key){const days=preferredDays(t);return !days.length||days.includes(isoDay(key))}
function scheduleLabel(t){const days=preferredDays(t);if(!days.length)return'';return `Normalt ${days.map(n=>DAY_SHORT[n-1].toLowerCase()).join(', ')}`}
function period(t){return t?.type==='daily'?'day':t?.type==='period'?'month':'week'}
function rhythmLabel(t){return t?.type==='daily'?'Dager per uke':t?.type==='period'?'Ganger per måned':'Ganger per uke'}
function category(t){const raw=(t.cat||'').trim();if(raw==='Husdyr')return'Dyr';if(raw==='Utearbeid')return'Hage & ute';if(raw==='Periodisk vedlikehold')return'Vedlikehold';if(raw==='Usynlig arbeid')return'Planlegging & admin';if(raw==='Hus'){if(['living','hallway'].includes(t.id))return'Stue';if(t.id==='bed')return'Soverom';if(['laundry','vacuum'].includes(t.id))return'Vask & klær';if(t.id==='trash')return'Vedlikehold'}return raw||'Hus'}
function relevant(s,t){return s.categoryRelevant?.[category(t)]!==false}
const todayKey=()=>localDate();
let selectedDay=todayKey(),selectedWeekStart=weekRangeForKey(todayKey()).start,selectedMonth=todayKey().slice(0,7);
function resetCurrent(which=mode){if(which==='day')selectedDay=todayKey();else if(which==='week')selectedWeekStart=weekRangeForKey(todayKey()).start;else selectedMonth=todayKey().slice(0,7)}
function selectedWeekRange(){return{start:selectedWeekStart,end:addDays(selectedWeekStart,6)}}
function selectedMonthKey(){return selectedMonth}
function comps(s,t,which=mode){const all=(s.completions||[]).filter(c=>String(c.taskId)===String(t.id));if(which==='day')return all.filter(c=>c.date===selectedDay);if(which==='week'){const {start,end}=selectedWeekRange();return all.filter(c=>validDateKey(c.date)&&c.date>=start&&c.date<=end)}return all.filter(c=>String(c.date||'').startsWith(selectedMonth))}
function completionCount(s,t,which=mode){const list=comps(s,t,which);return t?.type==='daily'?new Set(list.map(c=>String(c.date||''))).size:list.length}
function dailyWeekCount(s,t,key=selectedDay){const {start,end}=weekRangeForKey(key),list=(s.completions||[]).filter(c=>String(c.taskId)===String(t.id)&&validDateKey(c.date)&&c.date>=start&&c.date<=end);return new Set(list.map(c=>String(c.date))).size}
function ownCount(s,t,which=mode){return comps(s,t,which).filter(c=>c.by===s.user).length}
function actorSummary(s,t,which=mode){let list=comps(s,t,which);if(t?.type==='daily'){const byDate=new Map();for(const c of list)if(!byDate.has(c.date))byDate.set(c.date,c);list=[...byDate.values()]}const totals=new Map();for(const c of list){if(c.by)totals.set(c.by,(totals.get(c.by)||0)+1)}const own=totals.get(s.user)||0,others=[...totals.entries()].filter(([name])=>name!==s.user).sort(([a],[b])=>a.localeCompare(b,'nb')).map(([name,count])=>`${name} ${count}`);return[...(own?[`Du ${own}`]:[]),...others].join(' · ')}
function goal(t,which=mode){const configured=Math.max(1,Number(t?.freq)||1);if(t?.type==='daily')return which==='day'?1:Math.min(7,configured);return configured}
function progress(s,t,which=mode){const count=completionCount(s,t,which),target=goal(t,which);return{count,goal:target,done:count>=target}}
function isTodaySelected(){return selectedDay===todayKey()}
function isCurrentWeek(){return selectedWeekStart===weekRangeForKey(todayKey()).start}
function isCurrentMonth(){return selectedMonth===todayKey().slice(0,7)}
function dayAge(key){const a=Date.UTC(...todayKey().split('-').map((n,i)=>i===1?Number(n)-1:Number(n))),b=Date.UTC(...String(key).split('-').map((n,i)=>i===1?Number(n)-1:Number(n)));return Math.round((a-b)/86400000)}
function dayWritable(){const age=dayAge(selectedDay);return age>=0&&age<=BACKDATE_DAYS}
function writeAllowed(which=mode){return which==='day'?dayWritable():which==='week'?isCurrentWeek():isCurrentMonth()}
function targetDateForWrite(){return mode==='day'?selectedDay:todayKey()}
function selectedDayCount(s,t){return (s.completions||[]).filter(c=>String(c.taskId)===String(t.id)&&c.date===selectedDay).length}
function canComplete(){return writeAllowed()}
function complete(id){const s=state(),t=(s?.tasks||[]).find(x=>String(x.id)===String(id));if(!s||!t)return;if(!canComplete()){bridge()?.toast?.(mode==='day'?'Etterregistrering er mulig inntil 7 dager tilbake':'Velg Dag for å etterregistrere i en tidligere periode');return}const date=targetDateForWrite(),now=Date.now(),housePts=t.kind==='house'?Number(t.pts||0):Math.round(Number(t.pts||0)*.2),points={...(s.points||{})};points[s.user]=(points[s.user]||0)+Number(t.pts||0);const completion={id:now,taskId:t.id,date,by:s.user,kind:t.kind,housePts,registeredAt:new Date().toISOString(),backdated:date!==todayKey(),taskSnapshot:{name:t.name,cat:category(t),pts:Number(t.pts||0),type:t.type,kind:t.kind}};save({...s,view:'tasks',points,completions:[...(s.completions||[]),completion]});if(mode==='day'&&!scheduledFor(t,selectedDay))otherOpen=true;bridge()?.toast?.(`${t.name} registrert${date!==todayKey()?' for valgt dag':''} · +${t.pts} poeng`)}
function undo(id,scope){const s=state(),t=(s?.tasks||[]).find(x=>String(x.id)===String(id));if(!s||!t)return;const list=[...(s.completions||[])];let ix=-1;const wr=selectedWeekRange();for(let i=list.length-1;i>=0;i--){const c=list[i];if(String(c.taskId)!==String(id)||c.by!==s.user)continue;const ok=scope==='day'?c.date===selectedDay:scope==='week'?validDateKey(c.date)&&c.date>=wr.start&&c.date<=wr.end:String(c.date||'').startsWith(selectedMonth);if(ok){ix=i;break}}if(ix<0)return;list.splice(ix,1);const points={...(s.points||{})};points[s.user]=Math.max(0,(points[s.user]||0)-Number(t.pts||0));save({...s,view:'tasks',points,completions:list});bridge()?.toast?.('Registreringen er trukket tilbake')}
function card(s,t,{dayOther=false}={}){const dayView=mode==='day',which=dayView?'day':mode,{count:n,goal:g,done}=progress(s,t,which),writable=writeAllowed(),dayCount=dayView?selectedDayCount(s,t):0,weekDone=t.type==='daily'?dailyWeekCount(s,t,dayView?selectedDay:selectedWeekStart):null,weekGoal=t.type==='daily'?goal(t,'week'):null,schedule=scheduleLabel(t);let meta;if(dayView&&t.type==='daily'){const todayPart=dayCount?`Fullført · 1/1${dayCount>1?` · utført ${dayCount} ganger`:''}`:'0/1 i dag';meta=`${todayPart} · Uke ${weekDone}/${weekGoal}${schedule?' · '+schedule:''} · ${t.pts} poeng${t.owner?' · '+esc(t.owner):''}`}else if(dayView&&t.type==='flex'){const {start,end}=weekRangeForKey(selectedDay),weekCount=(s.completions||[]).filter(c=>String(c.taskId)===String(t.id)&&validDateKey(c.date)&&c.date>=start&&c.date<=end).length;meta=`${rhythmLabel(t)} · ${weekCount}/${goal(t,'week')} denne uka · ${dayCount?`${dayCount} i dag · `:''}${t.pts} poeng${t.owner?' · '+esc(t.owner):''}`}else if(dayView&&t.type==='period'){const ym=selectedDay.slice(0,7),monthCount=(s.completions||[]).filter(c=>String(c.taskId)===String(t.id)&&String(c.date||'').startsWith(ym)).length;meta=`${rhythmLabel(t)} · ${monthCount}/${goal(t,'month')} denne måneden · ${dayCount?`${dayCount} i dag · `:''}${t.pts} poeng${t.owner?' · '+esc(t.owner):''}`}else meta=`${n}/${g} ${mode==='week'?'i valgt uke':'i valgt måned'}${schedule&&mode==='week'?' · '+schedule:''} · ${t.pts} poeng${t.owner?' · '+esc(t.owner):''}`;const actors=mode==='week'?actorSummary(s,t,'week'):'',button=!writable?'<button type="button" class="small" disabled>Historikk</button>':`<button type="button" class="small" data-period-complete="${esc(t.id)}">${dayCount?'+ Gjort igjen':'+ Gjort'}</button>`,badge=dayView&&dayCount?'<span class="tag">Fullført ✓</span>':!dayView&&done?'<span class="tag">Mål nådd ✓</span>':'';return `<div class="card"><div class="row"><div class="grow"><strong>${esc(t.name)}</strong><div class="taskmeta">${meta}</div>${dayOther?'<div class="taskmeta">Kan gjøres i dag selv om den ikke ligger i dagens normale rytme.</div>':''}${actors?`<div class="taskmeta">${esc(actors)}</div>`:''}</div>${badge}</div><div class="row" style="margin-top:10px">${button}${ownCount(s,t,dayView?'day':mode)>0&&writable?`<button type="button" class="small" data-period-undo="${esc(t.id)}" data-period-scope="${dayView?'day':mode}">− Angre</button>`:''}</div></div>`}
function dateLabel(key,{long=false}={}){const d=keyDate(key);return new Intl.DateTimeFormat('nb-NO',{timeZone:'UTC',weekday:long?'long':'short',day:'numeric',month:long?'long':undefined}).format(d).replace(/^./,c=>c.toUpperCase())}
function monthLabel(ym,{year=false}={}){const d=keyDate(`${ym}-01`);const text=new Intl.DateTimeFormat('nb-NO',{timeZone:'UTC',month:'long',year:year?'numeric':undefined}).format(d);return text.replace(/^./,c=>c.toUpperCase())}
function isoWeek(start){const d=keyDate(start),target=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate(),12)),day=(target.getUTCDay()+6)%7;target.setUTCDate(target.getUTCDate()-day+3);const first=new Date(Date.UTC(target.getUTCFullYear(),0,4,12)),firstDay=(first.getUTCDay()+6)%7;first.setUTCDate(first.getUTCDate()-firstDay+3);return 1+Math.round((target-first)/604800000)}
function title(){if(mode==='day')return isTodaySelected()?dateLabel(selectedDay,{long:true}).split(' ')[0]:dateLabel(selectedDay,{long:true});if(mode==='week')return isCurrentWeek()?'Denne uken':`Uke ${isoWeek(selectedWeekStart)}`;return isCurrentMonth()?'Denne måneden':monthLabel(selectedMonth,{year:true})}
function intro(){if(mode==='day'){if(isTodaySelected())return'Dagens normale rytme ligger øverst. Andre aktive gjøremål kan fortsatt registreres når dagen ikke går etter planen.';const age=dayAge(selectedDay);return age>=0&&age<=BACKDATE_DAYS?'Du ser en tidligere dag. Gjøremål kan etterregistreres her.':'Du ser historikk for valgt dag.'}if(mode==='week')return isCurrentWeek()?'Her ser du både dager-per-uke og ganger-per-uke samlet. Mål er retning, ikke en sperre.':'Historikk for valgt uke. Etterregistrering gjøres via Dag.';return isCurrentMonth()?'Her ligger gjøremål med månedsrytme.':'Historikk for valgt måned. Etterregistrering gjøres via Dag.'}
function infoStrip(){if(mode==='day'&&!isTodaySelected()){const writable=dayWritable();return `<div class="card" style="padding:11px 13px;background:#fff5e9;border-color:#f0d8b3"><div class="row"><span class="grow"><strong>${writable?'Du registrerer for':'Du ser'} ${esc(dateLabel(selectedDay,{long:true}))}</strong><div class="taskmeta">${writable?'Endringer lagres på valgt dag, ikke i dag.':'Denne dagen er eldre enn 7 dager og er skrivebeskyttet.'}</div></span><button type="button" class="small" data-period-today="1">Tilbake til i dag</button></div></div>`}if(mode==='week'&&!isCurrentWeek())return `<div class="card" style="padding:11px 13px;background:#fff5e9;border-color:#f0d8b3"><div class="row"><span class="grow"><strong>Du ser uke ${isoWeek(selectedWeekStart)}</strong><div class="taskmeta">Historikk · bruk Dag for etterregistrering.</div></span><button type="button" class="small" data-period-current="week">Denne uka</button></div></div>`;if(mode==='month'&&!isCurrentMonth())return `<div class="card" style="padding:11px 13px;background:#fff5e9;border-color:#f0d8b3"><div class="row"><span class="grow"><strong>Du ser ${esc(monthLabel(selectedMonth,{year:true}))}</strong><div class="taskmeta">Historikk · bruk Dag for etterregistrering.</div></span><button type="button" class="small" data-period-current="month">Denne måneden</button></div></div>`;return''}
function pickerStyle(){return'padding:9px 8px;margin:-8px 0 14px;touch-action:pan-y;user-select:none;-webkit-user-select:none;overflow:hidden'}
function dayPicker(){const wr=weekRangeForKey(selectedDay),days=Array.from({length:7},(_,i)=>addDays(wr.start,i)),today=todayKey();return `<div class="card" data-period-picker="day" style="${pickerStyle()}" aria-label="Dra sidelengs for å bytte dag"><div data-period-drag-track style="display:grid;grid-template-columns:repeat(7,minmax(0,1fr));gap:4px;align-items:stretch;will-change:transform">${days.map(k=>{const d=keyDate(k),wd=new Intl.DateTimeFormat('nb-NO',{timeZone:'UTC',weekday:'short'}).format(d).replace('.',''),num=String(d.getUTCDate()),future=k>today;return `<button type="button" class="small ${k===selectedDay?'primary':''}" data-period-day="${k}" ${future?'disabled':''} style="padding:8px 1px;min-width:0"><span style="display:block;font-size:9px">${esc(wd)}</span><strong>${num}</strong></button>`}).join('')}</div></div>`}
function weekPicker(){const starts=Array.from({length:3},(_,i)=>addDays(selectedWeekStart,(i-1)*7));return `<div class="card" data-period-picker="week" style="${pickerStyle()}" aria-label="Dra sidelengs for å bytte uke"><div data-period-drag-track style="display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:7px;will-change:transform">${starts.map(k=>`<button type="button" class="small ${k===selectedWeekStart?'primary':''}" data-period-week="${k}" style="padding:9px 4px;min-width:0"><span style="display:block;font-size:10px">Uke</span><strong>${isoWeek(k)}</strong></button>`).join('')}</div></div>`}
function monthPicker(){const months=Array.from({length:3},(_,i)=>addMonths(selectedMonth,i-1));return `<div class="card" data-period-picker="month" style="${pickerStyle()}" aria-label="Dra sidelengs for å bytte måned"><div data-period-drag-track style="display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:7px;will-change:transform">${months.map(ym=>`<button type="button" class="small ${ym===selectedMonth?'primary':''}" data-period-month="${ym}" style="padding:10px 4px;min-width:0;font-size:12px">${esc(monthLabel(ym))}</button>`).join('')}</div></div>`}
function picker(){if(!pickerOpen)return'';return mode==='day'?dayPicker():mode==='week'?weekPicker():monthPicker()}
function segment(label,key){const active=mode===key,arrow=active&&pickerOpen?'⌃':'⌄';return `<button type="button" data-period-mode="${key}" class="${active?'on':''}">${label} <span aria-hidden="true" style="font-size:11px">${arrow}</span></button>`}
function groupCards(items,s,opts={}){const groups=new Map();for(const t of items){const k=category(t);if(!groups.has(k))groups.set(k,[]);groups.get(k).push(t)}const keys=[...groups.keys()].sort((a,b)=>{const ai=ORDER.indexOf(a),bi=ORDER.indexOf(b);return(ai<0?999:ai)-(bi<0?999:bi)||a.localeCompare(b,'nb')});return keys.map(k=>`<div class="section"><div class="ey">${esc(k)}</div>${groups.get(k).map(t=>card(s,t,opts)).join('')}</div>`).join('')}
function settleScroll(c,pos,forceTop){const target=forceTop?0:Math.max(0,pos||0);c.style.overflowAnchor='none';const apply=()=>{c.scrollTop=target};apply();requestAnimationFrame(()=>{apply();requestAnimationFrame(apply)});setTimeout(()=>{apply();c.style.overflowAnchor=''},120)}
function render({resetScroll=false}={}){const s=state(),c=$('#content');if(!s||!c||s.view!=='tasks')return;painting=true;const beforePos=c.scrollTop,beforeMax=Math.max(0,c.scrollHeight-c.clientHeight),wasBottom=beforeMax-beforePos<36,pos=resetScroll?0:beforePos,all=(s.tasks||[]).filter(t=>relevant(s,t));if(resetScroll){delete c.dataset.flytPendingScroll;delete c.dataset.flytPendingBottom}else{c.dataset.flytPendingScroll=String(pos);c.dataset.flytPendingBottom=wasBottom?'1':'0'}let main=[],other=[];if(mode==='day'){main=all.filter(t=>t.type==='daily'&&scheduledFor(t,selectedDay));other=all.filter(t=>!main.includes(t))}else if(mode==='week')main=all.filter(t=>t.type==='daily'||t.type==='flex');else main=all.filter(t=>t.type==='period');c.dataset.flytOwner='recurrence';const otherMarkup=mode==='day'&&other.length?`<div class="section"><button type="button" class="secondary full" data-period-other="1">${otherOpen?'Skjul':'Vis'} andre gjøremål (${other.length})</button>${otherOpen?`<p class="sub" style="margin-top:10px">Planer er nyttige. Dager er mindre samarbeidsvillige. Alt under kan registreres også i dag.</p>${groupCards(other,s,{dayOther:true})}`:''}</div>`:'';c.innerHTML=`<div class="ey">Gjøremål</div><h1 class="title">${esc(title())}</h1><div class="segments" data-period-tabs style="grid-template-columns:repeat(3,1fr);margin:14px 0 18px;touch-action:pan-y;user-select:none;-webkit-user-select:none">${segment('Dag','day')}${segment('Uke','week')}${segment('Måned','month')}</div>${picker()}${infoStrip()}<p class="sub">${esc(intro())}</p>${!main.length?`<div class="card">Ingen gjøremål i den normale rytmen for valgt ${mode==='day'?'dag':mode==='week'?'uke':'måned'}.</div>`:''}${groupCards(main,s)}${otherMarkup}<button type="button" class="primary full" data-open-new-setup="1" onclick="window.FlytSetupNavGuard?.openSetup?.(1)||window.FlytTasksUI?.openSetup?.(1)" style="margin-top:18px">Rediger oppsett</button>`;document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('on',b.dataset.view==='tasks'));painting=false;if(window.FlytPlannedUI?.paint){if(resetScroll)settleScroll(c,0,true);queueMicrotask(()=>window.FlytPlannedUI.paint())}else settleScroll(c,pos,resetScroll)}
function canShiftSelection(kind,steps){if(!steps)return false;if(kind==='day'){const next=addDays(selectedDay,steps);return next!==selectedDay&&!(steps>0&&next>todayKey())}if(kind==='week')return true;if(kind==='month')return true;return false}
function shiftSelection(kind,steps){if(!canShiftSelection(kind,steps))return false;if(kind==='day'){selectedDay=addDays(selectedDay,steps);return true}if(kind==='week'){selectedWeekStart=addDays(selectedWeekStart,steps*7);return true}if(kind==='month'){selectedMonth=addMonths(selectedMonth,steps);return true}return false}
function shiftMode(steps){const modes=['day','week','month'],i=modes.indexOf(mode),next=Math.max(0,Math.min(modes.length-1,i+steps));if(next===i)return false;mode=modes[next];pickerOpen=false;otherOpen=false;return true}
function dragReset(animate=true){if(!drag)return;const track=drag.track;if(track){track.style.transition=animate?'transform .14s ease':'none';track.style.transform='translateX(0px)';if(animate)setTimeout(()=>{if(track.isConnected)track.style.transition=''},160)}drag=null}
function beginDrag(e){const picker=e.target.closest?.('[data-period-picker]'),tabs=e.target.closest?.('[data-period-tabs]');if(!picker&&!tabs)return;if(e.pointerType==='mouse'&&e.button!==0)return;const host=picker||tabs,track=picker?.querySelector('[data-period-drag-track]')||tabs;drag={id:e.pointerId,x:e.clientX,y:e.clientY,dx:0,dy:0,active:false,cancelled:false,kind:picker?.dataset.periodPicker||'tabs',host,track};if(track)track.style.transition='none';try{host.setPointerCapture?.(e.pointerId)}catch(err){}}
function moveDrag(e){if(!drag||drag.id!==e.pointerId||drag.cancelled)return;drag.dx=e.clientX-drag.x;drag.dy=e.clientY-drag.y;const ax=Math.abs(drag.dx),ay=Math.abs(drag.dy);if(!drag.active){if(ay>10&&ay>ax){drag.cancelled=true;dragReset(false);return}if(ax<9||ax<=ay*1.12)return;drag.active=true}if(!drag.track)return;e.preventDefault();const step=drag.dx<0?1:-1;if(drag.kind!=='tabs'&&!canShiftSelection(drag.kind,step)){drag.track.style.transform='translateX(0px)';return}const slots=drag.kind==='day'?7:3,max=Math.max(54,(drag.host?.clientWidth||270)/slots),visual=Math.max(-max,Math.min(max,drag.dx*.55));drag.track.style.transform=`translateX(${visual}px)`}
function endDrag(e){if(!drag||drag.id!==e.pointerId)return;const current=drag,ax=Math.abs(current.dx),active=current.active&&!current.cancelled;drag=null;if(current.track){current.track.style.transition='transform .12s ease';current.track.style.transform='translateX(0px)'}if(!active||ax<38){if(current.track)setTimeout(()=>{if(current.track.isConnected)current.track.style.transition=''},150);return}e.preventDefault();suppressPickerClickUntil=Date.now()+420;const step=current.dx<0?1:-1;if(current.kind==='tabs'){if(shiftMode(step))render({resetScroll:false});return}if(!canShiftSelection(current.kind,step))return;if(shiftSelection(current.kind,step)){pickerOpen=true;otherOpen=false;render({resetScroll:false})}}
function cancelDrag(e){if(!drag||drag.id!==e.pointerId)return;dragReset(true)}
function tuneSetup(){const body=$('#setupBody');if(!body||$('#setup')?.classList.contains('hidden'))return;body.querySelectorAll('[data-setup-type]').forEach(sel=>{const daily=sel.querySelector('option[value="daily"]'),weekly=sel.querySelector('option[value="flex"]'),monthly=sel.querySelector('option[value="period"]');if(daily)daily.textContent='Dager per uke';if(weekly)weekly.textContent='Ganger per uke';if(monthly)monthly.textContent='Ganger per måned';const config=sel.closest('.config');if(config){config.querySelectorAll('.label').forEach(l=>{if(l.textContent.trim()==='Timing'||l.textContent.trim()==='Gjentas')l.textContent='Rytme';if(l.textContent.trim()==='Ganger/uke')l.textContent='Mål'})}})}
function install(){if(installed||!window.FlytTasksUI?.render)return false;installed=true;const originalOpen=window.FlytTasksUI.openSetup?.bind(window.FlytTasksUI);window.FlytTasksUI.render=render;if(originalOpen)window.FlytTasksUI.openSetup=(step=0)=>{originalOpen(step);queueMicrotask(tuneSetup)};if(window.FlytTasksDayCompleted)window.FlytTasksDayCompleted.augment=()=>{};render({resetScroll:false});return true}
document.addEventListener('pointerdown',beginDrag,true);
document.addEventListener('pointermove',moveDrag,{capture:true,passive:false});
document.addEventListener('pointerup',endDrag,true);
document.addEventListener('pointercancel',cancelDrag,true);
document.addEventListener('click',e=>{if(Date.now()<suppressPickerClickUntil&&e.target.closest?.('[data-period-picker],[data-period-tabs]')){e.preventDefault();e.stopImmediatePropagation();return}const tab=e.target.closest('[data-period-mode]');if(tab){e.preventDefault();e.stopImmediatePropagation();tab.blur?.();const next=['day','week','month'].includes(tab.dataset.periodMode)?tab.dataset.periodMode:'day';if(next===mode)pickerOpen=!pickerOpen;else{mode=next;pickerOpen=false;otherOpen=false}render({resetScroll:false});return}const shift=e.target.closest('[data-period-shift]');if(shift){e.preventDefault();e.stopImmediatePropagation();const [kind,raw]=String(shift.dataset.periodShift).split(':'),amount=Number(raw)||0;if(kind==='day')selectedDay=addDays(selectedDay,amount);else if(kind==='week')selectedWeekStart=addDays(selectedWeekStart,amount);else if(kind==='month')selectedMonth=addMonths(selectedMonth,amount);render({resetScroll:false});return}const day=e.target.closest('[data-period-day]');if(day){e.preventDefault();e.stopImmediatePropagation();const next=day.dataset.periodDay;if(next<=todayKey())selectedDay=next;pickerOpen=false;otherOpen=false;render({resetScroll:false});return}const week=e.target.closest('[data-period-week]');if(week){e.preventDefault();e.stopImmediatePropagation();selectedWeekStart=week.dataset.periodWeek;pickerOpen=false;render({resetScroll:false});return}const month=e.target.closest('[data-period-month]');if(month){e.preventDefault();e.stopImmediatePropagation();selectedMonth=month.dataset.periodMonth;pickerOpen=false;render({resetScroll:false});return}const other=e.target.closest('[data-period-other]');if(other){e.preventDefault();e.stopImmediatePropagation();otherOpen=!otherOpen;render({resetScroll:false});return}const today=e.target.closest('[data-period-today]');if(today){e.preventDefault();e.stopImmediatePropagation();resetCurrent('day');pickerOpen=false;otherOpen=false;render({resetScroll:false});return}const current=e.target.closest('[data-period-current]');if(current){e.preventDefault();e.stopImmediatePropagation();resetCurrent(current.dataset.periodCurrent);pickerOpen=false;render({resetScroll:false});return}const add=e.target.closest('[data-period-complete]');if(add){e.preventDefault();e.stopImmediatePropagation();complete(add.dataset.periodComplete);return}const undoBtn=e.target.closest('[data-period-undo]');if(undoBtn){e.preventDefault();e.stopImmediatePropagation();undo(undoBtn.dataset.periodUndo,undoBtn.dataset.periodScope||mode);return}},true);
const observer=new MutationObserver(()=>{if(!painting)tuneSetup()});window.addEventListener('DOMContentLoaded',()=>{const body=$('#setupBody');if(body)observer.observe(body,{childList:true,subtree:true})});let tries=0;const timer=setInterval(()=>{if(install()||++tries>80)clearInterval(timer)},100);
window.FlytRecurrenceUI={render,tuneSetup,getMode:()=>mode,dateKey:localDate,weekRange,progress,getSelectedDate:()=>selectedDay,getSelectedWeekRange:selectedWeekRange,getSelectedMonth:()=>selectedMonth,isPickerOpen:()=>pickerOpen,version:'20260827-1455'};
})();