(()=>{
'use strict';
const $=s=>document.querySelector(s);
const bridge=()=>window.FlytBridge;
if(!window.FlytStatusAlert&&!document.querySelector('script[data-flyt-status-alert]')){const sc=document.createElement('script');sc.src='./status-alert-ui.js?v=20260824-1212';sc.defer=true;sc.dataset.flytStatusAlert='1';document.head.appendChild(sc)}
let painting=false;
function state(){return bridge()?.getState?.()||null}
function save(next){bridge()?.setState?.(next);window.FlytSync?.queueSave?.()}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function items(s){return (Array.isArray(s?.work)?s.work:[]).filter(x=>x.source==='manual').sort((a,b)=>Number(b.createdAt||b.id||0)-Number(a.createdAt||a.id||0)).slice(0,12)}
function card(s,w){const mine=w.by===s.user;return `<div class="card row"><div class="grow"><strong>${esc(w.title)}</strong><div class="taskmeta">${esc(w.by||'')}</div></div>${mine?(w.seen?'<span class="tag">Sett ✓</span>':'<span class="taskmeta">Ikke sett ennå</span>'):(w.seen?'<span class="tag">Sett ✓</span>':`<button type="button" class="small" data-seen-ack="${w.id}">Jeg så det</button>`)}</div>`}
function render(){const s=state(),c=$('#content');if(!s||!c||s.view!=='seen')return;painting=true;const list=items(s);c.dataset.flytOwner='seen-new';c.innerHTML=`<div class="ey">Sett</div><h1 class="title">Se det som ellers ikke blir sett</h1><p class="sub">Her hører initiativ, planlegging og andre bidrag hjemme når de ellers lett kunne gått ubemerket hen. Vanlige gjøremål logges ikke her.</p>${list.length?list.map(w=>card(s,w)).join(''):'<div class="card"><strong>Ingenting å anerkjenne ennå</strong><p class="sub">Sett er ikke en aktivitetslogg. Legg bare inn noe som faktisk kan være lett å overse.</p></div>'}<button type="button" id="seenAdd" class="primary full">+ Legg til bidrag</button>`;document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('on',b.dataset.view==='seen'));painting=false}
document.addEventListener('click',e=>{const nav=e.target.closest('#nav button[data-view="seen"]');if(nav){e.preventDefault();e.stopImmediatePropagation();const s=state();if(!s)return;save({...s,view:'seen'});queueMicrotask(render);return}if(state()?.view!=='seen')return;const ack=e.target.closest('[data-seen-ack]');if(ack){e.preventDefault();e.stopImmediatePropagation();const s=state(),work=[...(s.work||[])],w=work.find(x=>String(x.id)===String(ack.dataset.seenAck)&&x.source==='manual');if(w&&w.by!==s.user){w.seen=true;w.seenAt=new Date().toISOString();save({...s,work});queueMicrotask(render)}return}const add=e.target.closest('#seenAdd');if(add){e.preventDefault();e.stopImmediatePropagation();const title=prompt('Hva gjorde du som ellers lett kunne gått ubemerket hen?');if(!title?.trim())return;const s=state(),now=Date.now(),work=[{id:now,title:title.trim(),by:s.user,seen:false,source:'manual',createdAt:now},...(s.work||[])];save({...s,work});queueMicrotask(render);bridge()?.toast?.('Bidraget er lagt i Sett');return}},true);
const observer=new MutationObserver(()=>{if(painting)return;const s=state(),c=$('#content');if(s?.view==='seen'&&c?.dataset.flytOwner!=='seen-new')queueMicrotask(render)});
let observed=false,tries=0;const timer=setInterval(()=>{const c=$('#content');if(c&&!observed){observer.observe(c,{childList:true,subtree:true});observed=true}const s=state();if(s?.view==='seen')render();if(observed&&++tries>80)clearInterval(timer)},100);
window.FlytSeenUI={render,version:'20260824-1258'};
})();