(()=>{
'use strict';
const VERSION='20260922-contributions1';
const $=selector=>document.querySelector(selector);
const bridge=()=>window.FlytBridge;
const core=()=>window.FlytSeenCore;
const CATEGORY={
  nice:{title:'Noe fint',icon:'♥',subtitle:'Send en liten beskjed som varmer.'},
  flirt:{title:'Flørt',icon:'😏',subtitle:'Send noe lekent, uten å gjøre det til en Fristelse.'},
  space:{title:'Gi litt rom',icon:'🌿',subtitle:'Vis forståelse uten å flytte oppgaver eller ansvar.'}
};
const DEFAULTS={
  nice:['Tenkte bare på deg ❤️','Håper du vet hvor glad jeg er for at vi er oss.','Du gjør hverdagen min litt finere.'],
  flirt:['Du så ganske bra ut i morges, bare så du vet det.','Jeg gleder meg litt ekstra til å se deg senere 😏','Bare en påminnelse: Jeg synes du er skikkelig fin.'],
  space:['Du trenger ikke prestere noe i dag ❤️','Jeg ser at du har mye i dag. Ta det litt med ro, så ordner vi resten ❤️','Ta den plassen du trenger i dag. Jeg er her.']
};
let page='main',sheet=null,painting=false,recognitionAlertOpen=false,recognitionAlertPaused=false;

function state(){return bridge()?.getState?.()||null}
function save(next){bridge()?.setState?.(next);window.FlytSync?.queueSave?.()}
function toast(text){bridge()?.toast?.(text)}
function esc(value){return String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]))}
function profileKey(s){return String(window.FlytSync?.getContext?.()?.user_id||s?.user||'')}
function partnerName(s){const context=window.FlytSync?.getContext?.(),member=context?.members?.find(item=>String(item.id)!==String(context?.user_id));return member?.display_name||Object.keys(s?.status||{}).find(name=>name!==s?.user)||Object.keys(s?.points||{}).find(name=>name!==s?.user)||'partneren din'}
function today(){return core()?.dateKey?.()||new Date().toISOString().slice(0,10)}
function timeLabel(value){const date=new Date(value||0);if(Number.isNaN(date.getTime()))return'';return new Intl.DateTimeFormat('nb-NO',{timeZone:'Europe/Oslo',hour:'2-digit',minute:'2-digit'}).format(date)}
function dateTimeLabel(value){const date=new Date(value||0);if(Number.isNaN(date.getTime()))return'Dato ukjent';return new Intl.DateTimeFormat('nb-NO',{timeZone:'Europe/Oslo',day:'numeric',month:'long',hour:'2-digit',minute:'2-digit'}).format(date)}
function ref(kind,id){return`${encodeURIComponent(kind)}|${encodeURIComponent(String(id))}`}
function readRef(value){const[kind,id]=String(value||'').split('|');return{kind:decodeURIComponent(kind||'completion'),id:decodeURIComponent(id||'')}}
function personal(s,category){return(core()?.personalNudges?.(s,profileKey(s))||[]).filter(item=>item.category===category).map(item=>item.text)}
function unique(values){const seen=new Set;return values.filter(value=>{const key=String(value||'').trim();if(!key||seen.has(key))return false;seen.add(key);return true})}
function manualSuggestions(s){return unique([...(core()?.suggestions?.(s,s.user)||[]),...personal(s,'recognition')]).slice(0,6)}
function categorySuggestions(s,category){return unique([...personal(s,category),...(DEFAULTS[category]||[])]).slice(0,5)}

function ensureStyles(){
  if($('#flytSeenStyles'))return;
  const style=document.createElement('style');style.id='flytSeenStyles';style.textContent=`
  #content[data-flyt-owner="seen-actions"]{background:radial-gradient(circle at 92% 1%,#f8d3c14d 0 112px,transparent 113px),linear-gradient(#fffaf7,#fff5ef);color:var(--ink)}
  .seenPage{max-width:520px;margin:0 auto;padding-bottom:8px}.seenHeader{margin:0 2px 18px}.seenHeader .ey{color:#b85e43;letter-spacing:.17em}.seenTitle{font:500 38px/1.03 Georgia,serif;margin:5px 0 7px;color:#392822}.seenSubtitle{margin:0;color:#806b61;line-height:1.45}.seenSection{margin-top:22px}.seenSectionTitle{font:600 21px/1.18 Georgia,serif;margin:0 2px 10px;color:#3d2b25}
  .seenContributionCard{padding:7px 12px;border:1px solid #ead7ce;border-radius:22px;background:#fffdf9;box-shadow:0 10px 28px #79503a0d}.seenContributionList{max-height:222px;overflow-y:auto;overscroll-behavior:contain;scrollbar-width:thin}.seenContribution{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:10px;align-items:center;padding:12px 2px;border-top:1px solid #f0e2db}.seenContribution:first-child{border-top:0}.seenContribution strong{display:block;font:600 17px/1.22 Georgia,serif}.seenContributionMeta{display:block;margin-top:4px;color:#806b61;font-size:12px}.seenAckButton{min-width:76px;min-height:42px;border:1px solid #e3b7a5;border-radius:999px;background:#fff4ee;color:#a24f3b;font-weight:850;padding:8px 11px}.seenAckButton.on{border-color:#c9634b;background:#e87961;color:#fff}.seenAckMessage{display:inline-block;margin-top:7px;border:0;background:transparent;color:#a8523e;font-size:12px;font-weight:800;padding:2px 0}.seenEmpty{padding:16px 4px;color:#806b61;line-height:1.45}
  .seenManualCard{padding:16px;border:1px solid #eadbd2;border-radius:20px;background:linear-gradient(145deg,#fffaf7,#ffede4)}.seenManualCard p{margin:0 0 13px;color:#806b61;line-height:1.42}.seenPrimary{width:100%;min-height:46px;border:0;border-radius:14px;background:linear-gradient(135deg,#e87961,#bd543f);color:#fff;font-weight:850;padding:11px 14px}.seenSecondaryActions{display:flex;gap:8px;flex-wrap:wrap}.seenSecondaryAction{flex:1 1 105px;min-height:44px;border:1px solid #eadbd2;border-radius:999px;background:#fffdf9;color:#573a31;font-weight:800;padding:9px 12px}.seenLast{display:grid;grid-template-columns:28px minmax(0,1fr);gap:9px;padding:12px;border:1px solid #eadbd2;border-radius:16px;background:#fffdf9}.seenLast p{margin:0;line-height:1.4}.seenLast small{display:block;margin-top:4px;color:#806b61}.seenHistoryLink{display:block;margin:12px auto 0;border:0;background:transparent;color:#a8523e;font-weight:800;padding:8px;text-decoration:underline;text-underline-offset:4px}
  .seenSubHead{display:flex;align-items:center;gap:11px;margin-bottom:18px}.seenBack{width:40px;height:40px;padding:0;border:1px solid #eadbd2;border-radius:50%;background:#fffaf7;font-size:20px}.seenHistoryGroup{margin-top:18px}.seenHistoryDate{margin:0 2px 8px;color:#806b61;font-size:12px;font-weight:900;text-transform:uppercase;letter-spacing:.08em}.seenHistoryList{display:grid;gap:9px}.seenHistoryItem{display:grid;grid-template-columns:28px minmax(0,1fr);gap:9px;padding:12px;border:1px solid #eadbd2;border-radius:16px;background:#fffdf9}.seenHistoryItem p{margin:0;line-height:1.4}.seenHistoryItem small{display:block;margin-top:4px;color:#806b61}
  .seenSheetLayer{position:fixed;inset:0;z-index:920;display:flex;align-items:flex-end;justify-content:center;background:#3a211b66}.seenSheet{width:min(100%,520px);max-height:88dvh;overflow:auto;padding:18px 16px max(20px,env(safe-area-inset-bottom));border-radius:26px 26px 0 0;background:#fffaf7;box-shadow:0 -20px 60px #4d291f33}.seenSheetHead{display:flex;justify-content:space-between;align-items:flex-start;gap:12px}.seenSheetHead h2{font:600 28px/1.1 Georgia,serif;margin:4px 0 5px}.seenSheetClose{width:40px;height:40px;border:1px solid #eadbd2;border-radius:50%;background:#fff;font-size:24px}.seenChips{display:flex;flex-wrap:wrap;gap:8px;margin:15px 0}.seenChip{border:1px solid #e4c7ba;border-radius:999px;background:#fff4ee;color:#75473a;font-weight:750;padding:9px 11px}.seenTextarea{width:100%;min-height:96px;resize:vertical;border:1px solid #e7d8cf;border-radius:14px;background:#fff;padding:12px;font:inherit;font-size:16px;line-height:1.45;color:var(--ink);outline:none}.seenTextarea:focus{border-color:#d67a5a;box-shadow:0 0 0 3px #e8796118}.seenHelper{margin:6px 2px 12px;color:#8a756c;font-size:12px;line-height:1.4}
  .nav{grid-template-columns:repeat(4,1fr)}@media(min-width:700px){.seenSheetLayer{align-items:center}.seenSheet{border-radius:26px;max-height:800px}}@media(max-width:360px){.seenTitle{font-size:34px}.seenContributionCard,.seenManualCard{padding-left:12px;padding-right:12px}}
  `;document.head.appendChild(style);
}
function contributionMarkup(row){const acknowledged=!!row.acknowledgement,key=ref(row.kind,row.id);return `<article class="seenContribution"><div><strong>${esc(row.title)}</strong><span class="seenContributionMeta">${esc(row.by)}${row.at?` · ${timeLabel(row.at)}`:''}</span>${acknowledged?`<button type="button" class="seenAckMessage" data-seen-ack-message="${key}">${row.acknowledgement.text?'Rediger melding':'+ Legg til en melding'}</button>`:''}</div><button type="button" class="seenAckButton ${acknowledged?'on':''}" data-seen-ack="${key}" aria-pressed="${acknowledged}">${acknowledged?'Sett ♥':'Sett ♡'}</button></article>`}
function historyIcon(type){return type==='space'?'🌿':type==='flirt'?'😏':'♥'}
function renderMain(s){
  const partner=partnerName(s),rows=core()?.contributions?.(s,{user:s.user,date:today()})||[],latest=(core()?.recognitionEvents?.(s)||[])[0];
  return `<div class="seenPage"><header class="seenHeader"><div class="ey">Sett</div><h1 class="seenTitle">Se hverandre</h1><p class="seenSubtitle">Legg merke til det partneren faktisk gjør, stort og smått.</p></header><section><h2 class="seenSectionTitle">${esc(partner)} har bidratt i dag</h2><div class="seenContributionCard">${rows.length?`<div class="seenContributionList">${rows.map(contributionMarkup).join('')}</div>`:`<div class="seenEmpty">Ingen registrerte bidrag her ennå i dag.</div>`}</div></section><section class="seenSection"><h2 class="seenSectionTitle">Noe annet du satte pris på?</h2><div class="seenManualCard"><p>Anerkjenn noe partneren gjorde, tok initiativ til eller måten partneren var på.</p><button type="button" class="seenPrimary" data-seen-open="manual">+ Gi anerkjennelse</button></div></section><section class="seenSection"><h2 class="seenSectionTitle">Noe annet du vil sende?</h2><div class="seenSecondaryActions">${Object.entries(CATEGORY).map(([key,item])=>`<button type="button" class="seenSecondaryAction" data-seen-open="${key}">${item.icon} ${item.title}</button>`).join('')}</div></section><section class="seenSection"><h2 class="seenSectionTitle">Siste anerkjennelse</h2>${latest?`<article class="seenLast"><span aria-hidden="true">${historyIcon(latest.type)}</span><div><p>${esc(latest.type==='task'?latest.title:latest.text)}</p><small>${esc(latest.by)} → ${esc(latest.to)} · ${dateTimeLabel(latest.at)}</small></div></article>`:'<div class="seenEmpty">Ingen anerkjennelser ennå.</div>'}<button type="button" class="seenHistoryLink" data-seen-history="1">Se historikk →</button></section>${renderSheet(s)}</div>`;
}
function sheetSuggestions(s,kind){const values=kind==='manual'?manualSuggestions(s):categorySuggestions(s,kind);return values.length?`<div class="seenChips">${values.map(value=>`<button type="button" class="seenChip" data-seen-suggestion="${esc(value)}">${esc(value)}</button>`).join('')}</div>`:''}
function renderSheet(s){
  if(!sheet)return'';
  if(sheet.kind==='task')return `<div class="seenSheetLayer" data-seen-sheet-layer><section class="seenSheet" role="dialog" aria-modal="true" aria-labelledby="seenSheetTitle"><div class="seenSheetHead"><div><div class="ey">Sett ♥</div><h2 id="seenSheetTitle">${esc(sheet.title)}</h2><p class="seenSubtitle">Legg til en melding hvis du vil. Anerkjennelsen er allerede sendt.</p></div><button type="button" class="seenSheetClose" data-seen-sheet-close aria-label="Lukk">×</button></div><label class="label" for="seenText" style="display:block;margin-top:16px">Melding · valgfritt</label><textarea id="seenText" class="seenTextarea" maxlength="250" placeholder="Takk for at du tok dette. Det hjalp skikkelig ❤️">${esc(sheet.text||'')}</textarea><button type="button" class="seenPrimary" data-seen-task-message-save style="margin-top:12px">Lagre melding</button></section></div>`;
  const manual=sheet.kind==='manual',info=CATEGORY[sheet.kind];
  return `<div class="seenSheetLayer" data-seen-sheet-layer><section class="seenSheet" role="dialog" aria-modal="true" aria-labelledby="seenSheetTitle"><div class="seenSheetHead"><div><div class="ey">Sett</div><h2 id="seenSheetTitle">${manual?'Hva satte du pris på?':esc(info.title)}</h2><p class="seenSubtitle">${manual?'Det kan være noe partneren gjorde, tok initiativ til eller måten partneren var på.':esc(info.subtitle)}</p></div><button type="button" class="seenSheetClose" data-seen-sheet-close aria-label="Lukk">×</button></div>${sheetSuggestions(s,sheet.kind)}<label class="label" for="seenText">${manual?'Jeg satte pris på at du …':'Egen tekst · valgfritt'}</label><textarea id="seenText" class="seenTextarea" maxlength="250" placeholder="${manual?'Skriv en kort anerkjennelse':'Skriv noe eget hvis du vil'}"></textarea><p class="seenHelper">${manual?'Velg et forslag eller skriv med egne ord.':'Lar du feltet stå tomt, sendes standardmeldingen.'}</p><button type="button" class="seenPrimary" data-seen-send="${sheet.kind}">${manual?'Send anerkjennelse':'Send'}</button></section></div>`;
}
function dateHeading(key){if(key===today())return'I dag';const yesterday=core()?.addDays?.(today(),-1);if(key===yesterday)return'I går';const date=new Date(`${key}T12:00:00Z`);return Number.isNaN(date.getTime())?key:new Intl.DateTimeFormat('nb-NO',{timeZone:'Europe/Oslo',day:'numeric',month:'long'}).format(date)}
function renderHistory(s){const events=(core()?.recognitionEvents?.(s)||[]).slice(0,60),groups=[];for(const item of events){let group=groups.find(entry=>entry.date===item.date);if(!group){group={date:item.date,items:[]};groups.push(group)}group.items.push(item)}return `<div class="seenPage"><div class="seenSubHead"><button type="button" class="seenBack" data-seen-back="1" aria-label="Tilbake">←</button><span class="ey">Sett</span></div><header class="seenHeader"><h1 class="seenTitle">Historikk</h1><p class="seenSubtitle">Det dere har sett og sendt til hverandre.</p></header>${groups.length?groups.map(group=>`<section class="seenHistoryGroup"><h2 class="seenHistoryDate">${esc(dateHeading(group.date))}</h2><div class="seenHistoryList">${group.items.map(item=>`<article class="seenHistoryItem"><span aria-hidden="true">${historyIcon(item.type)}</span><div><p>${esc(item.type==='task'?item.title:item.text)}</p>${item.type==='task'&&item.text!==item.title?`<p>«${esc(item.text)}»</p>`:''}<small>${item.type==='task'?`Sett av ${esc(item.by)}`:`Fra ${esc(item.by)} til ${esc(item.to)}`} · ${timeLabel(item.at)}</small></div></article>`).join('')}</div></section>`).join(''):'<div class="seenManualCard"><p>Ingen anerkjennelser ennå.</p></div>'}</div>`}
function render({resetScroll=false}={}){const s=state(),content=$('#content');if(!s||!content||s.view!=='seen')return;ensureStyles();painting=true;const scroll=resetScroll?0:content.scrollTop;content.dataset.flytOwner='seen-actions';content.innerHTML=page==='history'?renderHistory(s):renderMain(s);document.querySelectorAll('#nav button').forEach(button=>button.classList.toggle('on',button.dataset.view==='seen'));painting=false;content.scrollTop=resetScroll?0:Math.min(scroll,Math.max(0,content.scrollHeight-content.clientHeight));if(page==='main')window.FlytEdgeSwipeBack?.unbind(content);else window.FlytEdgeSwipeBack?.bind(content,{canGoBack:()=>page!=='main',onBack:openMain})}
function openMain(){page='main';sheet=null;render({resetScroll:true})}
function openSheet(kind,data={}){sheet={...data,kind};render({resetScroll:false});setTimeout(()=>$('#seenText')?.focus(),30)}
function closeSheet(){sheet=null;render({resetScroll:false})}
function sendMessage(type,text){const s=state(),to=s&&partnerName(s),value=String(text||'').trim();if(!s||!value)return false;const next=core()?.addRecognition?.(s,{type,text:value,user:s.user,to});if(!next||next===s)return false;sheet=null;save({...next,view:'seen'});render({resetScroll:false});toast(type==='recognition'||type==='personal'?'Anerkjennelse sendt ❤️':`Sendt til ${to} ❤️`);return true}
function pendingRecognitions(s){return core()?.pendingRecognitionEvents?.(s,s?.user)||[]}
function closeRecognitionAlert({pause=false}={}){document.querySelector('#seenRecognitionAlert')?.remove();recognitionAlertOpen=false;if(pause)recognitionAlertPaused=true}
function markRecognitionRead(id,{next=false,history=false}={}){const s=state();if(!s)return;const updated=core()?.markRecognitionEventSeen?.(s,id,s.user)||s;closeRecognitionAlert();if(history){page='history';save({...updated,view:'seen'});queueMicrotask(()=>render({resetScroll:true}));return}save(updated);if(next)queueMicrotask(checkRecognitionAlert)}
function checkRecognitionAlert(){const s=state();if(window.FlytSettingsUI?.enabled?.('popups.recognitions',true)===false||!s||s.view!=='home'||recognitionAlertPaused||recognitionAlertOpen||document.querySelector('#seenRecognitionAlert')||document.querySelector('[aria-modal="true"]'))return false;const pending=pendingRecognitions(s),item=pending[0];if(!item)return false;recognitionAlertOpen=true;const el=document.createElement('div');el.id='seenRecognitionAlert';el.style.cssText='position:fixed;inset:0;z-index:1300;display:grid;place-items:center;padding:24px;background:#3a211b66';el.innerHTML=`<section role="dialog" aria-modal="true" aria-label="Nytt i Sett" style="position:relative;width:min(100%,390px);padding:24px 20px 20px;border-radius:26px;background:#fffaf7;color:#452f29;text-align:center;box-shadow:0 24px 70px #3b211b55"><button type="button" data-recognition-alert-close aria-label="Lukk" style="position:absolute;right:14px;top:12px;border:0;background:#fff0e8;color:#806d65;width:38px;height:38px;border-radius:50%;font-size:26px;line-height:1">×</button><div class="ey">Nytt i Sett</div><div style="font-size:42px;line-height:1;margin:12px 0 8px" aria-hidden="true">${historyIcon(item.type)}</div><h2 style="font:500 28px/1.12 Georgia;margin:8px 0 14px">Fra ${esc(item.by)}</h2><div class="card hero" style="margin:0 0 14px"><strong style="font-size:18px;line-height:1.45">${esc(item.type==='task'?(item.text===item.title?`${item.by} så at du gjorde ${item.title}.`:item.text):item.text)}</strong></div><p class="taskmeta" style="margin:0 0 14px">${dateTimeLabel(item.at)}</p><p class="taskmeta" style="margin:0 0 14px">${pending.length>1?`1 av ${pending.length}`:'Ny melding'}</p><button type="button" class="primary full" data-recognition-alert-next>${pending.length>1?'Neste':'Ferdig'}</button><button type="button" data-recognition-alert-history style="border:0;background:transparent;color:#806d65;font-weight:800;padding:13px 8px 5px">Se historikk</button><button type="button" data-recognition-alert-close style="border:0;background:transparent;color:#806d65;font-weight:800;padding:10px 8px">Ikke nå</button></section>`;document.body.appendChild(el);return true}

document.addEventListener('click',async event=>{
  const match=selector=>event.target.closest?.(selector),stop=()=>{event.preventDefault();event.stopImmediatePropagation()};
  const alertClose=match('[data-recognition-alert-close]');if(alertClose){stop();closeRecognitionAlert({pause:true});return}
  const alertNext=match('[data-recognition-alert-next]');if(alertNext){stop();const item=pendingRecognitions(state())[0];if(item)markRecognitionRead(item.id,{next:true});else closeRecognitionAlert();return}
  const alertHistory=match('[data-recognition-alert-history]');if(alertHistory){stop();const item=pendingRecognitions(state())[0];if(item)markRecognitionRead(item.id,{history:true});else closeRecognitionAlert();return}
  const nav=match('#nav button[data-view="seen"]');if(nav){stop();const s=state();if(s){page='main';sheet=null;save({...s,view:'seen'});queueMicrotask(()=>render({resetScroll:true}))}return}
  if(state()?.view!=='seen')return;
  const ack=match('[data-seen-ack]');if(ack){stop();const s=state(),target=readRef(ack.dataset.seenAck),result=core()?.toggleAcknowledgement?.(s,{...target,user:s.user});if(!result)return;if(result.requiresConfirmation){const yes=window.FlytModal?.confirm?await window.FlytModal.confirm({ey:'Sett',title:'Fjerne anerkjennelsen?',text:'Meldingen du la til fjernes også.',ok:'Fjern'}):window.confirm?.('Fjerne anerkjennelsen og meldingen?');if(!yes)return;const confirmed=core()?.toggleAcknowledgement?.(s,{...target,user:s.user,allowTextRemoval:true});if(confirmed?.changed){save(confirmed.state);render({resetScroll:false});toast('Anerkjennelsen er fjernet')}return}if(result.changed){save(result.state);render({resetScroll:false});toast(result.action==='added'?'Sett ❤️':'Anerkjennelsen er fjernet')}return}
  const ackMessage=match('[data-seen-ack-message]');if(ackMessage){stop();const s=state(),target=readRef(ackMessage.dataset.seenAckMessage),row=(core()?.contributions?.(s,{user:s.user,date:today()})||[]).find(item=>item.kind===target.kind&&String(item.id)===String(target.id));if(row?.acknowledgement)openSheet('task',{sourceKind:target.kind,id:target.id,title:row.title,text:row.acknowledgement.text||''});return}
  const open=match('[data-seen-open]');if(open){stop();openSheet(open.dataset.seenOpen);return}
  const close=match('[data-seen-sheet-close]');if(close){stop();closeSheet();return}
  const layer=match('[data-seen-sheet-layer]');if(layer&&event.target===layer){stop();closeSheet();return}
  const suggestion=match('[data-seen-suggestion]');if(suggestion){stop();const input=$('#seenText');if(input){const raw=suggestion.dataset.seenSuggestion||suggestion.textContent||'';input.value=sheet?.kind==='manual'&&!/^Jeg /i.test(raw)?`Jeg satte pris på at du ${raw.charAt(0).toLowerCase()+raw.slice(1)}.`:raw;input.focus()}return}
  const taskMessage=match('[data-seen-task-message-save]');if(taskMessage){stop();const s=state(),value=$('#seenText')?.value||'',target={kind:sheet?.sourceKind||'completion',id:sheet?.id},result=core()?.setAcknowledgementText?.(s,{...target,user:s.user,text:value});if(result?.changed){sheet=null;save(result.state);render({resetScroll:false});toast('Meldingen er lagt til ❤️')}return}
  const send=match('[data-seen-send]');if(send){stop();const kind=send.dataset.seenSend,value=$('#seenText')?.value.trim()||(kind==='manual'?'':DEFAULTS[kind]?.[0]||'');sendMessage(kind==='manual'?'recognition':kind,value);return}
  const history=match('[data-seen-history]');if(history){stop();page='history';sheet=null;render({resetScroll:true});return}
  const back=match('[data-seen-back]');if(back){stop();openMain();return}
},true);

window.addEventListener('pageshow',()=>{recognitionAlertPaused=false;setTimeout(checkRecognitionAlert,120)});
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'){recognitionAlertPaused=false;setTimeout(checkRecognitionAlert,180)}});
window.addEventListener('focus',()=>{recognitionAlertPaused=false;setTimeout(checkRecognitionAlert,180)});
setTimeout(checkRecognitionAlert,700);setTimeout(checkRecognitionAlert,1800);
const observer=new MutationObserver(()=>{if(painting)return;const s=state(),content=$('#content');if(s?.view==='seen'&&content?.dataset.flytOwner!=='seen-actions')queueMicrotask(render)});let observed=false,tries=0;const timer=setInterval(()=>{const content=$('#content');if(content&&!observed){observer.observe(content,{childList:true,subtree:true});observed=true}const s=state();if(s?.view==='seen'&&content?.dataset.flytOwner!=='seen-actions')render();if(observed&&++tries>80)clearInterval(timer)},100);
window.FlytSeenRecognitionAlert={check:checkRecognitionAlert};
window.FlytSeenUI={render,openCategory(category){if(category==='recognition')openSheet('manual');else if(CATEGORY[category])openSheet(category)},version:VERSION};
})();
