(()=>{
'use strict';
const VERSION='20260926-due-soon-settings3';
const DEFAULTS=Object.freeze({
  popups:{dailyCheckin:true,recognitions:true,challenges:true,tips:true},
  home:{dailyStatus:true,challenges:true,overview:true},
  seen:{suggestions:true},
  summaries:{daily:false,weekly:true},
  rewards:{showChallenges:true}
});
const $=s=>document.querySelector(s);
const bridge=()=>window.FlytBridge;
function clone(value){return JSON.parse(JSON.stringify(value))}
function deepMerge(base,over={}){const out=clone(base);Object.entries(over||{}).forEach(([key,value])=>{out[key]=value&&typeof value==='object'&&!Array.isArray(value)?deepMerge(out[key]||{},value):value});return out}
function identity(s=bridge()?.getState?.()){return String(window.FlytSync?.getContext?.()?.user_id||s?.user||'meg')}
function personal(s=bridge()?.getState?.()){return deepMerge(DEFAULTS,s?.appPreferences?.personal?.[identity(s)]||{})}
function savePersonal(next){const s=bridge()?.getState?.();if(!s)return;const appPreferences={...(s.appPreferences||{}),personal:{...(s.appPreferences?.personal||{}),[identity(s)]:deepMerge(DEFAULTS,next)}};bridge()?.setState?.({...s,appPreferences});window.FlytSync?.queueSave?.();applyHome();}
function enabled(path,fallback=true){let value=personal();for(const key of String(path).split('.'))value=value?.[key];return typeof value==='boolean'?value:fallback}
function setValue(path,value){const next=personal(),parts=String(path).split('.');let node=next;parts.slice(0,-1).forEach(key=>node=node[key]||(node[key]={}));node[parts.at(-1)]=value;savePersonal(next)}
function partnerName(s){const members=window.FlytSync?.getContext?.()?.members||[],other=members.find(member=>String(member.id)!==String(window.FlytSync?.getContext?.()?.user_id));return other?.display_name||Object.keys(s?.points||{}).find(name=>name!==s?.user)||'Ikke koblet til'}
function esc(value){return String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]))}
const DUE_SOON_CATEGORY_ORDER=['Barn','Kjøkken','Klesvask','Renhold','Stue & fellesområder','Bad','Soverom','Dyr','Hage & ute','Bil','Planlegging & admin','Egendefinert'];
function dueSoonPrefs(s=bridge()?.getState?.()){const raw=s?.appPreferences?.household?.dueSoon||{};return{enabled:raw.enabled!==false,taskOverrides:raw.taskOverrides&&typeof raw.taskOverrides==='object'?{...raw.taskOverrides}:{}}}
function dueSoonDefault(task){if(task?.showInDueSoon===true)return true;if(task?.showInDueSoon===false)return false;const base=(window.FlytTaskLanguage?.catalog||[]).find(item=>String(item?.id)===String(task?.id));return base?.showInDueSoon===true}
function dueSoonTaskOn(task,s=bridge()?.getState?.()){const prefs=dueSoonPrefs(s),value=prefs.taskOverrides[String(task?.id||'')];return typeof value==='boolean'?value:dueSoonDefault(task)}
function dueSoonActiveTasks(s=bridge()?.getState?.()){return(s?.tasks||[]).filter(task=>task&&(task.type==='flex'||task.type==='period')).sort((a,b)=>{const ai=DUE_SOON_CATEGORY_ORDER.indexOf(String(a.cat||'Egendefinert')),bi=DUE_SOON_CATEGORY_ORDER.indexOf(String(b.cat||'Egendefinert'));return(ai<0?999:ai)-(bi<0?999:bi)||String(a.name||'').localeCompare(String(b.name||''),'nb')})}
function saveDueSoonPrefs(patch){const s=bridge()?.getState?.();if(!s)return;const current=dueSoonPrefs(s),household={...(s.appPreferences?.household||{}),dueSoon:{...current,...patch}};bridge()?.setState?.({...s,appPreferences:{...(s.appPreferences||{}),household}});window.FlytSync?.queueSave?.();if(s.view==='tasks')window.FlytRecurrenceUI?.render?.({resetScroll:false})}
function ensureDueSoonSettingsStyles(){if($('#flytDueSoonSettingsStyles'))return;const style=document.createElement('style');style.id='flytDueSoonSettingsStyles';style.textContent='.flytDueSoonSettingsLayer{z-index:1810}.flytDueSoonIntro{margin:8px 4px 14px}.flytDueSoonGroup{margin:12px 0;border:1px solid #eadbd2;border-radius:15px;background:#fffdf9;overflow:hidden}.flytDueSoonGroup h3{margin:0;padding:10px 12px 7px;color:#9a553f;font-size:12px;letter-spacing:.08em;text-transform:uppercase}.flytDueSoonGroup .flytSettingsToggle{padding:12px}.flytDueSoonGroup .flytSettingsToggle:first-of-type{border-top:0}';document.head.appendChild(style)}
function dueSoonMasterMarkup(){const on=dueSoonPrefs().enabled;return '<button type="button" class="flytSettingsToggle" data-settings-due-soon-master aria-pressed="'+String(on)+'"><span><strong>Vis «På tide» i Gjøre</strong><small>Vis relevante faste gjøremål i Dag-visningen.</small></span><i class="'+(on?'on':'')+'" aria-hidden="true"><b></b></i></button>'}
function dueSoonSettingsMarkup(){const s=bridge()?.getState?.()||{},groups=new Map();dueSoonActiveTasks(s).forEach(task=>{const cat=String(task.cat||'Egendefinert');if(!groups.has(cat))groups.set(cat,[]);groups.get(cat).push(task)});const rows=[...groups.entries()].map(([cat,tasks])=>'<div class="flytDueSoonGroup"><h3>'+esc(cat)+'</h3>'+tasks.map(task=>{const on=dueSoonTaskOn(task,s),sub=task.type==='period'?'Månedlig/periodebundet':'Fleksibelt ukegjøremål';return '<button type="button" class="flytSettingsToggle" data-settings-due-soon-task="'+esc(task.id)+'" aria-pressed="'+String(on)+'"><span><strong>'+esc(task.name)+'</strong><small>'+sub+'</small></span><i class="'+(on?'on':'')+'" aria-hidden="true"><b></b></i></button>'}).join('')+'</div>').join('');return '<div id="flytDueSoonSettings" class="flytSettingsLayer flytDueSoonSettingsLayer" role="presentation"><section class="flytSettingsPanel" role="dialog" aria-modal="true" aria-labelledby="flytDueSoonTitle"><header><div><div class="ey">GJØRE</div><h2 id="flytDueSoonTitle">På tide</h2><p>Velg hvilke av deres aktive gjøremål som kan foreslås når de begynner å bli aktuelle.</p></div><button type="button" class="flytSettingsClose" data-settings-due-soon-back>Tilbake</button></header><div class="flytSettingsScroll">'+dueSoonMasterMarkup()+'<p class="flytSettingsHint flytDueSoonIntro">Valgene gjelder husholdningen. Å slå av På tide endrer ikke oppgaver, poeng eller historikk.</p>'+(rows||'<p class="flytSettingsHint">Ingen aktive fleksible eller månedlige gjøremål å velge mellom.</p>')+'<button type="button" class="flytSettingsRestore" data-settings-due-soon-reset>Tilbakestill til anbefalte valg</button></div></section></div>'}
function openDueSoonSettings(){ensureDueSoonSettingsStyles();$('#flytDueSoonSettings')?.remove();document.body.insertAdjacentHTML('beforeend',dueSoonSettingsMarkup())}
function refreshDueSoonToggleValues(){const master=$('[data-settings-due-soon-master]');if(master)paintToggle(master,dueSoonPrefs().enabled);const tasks=new Map(dueSoonActiveTasks().map(task=>[String(task.id),task]));document.querySelectorAll('[data-settings-due-soon-task]').forEach(button=>{const task=tasks.get(String(button.dataset.settingsDueSoonTask||''));if(task)paintToggle(button,dueSoonTaskOn(task))})}

function toggle(path,label,description){const on=enabled(path);return `<button type="button" class="flytSettingsToggle" data-settings-toggle="${path}" aria-pressed="${on}"><span><strong>${esc(label)}</strong><small>${esc(description)}</small></span><i class="${on?'on':''}" aria-hidden="true"><b></b></i></button>`}
function pointsEnabled(state=bridge()?.getState?.()){return state?.appPreferences?.household?.pointsEnabled!==false}
function pointsToggle(){return''}
function setPointsEnabled(on){const state=bridge()?.getState?.();if(!state)return;const household={...(state.appPreferences?.household||{}),pointsEnabled:on};let rewards=[...(state.rewards||[])],backup=state.appPreferences?.household?.pointBackup||[];if(!on){backup=rewards.map(item=>({id:item.id,requiresPoints:!!item.requiresPoints,cost:item.cost}));rewards=rewards.map(item=>({...item,requiresPoints:false}));household.pointBackup=backup}else{const before=new Map(backup.map(item=>[String(item.id),item]));rewards=rewards.map(item=>{const saved=before.get(String(item.id));return saved?{...item,requiresPoints:saved.requiresPoints,cost:saved.cost}:item});delete household.pointBackup}bridge()?.setState?.({...state,rewards,appPreferences:{...(state.appPreferences||{}),household}});window.FlytSync?.queueSave?.();bridge()?.toast?.(on?'Poengsystemet er på':'Belønninger er åpne uten poeng')}
function section(title,body,open=false){return `<details class="flytSettingsSection" ${open?'open':''}><summary><span>${esc(title)}</span><b>⌄</b></summary><div class="flytSettingsSectionBody">${body}</div></details>`}
function markup(){const s=bridge()?.getState?.()||{},who=esc(s.user||'Deg'),partner=esc(partnerName(s));return `<div id="flytSettings" class="flytSettingsLayer" role="presentation"><section class="flytSettingsPanel" role="dialog" aria-modal="true" aria-labelledby="flytSettingsTitle"><header><div><div class="ey">HVERDAGSOSS</div><h2 id="flytSettingsTitle">Innstillinger</h2><p>Tilpass hvordan appen møter deg – uten å gjøre hverdagen mer komplisert.</p></div><button type="button" class="flytSettingsClose" data-settings-close aria-label="Lukk innstillinger">Lukk</button></header><div class="flytSettingsScroll">
${section('Konto og partner',`<div class="flytSettingsInfo"><strong>${who}</strong><span>Partner: ${partner}</span></div><button type="button" class="flytSettingsLink" data-settings-sync>Koble til eller administrer partner <b>›</b></button><button type="button" class="flytSettingsLink" data-settings-feedback>Tilbakemelding <b>›</b></button>`,true)}
${section('Popup og påminnelser',`${toggle('popups.dailyCheckin','Daglig dagsform-popup','Spør én gang om dagen når dagsform ikke er registrert.')} ${toggle('popups.recognitions','Nye anerkjennelser','Vis uleste meldinger fra Sett ved åpning.')} ${toggle('popups.challenges','Nye utfordringer','Vis varsling når en partnerutfordring er klar.')} ${toggle('popups.tips','Tips og påminnelser','Vis relevante, forsiktige nudger på Hjem.')}<button type="button" class="flytSettingsRestore" data-settings-restore>Gjenopprett anbefalte innstillinger</button>`)}
${section('Hjem',`${toggle('home.dailyStatus','Dagsform','Vis dagsformkortet på Hjem.')} ${toggle('home.challenges','Utfordringer','Vis utfordringer på Hjem.')} ${toggle('home.overview','Dagens oversikt','Vis fremdrift og oversikt over dagens gjøremål.')}`)}
${section('Gjøre',`<p class="flytSettingsHint">Oppgaver, kategorier, rytme, poeng og rekkefølge styres samlet for husholdningen.</p><button type="button" class="flytSettingsLink" data-settings-task-setup><span><strong>Rediger oppsett</strong><small>Aktive kategorier, gjøremål, frekvens, dager, poeng og standardrekkefølge.</small></span><b>›</b></button><button type="button" class="flytSettingsLink" data-settings-due-soon><span><strong>På tide</strong><small>Vis eller skjul På tide, og velg hvilke gjøremål som kan foreslås.</small></span><b>›</b></button>`)}
${section('Oppsummeringer',`${toggle('summaries.weekly','Ukesoppsummering','Vis én popup første gang du åpner appen etter at uka er avsluttet.')} ${toggle('summaries.daily','Dagsoppsummering som popup','Vis gårsdagens oppsummering automatisk ved neste åpning.')}`)}
${section('Sett',`${toggle('seen.suggestions','Forslag til anerkjennelse','Vis forslag når du vil sende noe fint.')}<button type="button" class="flytSettingsLink" data-settings-seen-suggestions>Mine personlige forslag <b>›</b></button><button type="button" class="flytSettingsLink" data-settings-history>Historikk i Sett <b>›</b></button>`)}
${section('Mål og belønning',`${pointsToggle(s)}${toggle('rewards.showChallenges','Vis utfordringer på Hjem','La utfordringer være en del av dagens oversikt.')}<button type="button" class="flytSettingsLink" data-settings-rewards>Administrer egne belønninger <b>›</b></button><p class="flytSettingsHint">Poeng viser innsats og fremdrift. De brukes ikke opp. Dine popup- og Hjem-valg er personlige.</p>`)}
${section('Historikk og data',`<button type="button" class="flytSettingsLink" data-settings-history>Se historikk og egne forslag <b>›</b></button><p class="flytSettingsHint">Innstillingene endrer ikke oppgaver, poeng, meldinger eller historikk.</p>`)}
${section('Om HverdagsOss',`<p class="flytSettingsHint">HverdagsOss skal gjøre det enklere å se, fordele og verdsette hverdagen sammen.</p><div class="flytSettingsVersion">Versjon ${VERSION}</div>`)}<div class="flytSettingsLogout"><button type="button" data-settings-logout>Logg ut</button></div>
</div></section></div>`}
let setupReturnPending=false,subpageReturnPending=false;
function open(){const existing=$('#flytSettings');if(existing){existing.classList.remove('hidden');existing.setAttribute('aria-hidden','false');return}setupReturnPending=false;subpageReturnPending=false;$('#flytAppMenu')?.remove();document.body.insertAdjacentHTML('beforeend',markup())}
function back(){close()}
function suspendForSetup(){const panel=$('#flytSettings');if(!panel)return false;setupReturnPending=true;panel.classList.add('hidden');panel.setAttribute('aria-hidden','true');return true}
function resumeFromSetup(){if(!setupReturnPending)return false;const panel=$('#flytSettings');if(!panel)return false;setupReturnPending=false;panel.classList.remove('hidden');panel.setAttribute('aria-hidden','false');return true}
function suspendForSubpage(){const panel=$('#flytSettings');if(!panel)return false;subpageReturnPending=true;panel.classList.add('hidden');panel.setAttribute('aria-hidden','true');return true}
function resumeFromSubpage(){if(!subpageReturnPending)return false;const panel=$('#flytSettings');if(!panel)return false;subpageReturnPending=false;panel.classList.remove('hidden');panel.setAttribute('aria-hidden','false');return true}
function hasSetupReturn(){return setupReturnPending}
function addMenuEntry(){const menu=$('#flytAppMenu'),list=menu?.querySelector('.flytMenuSheet>div[style]');if(!menu||!list||list.querySelector('[data-settings-open]'))return;const button=document.createElement('button');button.type='button';button.className='secondary flytMenuAction';button.dataset.settingsOpen='1';button.innerHTML='<span class="flytMenuIcon">⚙</span><span><strong>Innstillinger</strong><span class="taskmeta" style="display:block">Popup, Hjem, Gjøre, Sett og belønninger</span></span>';const account=list.querySelector('[data-flyt-menu="account"]');if(account)list.insertBefore(button,account);else list.appendChild(button)}
function close(){setupReturnPending=false;subpageReturnPending=false;$('#flytDueSoonSettings')?.remove();$('#flytSettings')?.remove()}
function applyHome(){const s=bridge()?.getState?.(),content=$('#content');if(!s||s.view!=='home'||!content)return;const visibility=[['[data-home-status-card]','home.dailyStatus'],['.homeChallengeCard','home.challenges'],['.homeGoalCard','home.overview']];visibility.forEach(([selector,path])=>content.querySelectorAll(selector).forEach(el=>el.hidden=!enabled(path)));const nudge=$('#homeNudgeMount');if(nudge)nudge.hidden=!enabled('popups.tips')}
function restore(){const s=bridge()?.getState?.();savePersonal(DEFAULTS);['enabled','initiative','askHelp','relationship','recognition'].forEach(key=>window.FlytNudgeUI?.updatePreference?.(key,true));window.FlytNudgeUI?.updatePreference?.('frequency','balanced');window.FlytNudgeUI?.updatePreference?.('tone','warm');bridge()?.toast?.('Anbefalte innstillinger er gjenopprettet');if(s)applyHome();refreshToggleValues()}
function route(action){const s=bridge()?.getState?.();if(action==='history'||action==='seen-suggestions'){if(!suspendForSubpage())return;if(action==='history')window.FlytHistoryUI?.openHistory?.();else window.FlytHistoryUI?.openSeenSuggestions?.();return}if(action==='task-setup'){if(!suspendForSetup())return;if(!window.FlytSetupV2?.open?.(1))resumeFromSetup();return}close();if(action==='sync'){$('#syncBtn')?.click();return}if(action==='feedback'){window.FlytBetaUI?.open?.();return}if(action==='logout'){$('#lock')?.click();return}if(action==='rewards'){if(!s)return;bridge()?.setState?.({...s,view:'rewards'});return}}
function ensureStyles(){if($('#flytSettingsStyles'))return;const style=document.createElement('style');style.id='flytSettingsStyles';style.textContent=`
#flytAppMenu [data-flyt-menu="connection"],#flytAppMenu [data-flyt-menu="setup"],#flytAppMenu [data-flyt-menu="account"]{display:none!important}.top>div>#syncBtn{display:none!important}
.flytSettingsLogout{margin:18px 2px 5px;padding-top:14px;border-top:1px solid #eadbd2}.flytSettingsLogout button{width:100%;min-height:44px;border:1px solid #d98761;border-radius:13px;background:#fff7f1;color:#a14b37;font-weight:850}
.flytSettingsLayer{position:fixed;inset:0;z-index:1800;display:flex;align-items:flex-end;background:#3a211b77;backdrop-filter:blur(4px);-webkit-backdrop-filter:blur(4px)}.flytSettingsPanel{width:min(100%,540px);max-height:92dvh;margin:auto 0 0;padding:15px 14px max(18px,env(safe-area-inset-bottom));overflow:hidden;border-radius:26px 26px 0 0;background:#fffaf7;color:#452f29;box-shadow:0 -20px 60px #3b211b33}.flytSettingsPanel header{display:flex;align-items:flex-start;justify-content:space-between;gap:12px;padding:3px 5px 14px}.flytSettingsPanel h2{margin:4px 0 3px;font:600 28px/1.1 Georgia,serif}.flytSettingsPanel header p{max-width:390px;margin:0;color:#806b61;font-size:13px;line-height:1.35}.flytSettingsPanel header>button{width:39px;height:39px;border:1px solid #eadbd2;border-radius:50%;background:#fff;color:#9a553f;font-size:26px;line-height:1}.flytSettingsPanel header>button.flytSettingsClose{width:auto;height:39px;padding:0 13px;border-radius:999px;font-size:14px;font-weight:800}.flytSettingsScroll{max-height:calc(92dvh - 120px);overflow:auto;padding:0 2px 8px}.flytSettingsSection{margin:8px 0;border:1px solid #eadbd2;border-radius:17px;background:#fffdf9;overflow:hidden}.flytSettingsSection summary{display:flex;justify-content:space-between;align-items:center;padding:14px 13px;cursor:pointer;font-weight:800;list-style:none}.flytSettingsSection summary::-webkit-details-marker{display:none}.flytSettingsSection summary>b{font-size:19px;color:#ad5c45;transition:transform .16s}.flytSettingsSection[open] summary>b{transform:rotate(180deg)}.flytSettingsSectionBody{padding:0 10px 11px}.flytSettingsToggle,.flytSettingsLink{width:100%;display:flex;align-items:center;justify-content:space-between;gap:12px;padding:12px 4px;border:0;border-top:1px solid #f1e3dc;background:transparent;text-align:left}.flytSettingsToggle:first-child,.flytSettingsLink:first-child{border-top:0}.flytSettingsToggle span{display:grid;gap:3px}.flytSettingsToggle strong{font-size:14px}.flytSettingsToggle small,.flytSettingsHint{color:#806b61;font-size:12px;line-height:1.35}.flytSettingsToggle i{width:42px;height:25px;flex:0 0 42px;padding:3px;border-radius:999px;background:#e9ddd7;transition:.16s}.flytSettingsToggle i.on{background:#d77b52}.flytSettingsToggle i b{display:block;width:19px;height:19px;border-radius:50%;background:white;box-shadow:0 1px 3px #4322;transition:.16s}.flytSettingsToggle i.on b{transform:translateX(17px)}.flytSettingsLink{font-weight:750;color:#573a31}.flytSettingsLink b{font-size:23px;color:#b06046}.flytSettingsInfo{display:flex;justify-content:space-between;gap:8px;padding:8px 4px 12px;color:#806b61;font-size:13px}.flytSettingsInfo strong{color:#452f29}.flytSettingsRestore{width:100%;margin-top:10px;padding:10px;border:1px solid #df9a79;border-radius:12px;background:#fff7f1;color:#a8543e;font-weight:800}.flytSettingsVersion{margin:4px;color:#a08b80;font-size:11px}` ;document.head.appendChild(style)}
document.addEventListener('click',event=>{const target=event.target.closest?.('[data-settings-due-soon],[data-settings-due-soon-back],[data-settings-due-soon-master],[data-settings-due-soon-task],[data-settings-due-soon-reset]');if(!target)return;event.preventDefault();event.stopImmediatePropagation();if(target.matches('[data-settings-due-soon]')){openDueSoonSettings();return}if(target.matches('[data-settings-due-soon-back]')){$('#flytDueSoonSettings')?.remove();return}if(target.matches('[data-settings-due-soon-master]')){const on=!dueSoonPrefs().enabled;saveDueSoonPrefs({enabled:on});paintToggle(target,on);return}if(target.matches('[data-settings-due-soon-task]')){const id=String(target.dataset.settingsDueSoonTask||''),task=dueSoonActiveTasks().find(item=>String(item.id)===id);if(!task)return;const on=!dueSoonTaskOn(task),prefs=dueSoonPrefs(),taskOverrides={...prefs.taskOverrides,[id]:on};saveDueSoonPrefs({taskOverrides});paintToggle(target,on);return}if(target.matches('[data-settings-due-soon-reset]')){saveDueSoonPrefs({taskOverrides:{}});refreshDueSoonToggleValues();bridge()?.toast?.('På tide er tilbakestilt til anbefalte valg');return}},true);
document.addEventListener('click',event=>{const target=event.target.closest?.('[data-settings-open],#flytMoreBtn,[data-settings-close],[data-settings-back],[data-settings-toggle],[data-settings-points-toggle],[data-settings-restore],[data-settings-sync],[data-settings-feedback],[data-settings-logout],[data-settings-task-setup],[data-settings-rewards],[data-settings-history],[data-settings-seen-suggestions]');if(!target)return;if(target.matches('[data-settings-open],#flytMoreBtn')){event.preventDefault();event.stopImmediatePropagation();open();return}if(target.matches('[data-settings-close]')){event.preventDefault();close();return}if(target.matches('[data-settings-back]')){event.preventDefault();back();return}if(target.matches('[data-settings-toggle]')){event.preventDefault();const path=target.dataset.settingsToggle,on=!enabled(path);setValue(path,on);paintToggle(target,on);return}if(target.matches('[data-settings-points-toggle]')){event.preventDefault();const on=!pointsEnabled();setPointsEnabled(on);paintToggle(target,on);return}if(target.matches('[data-settings-restore]')){event.preventDefault();restore();return}event.preventDefault();const action=target.matches('[data-settings-sync]')?'sync':target.matches('[data-settings-feedback]')?'feedback':target.matches('[data-settings-logout]')?'logout':target.matches('[data-settings-task-setup]')?'task-setup':target.matches('[data-settings-rewards]')?'rewards':target.matches('[data-settings-history]')?'history':'seen-suggestions';route(action)},true);
function paintToggle(button,on){button.setAttribute('aria-pressed',String(on));button.querySelector('i')?.classList.toggle('on',on)}
function refreshToggleValues(){document.querySelectorAll('[data-settings-toggle]').forEach(button=>paintToggle(button,enabled(button.dataset.settingsToggle)));document.querySelectorAll('[data-settings-points-toggle]').forEach(button=>paintToggle(button,pointsEnabled()))}
function decorateGear(){const button=$('#flytMoreBtn');if(!button)return;if(button.textContent!=='⚙')button.textContent='⚙';if(button.getAttribute('aria-label')!=='Innstillinger')button.setAttribute('aria-label','Innstillinger');if(button.getAttribute('aria-haspopup')!=='dialog')button.setAttribute('aria-haspopup','dialog')}
function install(){ensureStyles();const button=$('#setupBtn');if(button){button.textContent='Innstillinger';button.setAttribute('aria-label','Åpne innstillinger');button.onclick=event=>{event.preventDefault();open()}}const content=$('#content');if(content)new MutationObserver(()=>queueMicrotask(applyHome)).observe(content,{childList:true,subtree:true});new MutationObserver(()=>queueMicrotask(()=>{addMenuEntry();decorateGear()})).observe(document.body,{childList:true,subtree:true});addMenuEntry();decorateGear();applyHome()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
window.addEventListener('pageshow',()=>{install();applyHome()});
window.addEventListener('flyt:setup:closed',resumeFromSetup);window.FlytSettingsUI={version:VERSION,open,close,back,enabled,personal,applyHome,hasSetupReturn,resumeFromSubpage};
})();
