(()=>{
'use strict';
const VERSION='20260913-settings4';
const DEFAULTS=Object.freeze({
  popups:{dailyCheckin:true,recognitions:true,challenges:true,tips:true},
  home:{dailyStatus:true,challenges:true,overview:true},
  seen:{suggestions:true},
  rewards:{showChallenges:true}
});
const $=s=>document.querySelector(s);
const bridge=()=>window.FlytBridge;
function clone(value){return JSON.parse(JSON.stringify(value))}
function deepMerge(base,over={}){const out=clone(base);Object.entries(over||{}).forEach(([key,value])=>{out[key]=value&&typeof value==='object'&&!Array.isArray(value)?deepMerge(out[key]||{},value):value});return out}
function identity(s=bridge()?.getState?.()){return String(window.FlytSync?.getContext?.()?.user_id||s?.user||'meg')}
function personal(s=bridge()?.getState?.()){return deepMerge(DEFAULTS,s?.appPreferences?.personal?.[identity(s)]||{})}
function savePersonal(next){const s=bridge()?.getState?.();if(!s)return;const appPreferences={...(s.appPreferences||{}),personal:{...(s.appPreferences?.personal||{}),[identity(s)]:deepMerge(DEFAULTS,next)}};bridge()?.setState?.({...s,appPreferences});window.FlytSync?.queueSave?.();applyHome();}
function enabled(path,fallback=true){let value=personal();for(const key of String(path).split('.'))value=value?.[key];return typeof value==='boolean'?value:fallback}
function setValue(path,value){const next=personal(),parts=String(path).split('.');let node=next;parts.slice(0,-1).forEach(key=>node=node[key]||(node[key]={}));node[parts.at(-1)]=value;savePersonal(next)}
function partnerName(s){const members=window.FlytSync?.getContext?.()?.members||[],other=members.find(member=>String(member.id)!==String(window.FlytSync?.getContext?.()?.user_id));return other?.display_name||Object.keys(s?.points||{}).find(name=>name!==s?.user)||'Ikke koblet til'}
function esc(value){return String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]))}
function toggle(path,label,description){const on=enabled(path);return `<button type="button" class="flytSettingsToggle" data-settings-toggle="${path}" aria-pressed="${on}"><span><strong>${esc(label)}</strong><small>${esc(description)}</small></span><i class="${on?'on':''}" aria-hidden="true"><b></b></i></button>`}
function pointsEnabled(state=bridge()?.getState?.()){return state?.appPreferences?.household?.pointsEnabled!==false}
function pointsToggle(state){const on=pointsEnabled(state);return `<button type="button" class="flytSettingsToggle" data-settings-points-toggle aria-pressed="${on}"><span><strong>Bruk poengsystem</strong><small>Poengkrav gjelder belønninger for begge i husholdningen.</small></span><i class="${on?'on':''}" aria-hidden="true"><b></b></i></button>`}
function setPointsEnabled(on){const state=bridge()?.getState?.();if(!state)return;const household={...(state.appPreferences?.household||{}),pointsEnabled:on};let rewards=[...(state.rewards||[])],backup=state.appPreferences?.household?.pointBackup||[];if(!on){backup=rewards.map(item=>({id:item.id,requiresPoints:!!item.requiresPoints,cost:item.cost}));rewards=rewards.map(item=>({...item,requiresPoints:false}));household.pointBackup=backup}else{const before=new Map(backup.map(item=>[String(item.id),item]));rewards=rewards.map(item=>{const saved=before.get(String(item.id));return saved?{...item,requiresPoints:saved.requiresPoints,cost:saved.cost}:item});delete household.pointBackup}bridge()?.setState?.({...state,rewards,appPreferences:{...(state.appPreferences||{}),household}});window.FlytSync?.queueSave?.();bridge()?.toast?.(on?'Poengsystemet er på':'Belønninger er åpne uten poeng')}
function section(title,body,open=false){return `<details class="flytSettingsSection" ${open?'open':''}><summary><span>${esc(title)}</span><b>⌄</b></summary><div class="flytSettingsSectionBody">${body}</div></details>`}
function markup(){const s=bridge()?.getState?.()||{},who=esc(s.user||'Deg'),partner=esc(partnerName(s));return `<div id="flytSettings" class="flytSettingsLayer" role="presentation"><section class="flytSettingsPanel" role="dialog" aria-modal="true" aria-labelledby="flytSettingsTitle"><header><div><div class="ey">HVERDAGSOSS</div><h2 id="flytSettingsTitle">Innstillinger</h2><p>Tilpass hvordan appen møter deg – uten å gjøre hverdagen mer komplisert.</p></div><button type="button" data-settings-close aria-label="Lukk innstillinger">×</button></header><div class="flytSettingsScroll">
${section('Konto og partner',`<div class="flytSettingsInfo"><strong>${who}</strong><span>Partner: ${partner}</span></div><button type="button" class="flytSettingsLink" data-settings-sync>Koble til eller administrer partner <b>›</b></button>`,true)}
${section('Popup og påminnelser',`${toggle('popups.dailyCheckin','Daglig dagsform-popup','Spør én gang om dagen når dagsform ikke er registrert.')} ${toggle('popups.recognitions','Nye anerkjennelser','Vis uleste meldinger fra Sett ved åpning.')} ${toggle('popups.challenges','Nye utfordringer','Vis varsling når en partnerutfordring er klar.')} ${toggle('popups.tips','Tips og påminnelser','Vis relevante, forsiktige nudger på Hjem.')}<button type="button" class="flytSettingsRestore" data-settings-restore>Gjenopprett anbefalte innstillinger</button>`)}
${section('Hjem',`${toggle('home.dailyStatus','Dagsform','Vis dagsformkortet på Hjem.')} ${toggle('home.challenges','Utfordringer','Vis utfordringer på Hjem.')} ${toggle('home.overview','Dagens oversikt','Vis fremdrift og oversikt over dagens gjøremål.')}`)}
${section('Gjøre',`<p class="flytSettingsHint">Oppgaver, kategorier og poeng styres samlet, slik at dere fortsatt ser samme husholdning.</p><button type="button" class="flytSettingsLink" data-settings-task-setup>Aktive kategorier og egne gjøremål <b>›</b></button><button type="button" class="flytSettingsLink" data-settings-task-setup>Frekvens, dager og poeng <b>›</b></button><button type="button" class="flytSettingsLink" data-settings-task-order>Standardrekkefølge <b>›</b></button>`)}
${section('Sett',`${toggle('seen.suggestions','Forslag til anerkjennelse','Vis forslag når du vil sende noe fint.')}<button type="button" class="flytSettingsLink" data-settings-seen-suggestions>Mine personlige forslag <b>›</b></button><button type="button" class="flytSettingsLink" data-settings-history>Historikk i Sett <b>›</b></button>`)}
${section('Mål og belønning',`${pointsToggle(s)}${toggle('rewards.showChallenges','Vis utfordringer på Hjem','La utfordringer være en del av dagens oversikt.')}<button type="button" class="flytSettingsLink" data-settings-rewards>Administrer egne belønninger <b>›</b></button><p class="flytSettingsHint">Poengsystemet er felles for husholdningen. Dine popup- og Hjem-valg er personlige.</p>`)}
${section('Historikk og data',`<button type="button" class="flytSettingsLink" data-settings-history>Se historikk og egne forslag <b>›</b></button><p class="flytSettingsHint">Innstillingene endrer ikke oppgaver, poeng, meldinger eller historikk.</p>`)}
${section('Om HverdagsOss',`<p class="flytSettingsHint">HverdagsOss skal gjøre det enklere å se, fordele og verdsette hverdagen sammen.</p><div class="flytSettingsVersion">Versjon ${VERSION}</div>`)}
</div></section></div>`}
function open(){if($('#flytSettings'))return;$('#flytAppMenu')?.remove();document.body.insertAdjacentHTML('beforeend',markup())}
function addMenuEntry(){const menu=$('#flytAppMenu'),list=menu?.querySelector('.flytMenuSheet>div[style]');if(!menu||!list||list.querySelector('[data-settings-open]'))return;const button=document.createElement('button');button.type='button';button.className='secondary flytMenuAction';button.dataset.settingsOpen='1';button.innerHTML='<span class="flytMenuIcon">⚙</span><span><strong>Innstillinger</strong><span class="taskmeta" style="display:block">Popup, Hjem, Gjøre, Sett og belønninger</span></span>';const account=list.querySelector('[data-flyt-menu="account"]');if(account)list.insertBefore(button,account);else list.appendChild(button)}
function close(){ $('#flytSettings')?.remove() }
function applyHome(){const s=bridge()?.getState?.(),content=$('#content');if(!s||s.view!=='home'||!content)return;const visibility=[['[data-home-status-card]','home.dailyStatus'],['.homeChallengeCard','home.challenges'],['.homeGoalCard','home.overview']];visibility.forEach(([selector,path])=>content.querySelectorAll(selector).forEach(el=>el.hidden=!enabled(path)));const nudge=$('#homeNudgeMount');if(nudge)nudge.hidden=!enabled('popups.tips')}
function restore(){const s=bridge()?.getState?.();savePersonal(DEFAULTS);['enabled','initiative','askHelp','relationship','recognition'].forEach(key=>window.FlytNudgeUI?.updatePreference?.(key,true));window.FlytNudgeUI?.updatePreference?.('frequency','balanced');window.FlytNudgeUI?.updatePreference?.('tone','warm');bridge()?.toast?.('Anbefalte innstillinger er gjenopprettet');if(s)applyHome();open()}
function route(action){close();const s=bridge()?.getState?.();if(action==='sync'){$('#syncBtn')?.click();return}if(action==='task-setup'){window.FlytSetupV2?.open?.(1);return}if(action==='task-order'){if(!s)return;bridge()?.setState?.({...s,view:'tasks'});queueMicrotask(()=>window.FlytRecurrenceUI?.openToday?.('all')||window.FlytRecurrenceUI?.render?.({resetScroll:true}));return}if(action==='rewards'){if(!s)return;bridge()?.setState?.({...s,view:'rewards'});queueMicrotask(()=>window.FlytRewardsUI?.render?.());return}if(action==='history'){window.FlytHistoryUI?.openHistory?.();return}if(action==='seen-suggestions'){window.FlytHistoryUI?.openSeenSuggestions?.();return}}
function ensureStyles(){if($('#flytSettingsStyles'))return;const style=document.createElement('style');style.id='flytSettingsStyles';style.textContent=`
#flytAppMenu [data-flyt-menu="connection"],#flytAppMenu [data-flyt-menu="setup"],#flytAppMenu [data-flyt-menu="account"]{display:none!important}.top>div>#syncBtn{display:none!important}
.flytSettingsLayer{position:fixed;inset:0;z-index:1800;display:flex;align-items:flex-end;background:#3a211b77;backdrop-filter:blur(4px);-webkit-backdrop-filter:blur(4px)}.flytSettingsPanel{width:min(100%,540px);max-height:92dvh;margin:auto 0 0;padding:15px 14px max(18px,env(safe-area-inset-bottom));overflow:hidden;border-radius:26px 26px 0 0;background:#fffaf7;color:#452f29;box-shadow:0 -20px 60px #3b211b33}.flytSettingsPanel header{display:flex;align-items:flex-start;justify-content:space-between;gap:12px;padding:3px 5px 14px}.flytSettingsPanel h2{margin:4px 0 3px;font:600 28px/1.1 Georgia,serif}.flytSettingsPanel header p{max-width:390px;margin:0;color:#806b61;font-size:13px;line-height:1.35}.flytSettingsPanel header>button{width:39px;height:39px;border:1px solid #eadbd2;border-radius:50%;background:#fff;color:#9a553f;font-size:26px;line-height:1}.flytSettingsScroll{max-height:calc(92dvh - 120px);overflow:auto;padding:0 2px 8px}.flytSettingsSection{margin:8px 0;border:1px solid #eadbd2;border-radius:17px;background:#fffdf9;overflow:hidden}.flytSettingsSection summary{display:flex;justify-content:space-between;align-items:center;padding:14px 13px;cursor:pointer;font-weight:800;list-style:none}.flytSettingsSection summary::-webkit-details-marker{display:none}.flytSettingsSection summary>b{font-size:19px;color:#ad5c45;transition:transform .16s}.flytSettingsSection[open] summary>b{transform:rotate(180deg)}.flytSettingsSectionBody{padding:0 10px 11px}.flytSettingsToggle,.flytSettingsLink{width:100%;display:flex;align-items:center;justify-content:space-between;gap:12px;padding:12px 4px;border:0;border-top:1px solid #f1e3dc;background:transparent;text-align:left}.flytSettingsToggle:first-child,.flytSettingsLink:first-child{border-top:0}.flytSettingsToggle span{display:grid;gap:3px}.flytSettingsToggle strong{font-size:14px}.flytSettingsToggle small,.flytSettingsHint{color:#806b61;font-size:12px;line-height:1.35}.flytSettingsToggle i{width:42px;height:25px;flex:0 0 42px;padding:3px;border-radius:999px;background:#e9ddd7;transition:.16s}.flytSettingsToggle i.on{background:#d77b52}.flytSettingsToggle i b{display:block;width:19px;height:19px;border-radius:50%;background:white;box-shadow:0 1px 3px #4322;transition:.16s}.flytSettingsToggle i.on b{transform:translateX(17px)}.flytSettingsLink{font-weight:750;color:#573a31}.flytSettingsLink b{font-size:23px;color:#b06046}.flytSettingsInfo{display:flex;justify-content:space-between;gap:8px;padding:8px 4px 12px;color:#806b61;font-size:13px}.flytSettingsInfo strong{color:#452f29}.flytSettingsRestore{width:100%;margin-top:10px;padding:10px;border:1px solid #df9a79;border-radius:12px;background:#fff7f1;color:#a8543e;font-weight:800}.flytSettingsVersion{margin:4px;color:#a08b80;font-size:11px}` ;document.head.appendChild(style)}
document.addEventListener('click',event=>{const target=event.target.closest?.('[data-settings-open],[data-settings-close],[data-settings-toggle],[data-settings-points-toggle],[data-settings-restore],[data-settings-sync],[data-settings-task-setup],[data-settings-task-order],[data-settings-rewards],[data-settings-history],[data-settings-seen-suggestions]');if(!target)return;if(target.matches('[data-settings-open]')){event.preventDefault();open();return}if(target.matches('[data-settings-close]')){event.preventDefault();close();return}if(target.matches('[data-settings-toggle]')){event.preventDefault();const path=target.dataset.settingsToggle;setValue(path,!enabled(path));const layer=$('#flytSettings');if(layer){layer.replaceWith(document.createRange().createContextualFragment(markup()))}return}if(target.matches('[data-settings-points-toggle]')){event.preventDefault();setPointsEnabled(!pointsEnabled());const layer=$('#flytSettings');if(layer)layer.replaceWith(document.createRange().createContextualFragment(markup()));return}if(target.matches('[data-settings-restore]')){event.preventDefault();restore();return}event.preventDefault();const action=target.matches('[data-settings-sync]')?'sync':target.matches('[data-settings-task-setup]')?'task-setup':target.matches('[data-settings-task-order]')?'task-order':target.matches('[data-settings-rewards]')?'rewards':target.matches('[data-settings-history]')?'history':'seen-suggestions';route(action)},true);
function install(){ensureStyles();const button=$('#setupBtn');if(button){button.textContent='Innstillinger';button.setAttribute('aria-label','Åpne innstillinger');button.onclick=event=>{event.preventDefault();open()}}const content=$('#content');if(content)new MutationObserver(()=>queueMicrotask(applyHome)).observe(content,{childList:true,subtree:true});new MutationObserver(()=>queueMicrotask(addMenuEntry)).observe(document.body,{childList:true,subtree:true});addMenuEntry();applyHome()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
window.addEventListener('pageshow',()=>{install();applyHome()});
window.FlytSettingsUI={version:VERSION,open,close,enabled,personal,applyHome};
})();
