(()=>{
'use strict';
const ORDER=['Barn','Kjøkken','Klesvask','Renhold','Stue','Bad','Soverom','Dyr','Hage & ute','Bil','Innkjøp','Vedlikehold','Planlegging & admin','Personlig investering','Egendefinert'];
const LIB=window.FlytTaskLanguage?.catalog||[];
const DEFAULT_IDS=['dish_fill','dish_empty','kitchen','dinner','laundry_start','laundry_hang','laundry_fold','trash'];
const DAY_LABELS=[[1,'Man'],[2,'Tir'],[3,'Ons'],[4,'Tor'],[5,'Fre'],[6,'Lør'],[7,'Søn']];
let step=1,openCategory=null,patchTimer=null,legacyObserver=null,contentObserver=null;
const bridge=()=>window.FlytBridge;
const state=()=>bridge()?.getState?.()||null;
const save=s=>{bridge()?.setState?.(s);window.FlytSync?.queueSave?.()};
const accordion=()=>window.FlytCategoryAccordion;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function category(t){const raw=String(t?.cat||'').trim();if(raw==='Husdyr')return'Dyr';if(raw==='Utearbeid')return'Hage & ute';if(raw==='Periodisk vedlikehold')return'Vedlikehold';if(raw==='Usynlig arbeid')return'Planlegging & admin';if(raw==='Vask & klær')return['laundry_start','laundry_hang','laundry_fold','laundry'].includes(String(t?.id))?'Klesvask':'Renhold';if(raw==='Hus'){if(['living','hallway'].includes(t.id))return'Stue';if(t.id==='bed')return'Soverom';if(['laundry'].includes(t.id))return'Klesvask';if(t.id==='vacuum')return'Renhold';if(t.id==='trash')return'Vedlikehold'}return raw||'Egendefinert'}
function customCats(s){return [...new Set([...(s?.custom||[]),...(s?.tasks||[])].map(category).filter(c=>c&&c!=='Egendefinert'&&!ORDER.includes(c)))].sort((a,b)=>a.localeCompare(b,'nb'))}
function allCategories(s){return [...ORDER.filter(c=>c!=='Egendefinert'),...customCats(s),'Egendefinert']}
function members(){const xs=(window.FlytSync?.getContext?.()?.members||[]).map(m=>m.display_name).filter(Boolean);return [...new Set(['Begge',...xs])];}
function ownerOptions(current){return members().map(n=>`<option ${n===current?'selected':''}>${esc(n)}</option>`).join('')}
function snapshot(s,label){return{id:'setup_'+Date.now()+'_'+Math.random().toString(36).slice(2,6),savedAt:new Date().toISOString(),label,tasks:structuredClone(s.tasks||[]),custom:structuredClone(s.custom||[]),taskOverrides:structuredClone(s.taskOverrides||{}),areas:structuredClone(s.areas||{}),trainingFor:structuredClone(s.trainingFor||{}),categoryRelevant:structuredClone(s.categoryRelevant||{})}}
function archive(s,label){const hist=Array.isArray(s.setupHistory)?[...s.setupHistory]:[],snap=snapshot(s,label),sig=x=>JSON.stringify({tasks:x.tasks||[],custom:x.custom||[],taskOverrides:x.taskOverrides||{},areas:x.areas||{},trainingFor:x.trainingFor||{},categoryRelevant:x.categoryRelevant||{}});if(!hist[0]||sig(hist[0])!==sig(snap))hist.unshift(snap);return hist.slice(0,5)}
function ensureRoot(){let root=document.querySelector('#flytSetupV2');if(root)return root;root=document.createElement('div');root.id='flytSetupV2';root.className='hidden';root.style.cssText='position:fixed;inset:0;z-index:220;background:#fff7f1;display:grid;grid-template-rows:auto minmax(0,1fr) auto;color:var(--ink)';root.innerHTML=`<div style="padding:max(14px,env(safe-area-inset-top)) 16px 12px;border-bottom:1px solid var(--line);background:#fff"><div class="ey">Husholdningsoppsett</div><strong id="flytSetupV2Title">Oppsett</strong></div><div id="flytSetupV2Body" style="overflow-y:auto;-webkit-overflow-scrolling:touch;touch-action:pan-y;padding:18px 15px"></div><div style="padding:10px 15px max(12px,env(safe-area-inset-bottom));border-top:1px solid var(--line);background:#fff;display:flex;gap:8px;position:relative;z-index:2"><button type="button" id="flytSetupV2Back" class="secondary grow">Lukk</button><button type="button" id="flytSetupV2Next" class="primary grow">Neste</button></div>`;document.body.appendChild(root);root.querySelector('#flytSetupV2Back').addEventListener('click',()=>{if(step>1){step--;render({resetScroll:true})}else close()});root.querySelector('#flytSetupV2Next').addEventListener('click',()=>{if(step<2){step++;render({resetScroll:true})}else finish()});root.querySelector('#flytSetupV2Body').addEventListener('click',handleBodyClick);root.querySelector('#flytSetupV2Body').addEventListener('change',handleBodyChange);return root}
function hideLegacy(){const old=document.querySelector('#setup');if(old&&!old.classList.contains('hidden'))old.classList.add('hidden');if(old){old.style.pointerEvents='none';old.setAttribute('aria-hidden','true')}}
function taskSource(s,id){const base=[...LIB,...(s.custom||[])].find(t=>String(t.id)===String(id));return base?{...base,...(s.taskOverrides?.[id]||{})}:base}
function frequencyLabel(type){return type==='daily'?'Dager per uke':type==='period'?'Ganger per måned':'Ganger per uke'}
function rhythmName(type){return type==='daily'?'Fast på valgte dager':type==='period'?'Ganger per måned':'Fleksibel i uken'}
function preferredDays(t){return [...new Set((Array.isArray(t?.preferredDays)?t.preferredDays:[]).map(Number).filter(n=>n>=1&&n<=7))].sort((a,b)=>a-b)}
function effortLevel(t){return Math.min(5,Math.max(1,Math.round(Number(t?.effortLevel)||Number(t?.pts)/10||1)))}
function effortOptions(current){return [1,2,3,4,5].map(level=>`<option value="${level}" ${level===current?'selected':''}>${level} · ${level*10} poeng</option>`).join('')}
function daySelector(t){if(t.type!=='daily')return'';const days=preferredDays(t);return `<div style="margin-top:10px"><span class="label">Faste dager</span><div style="display:grid;grid-template-columns:repeat(7,minmax(0,1fr));gap:4px;margin-top:6px">${DAY_LABELS.map(([n,l])=>`<label style="text-align:center;font-size:11px"><input type="checkbox" data-v2-day="${esc(t.id)}|${n}" ${days.includes(n)?'checked':''} style="display:block;margin:0 auto 4px;accent-color:var(--accent)">${l}</label>`).join('')}</div><div class="taskmeta" style="margin-top:6px">Oppgaven ligger automatisk i Dagens plan på disse dagene. Den kan fortsatt fjernes eller flyttes for én enkelt dag.</div></div>`}
function categoryOptions(s,current){return allCategories(s).map(c=>`<option value="${esc(c)}" ${c===current?'selected':''}>${esc(c)}</option>`).join('')}
function taskRow(s,t){const selected=(s.tasks||[]).find(x=>String(x.id)===String(t.id)),display=selected||t,type=display.type||'flex',days=preferredDays(display),max=type==='daily'?7:31,freq=type==='daily'&&days.length?days.length:Math.min(max,Math.max(1,Number(display.freq)||1)),effort=effortLevel(display);return `<div class="template" style="display:block"><label style="display:flex;gap:10px;align-items:flex-start"><input type="checkbox" data-v2-task="${esc(t.id)}" ${selected?'checked':''} style="margin-top:4px;transform:scale(1.2);accent-color:var(--accent)"><span class="grow"><strong>${esc(display.name)}</strong><div class="taskmeta">${rhythmName(type)} · Nivå ${effort} · ${effort*10} poeng${days.length?` · ${days.map(n=>DAY_LABELS[n-1][1]).join(', ')}`:''}${display.kind==='personal'?' · Personlig investering':''}</div></span></label>${selected?`<div class="config" style="margin-left:28px"><div class="grid2"><label><span class="label">Navn</span><input class="field" data-v2-name="${esc(t.id)}" value="${esc(display.name)}" maxlength="80"></label><label><span class="label">Kategori</span><select class="field" data-v2-cat="${esc(t.id)}">${categoryOptions(s,category(display))}</select></label><label><span class="label">Rytme</span><select class="field" data-v2-type="${esc(t.id)}"><option value="daily" ${type==='daily'?'selected':''}>Fast på valgte dager</option><option value="flex" ${type==='flex'?'selected':''}>Fleksibel i uken</option><option value="period" ${type==='period'?'selected':''}>Ganger per måned</option></select></label><label><span class="label">${frequencyLabel(type)}</span><input class="field" type="number" min="1" max="${max}" data-v2-freq="${esc(t.id)}" value="${freq}" ${type==='daily'&&days.length?'disabled':''}></label><label><span class="label">Innsatsnivå</span><select class="field" data-v2-effort="${esc(t.id)}" aria-label="Innsatsnivå for ${esc(display.name)}">${effortOptions(effort)}</select></label><label><span class="label">Vanligvis</span><select class="field" data-v2-owner="${esc(t.id)}">${ownerOptions(selected.owner||'Begge')}</select></label></div>${daySelector(selected)}</div>`:''}</div>`}
function setupCategory(s,c,tasks,{general=false}={}){const open=openCategory===c,add=general?'<button type="button" class="secondary full" data-v2-add-general="1">+ Legg til gjøremål</button>':`<button type="button" class="secondary full" data-v2-add-cat="${encodeURIComponent(c)}">+ Legg til gjøremål</button>`,body=tasks.length?tasks.map(t=>taskRow(s,t)).join(''):'<p class="sub" style="margin:12px 0">Ingen egendefinerte gjøremål her ennå.</p>';return accordion()?.item?.({key:c,label:c,count:tasks.length,open,attribute:'data-v2-category-toggle',body,bodyTop:`<div class="categoryAccordionActions">${add}</div>`})||''}
function step1(s){const relevant={};for(const c of allCategories(s))relevant[c]=s.categoryRelevant?.[c]!==false;const custom=s.custom||[],categories=allCategories(s).filter(c=>relevant[c]&&c!=='Egendefinert').map(c=>{const base=LIB.map(t=>taskSource(s,t.id)).filter(t=>category(t)===c),extra=custom.filter(t=>category(t)===c&&!base.some(b=>String(b.id)===String(t.id))),all=[...base,...extra];return all.length?setupCategory(s,c,all):''}).join(''),general=custom.filter(t=>category(t)==='Egendefinert');return `<h1 class="title">Bygg husholdningen</h1><p class="sub">Åpne én kategori om gangen og velg gjøremål. Navn, kategori, rytme, innsats og ansvar kan endres på alle oppgaver.</p><div class="card"><strong>Områder</strong><div class="grid2" style="margin-top:10px">${allCategories(s).filter(c=>c!=='Egendefinert').map(c=>`<label class="need" style="display:flex;align-items:center;gap:9px;padding:9px 10px;text-align:left"><input type="checkbox" data-v2-category="${encodeURIComponent(c)}" ${relevant[c]?'checked':''} style="width:19px;height:19px;accent-color:var(--accent)"><span>${esc(c)}</span></label>`).join('')}</div></div><div class="categoryAccordionList" data-v2-category-list>${categories}${setupCategory(s,'Egendefinert',general,{general:true})}</div><div class="card"><strong>Tilbakestill aktive gjøremål</strong><p class="sub">Poeng, gjennomføringer og statistikk beholdes.</p><button type="button" class="secondary full" data-v2-reset="1">Tilbakestill gjøremål</button></div>`}
function historyHtml(s){const hist=s.setupHistory||[];if(!hist.length)return'<p class="sub">Ingen tidligere oppsett lagret ennå.</p>';return hist.map(x=>{const d=new Date(x.savedAt),when=isNaN(d)?'Ukjent tidspunkt':d.toLocaleString('nb-NO',{dateStyle:'short',timeStyle:'short'});return `<div class="card row"><div class="grow"><strong>${esc(x.label||'Lagret oppsett')}</strong><div class="taskmeta">${when} · ${(x.tasks||[]).length} gjøremål</div></div><button type="button" class="small" data-v2-restore="${esc(x.id)}">Gjenopprett</button></div>`}).join('')}
function step2(s){const tasks=s.tasks||[];return `<h1 class="title">Klart til bruk</h1><div class="card hero"><strong>${tasks.length} gjøremål er valgt</strong><p class="sub" style="margin-bottom:0">Dette er et utgangspunkt. Dere kan legge til, fjerne og endre dem senere.</p></div><div class="section"><strong>Tidligere oppsett</strong>${historyHtml(s)}</div>`}
function render({resetScroll=false,scrollTop=null}={}){const s=state(),root=ensureRoot();if(!s)return;hideLegacy();const title=root.querySelector('#flytSetupV2Title'),body=root.querySelector('#flytSetupV2Body'),back=root.querySelector('#flytSetupV2Back'),next=root.querySelector('#flytSetupV2Next'),previous=scrollTop===null?body.scrollTop:Math.max(0,Number(scrollTop)||0);title.textContent=step===1?'Gjøremål':'Oppsummering';back.style.visibility='visible';back.textContent=step===1?'Lukk':'Tilbake';next.textContent=step===2?'Lagre oppsett':'Neste';body.style.overflowAnchor='none';body.innerHTML=step===1?step1(s):step2(s);const target=resetScroll?0:previous,apply=()=>{body.scrollTop=target};apply();requestAnimationFrame(()=>{apply();requestAnimationFrame(apply)});setTimeout(()=>{apply();body.style.overflowAnchor=''},100)}
function open(start=1){const s=state();if(!s)return false;step=Math.max(1,Math.min(2,Number(start)||1));openCategory=null;hideLegacy();const root=ensureRoot();root.classList.remove('hidden');root.setAttribute('aria-hidden','false');render({resetScroll:true});document.activeElement?.blur?.();return true}
function close(){const root=ensureRoot();root.classList.add('hidden');root.setAttribute('aria-hidden','true')}
function finish(){const s=state();if(!s)return;save({...s,setupDone:true,coupleJourney:{...(s.coupleJourney||{}),firstWinStartedAt:s.coupleJourney?.firstWinStartedAt||new Date().toISOString(),firstWinSeenBy:Array.isArray(s.coupleJourney?.firstWinSeenBy)?s.coupleJourney.firstWinSeenBy:[]},setupHistory:archive(s,'Lagret oppsett')});close();const view=bridge()?.getState?.()?.view;if(view==='tasks'){if(window.FlytRecurrenceUI?.render)window.FlytRecurrenceUI.render({resetScroll:true});else window.FlytTasksUI?.render?.({resetScroll:true})}else if(view==='home')window.FlytHomeUI?.render?.({resetScroll:true})}
function updateTask(id,field,fn){const s=state(),tasks=(s?.tasks||[]).map(t=>({...t})),i=tasks.findIndex(t=>String(t.id)===String(id));if(!s||i<0)return;fn(tasks[i]);const fields=new Set(tasks[i].customizedFields||[]);if(field)fields.add(field);tasks[i].customizedFields=[...fields];const taskOverrides={...(s.taskOverrides||{})};if(LIB.some(t=>String(t.id)===String(id)))taskOverrides[id]={...tasks[i]};const custom=(s.custom||[]).map(t=>String(t.id)===String(id)?{...tasks[i]}:t);save({...s,tasks,custom,taskOverrides});render()}
async function askConfirm(opts){if(window.FlytModal?.confirm)return window.FlytModal.confirm(opts);return true}
async function handleBodyClick(e){const b=e.target.closest('button');if(!b)return;if(b.dataset.v2CategoryToggle){const body=document.querySelector('#flytSetupV2Body'),key=decodeURIComponent(b.dataset.v2CategoryToggle),top=accordion()?.capture?.(b);openCategory=accordion()?.nextOpen?.(openCategory,key)??null;render();accordion()?.restore?.(body,`[data-v2-category-toggle="${encodeURIComponent(key)}"]`,top);return}if(b.dataset.v2Area){const s=state(),areas={...(s.areas||{})};areas[b.dataset.v2Area]=!areas[b.dataset.v2Area];save({...s,areas});render();return}if(b.dataset.v2AddCat){const pos=document.querySelector('#flytSetupV2Body')?.scrollTop||0,cat=decodeURIComponent(b.dataset.v2AddCat);await window.FlytCustomCategories?.addToCategory?.(cat);openCategory=cat;render({scrollTop:pos});return}if(b.dataset.v2AddGeneral){const pos=document.querySelector('#flytSetupV2Body')?.scrollTop||0;await window.FlytCustomCategories?.openGeneral?.();openCategory='Egendefinert';render({scrollTop:pos});return}if(b.dataset.v2Reset){const yes=await askConfirm({ey:'Oppsett',title:'Tilbakestille aktive gjøremål?',text:'Poeng, gjennomføringer og statistikk beholdes.',ok:'Tilbakestill'});if(!yes)return;const s=state(),rel=s.categoryRelevant||{},tasks=LIB.filter(t=>DEFAULT_IDS.includes(t.id)&&rel[category(t)]!==false).map(t=>({...t,owner:'Begge'}));openCategory=null;save({...s,tasks,taskOverrides:{},setupHistory:archive(s,'Før tilbakestilling')});render();return}if(b.dataset.v2Restore){const s=state(),snap=(s?.setupHistory||[]).find(x=>String(x.id)===String(b.dataset.v2Restore));if(!s||!snap)return;const yes=await askConfirm({ey:'Oppsett',title:'Gjenopprette oppsett?',text:'Poeng, gjennomføringer og statistikk beholdes.',ok:'Gjenopprett'});if(!yes)return;openCategory=null;save({...s,tasks:structuredClone(snap.tasks||[]),custom:structuredClone(snap.custom||[]),taskOverrides:structuredClone(snap.taskOverrides||{}),areas:structuredClone(snap.areas||s.areas||{}),trainingFor:structuredClone(snap.trainingFor||s.trainingFor||{}),categoryRelevant:structuredClone(snap.categoryRelevant||{}),setupHistory:archive(s,'Før gjenoppretting')});render()}}
function handleBodyChange(e){const el=e.target,s=state();if(!s)return;if(el.dataset.v2Category){const cat=decodeURIComponent(el.dataset.v2Category),categoryRelevant={...(s.categoryRelevant||{}),[cat]:el.checked};let tasks=[...(s.tasks||[])];if(!el.checked){tasks=tasks.filter(t=>category(t)!==cat);if(openCategory===cat)openCategory=null}save({...s,categoryRelevant,tasks,setupHistory:archive(s,el.checked?`${cat} slått på`:`${cat} slått av`)});render();return}if(el.dataset.v2Task){const id=el.dataset.v2Task,base=taskSource(s,id),tasks=[...(s.tasks||[])],i=tasks.findIndex(t=>String(t.id)===String(id));if(el.checked&&i<0&&base){const effort=effortLevel(base);tasks.push({...base,owner:base.owner||'Begge',freq:Math.max(1,Number(base.freq)||1),effortLevel:effort,pts:effort*10})}if(!el.checked&&i>=0)tasks.splice(i,1);save({...s,tasks});render();return}if(el.dataset.v2Name){const value=String(el.value||'').trim();if(!value){el.value=(s.tasks||[]).find(t=>String(t.id)===String(el.dataset.v2Name))?.name||'';bridge()?.toast?.('Gjøremålet må ha et navn');return}updateTask(el.dataset.v2Name,'name',t=>t.name=value);return}if(el.dataset.v2Cat){updateTask(el.dataset.v2Cat,'cat',t=>t.cat=el.value);return}if(el.dataset.v2Day){const [id,rawDay]=String(el.dataset.v2Day).split('|'),day=Number(rawDay),current=(s.tasks||[]).find(t=>String(t.id)===String(id)),days=preferredDays(current);if(!el.checked&&days.length===1){el.checked=true;bridge()?.toast?.('Velg minst én fast dag');return}updateTask(id,'preferredDays',t=>{const set=new Set(preferredDays(t));if(el.checked)set.add(day);else set.delete(day);t.preferredDays=[...set].sort((a,b)=>a-b);t.freq=t.preferredDays.length});return}if(el.dataset.v2Type){updateTask(el.dataset.v2Type,'type',t=>{t.type=el.value;if(el.value==='daily'){t.preferredDays=preferredDays(t).length?preferredDays(t):[1,2,3,4,5,6,7];t.freq=t.preferredDays.length}else{delete t.preferredDays;t.freq=Math.min(31,Math.max(1,Number(t.freq)||1))}});return}if(el.dataset.v2Freq){updateTask(el.dataset.v2Freq,'freq',t=>{if(t.type==='daily'&&preferredDays(t).length)return;t.freq=Math.min(t.type==='daily'?7:31,Math.max(1,Number(el.value)||1))});return}if(el.dataset.v2Effort){updateTask(el.dataset.v2Effort,'effortLevel',t=>{const effort=Math.min(5,Math.max(1,Math.round(Number(el.value)||1)));t.effortLevel=effort;t.pts=effort*10;const custom=new Set(t.customizedFields||[]);custom.add('pts');t.customizedFields=[...custom]});return}if(el.dataset.v2Owner){updateTask(el.dataset.v2Owner,'owner',t=>t.owner=el.value)}}
function patchTopButton(){const old=document.querySelector('#setupBtn');if(old){const clone=old.cloneNode(true);clone.id='setupBtnV2';clone.onclick=null;clone.removeAttribute('data-open-setup');clone.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();open(1)});old.replaceWith(clone)}const top=document.querySelector('#setupBtnV2');if(top&&!top.__flytV2){top.__flytV2=true;top.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();open(1)})}}
function patchContentButtons(){document.querySelectorAll('#content [data-open-new-setup],#content [data-open-setup]').forEach(old=>{const clone=old.cloneNode(true);clone.removeAttribute('data-open-new-setup');clone.removeAttribute('data-open-setup');clone.removeAttribute('onclick');clone.dataset.flytSetupV2='1';clone.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();open(1)});old.replaceWith(clone)});document.querySelectorAll('#content [data-flyt-setup-v2]').forEach(b=>{if(!b.__flytV2){b.__flytV2=true;b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();open(1)})}})}
function patchApis(){if(window.FlytTasksUI){window.FlytTasksUI.openSetup=open;window.FlytTasksUI.__setupV2=true}window.FlytSetupNavGuard={openSetup:open,go:dir=>{if(dir<0){if(step>1){step--;render({resetScroll:true})}else close();return true}if(dir>0&&step<2){step++;render({resetScroll:true});return true}if(dir>0&&step===2){finish();return true}return true},version:'v2'};patchTopButton();patchContentButtons()}
function watchLegacy(){const old=document.querySelector('#setup');if(!old||legacyObserver)return;legacyObserver=new MutationObserver(()=>{if(!old.classList.contains('hidden')){const t=(document.querySelector('#setupTitle')?.textContent||''),n=t.includes('Bygg')?1:t.includes('Slik')?2:0;old.classList.add('hidden');old.style.pointerEvents='none';open(n)}});legacyObserver.observe(old,{attributes:true,attributeFilter:['class']})}
function authBlocksAutoSetup(){const gate=document.querySelector('#betaGate'),app=document.querySelector('.app');return window.FlytSync?.isReady?.()!==true||(gate&&!gate.classList.contains('hidden'))||(app&&app.classList.contains('hidden'))}
function install(){ensureRoot();hideLegacy();patchApis();watchLegacy();const content=document.querySelector('#content');if(content&&!contentObserver){contentObserver=new MutationObserver(()=>queueMicrotask(patchContentButtons));contentObserver.observe(content,{childList:true,subtree:true})}patchTimer=setInterval(()=>{patchApis();watchLegacy();const s=state(),root=ensureRoot();if(!s||s.setupDone)return;if(authBlocksAutoSetup()){if(!root.classList.contains('hidden'))close();return}if(root.classList.contains('hidden'))open(1)},500);setTimeout(()=>{if(patchTimer){clearInterval(patchTimer);patchTimer=null}},30000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
window.FlytSetupV2={open,close,render,effortLevel,getOpenCategory:()=>openCategory,version:'20260903-2200'};
})();
