(()=>{
'use strict';
const ORDER=['Barn','Kjøkken','Vask & klær','Stue','Bad','Soverom','Dyr','Hage & ute','Bil','Innkjøp','Vedlikehold','Planlegging & admin','Personlig investering','Egendefinert'];
const LIB=window.FlytTaskLanguage?.catalog||[];
const DEFAULT_IDS=['dish_fill','dish_empty','kitchen','counter','dinner','kids_wakeup','kids_get_ready','lunch','bag','bedkids','bath_toilet','bath_sink','bath_shower','bath_floor','bath_tidy','living','laundry_start','laundry_hang','laundry_fold','trash','train'];
const AREAS=[['home','🏠 Hjem'],['children','👨‍👩‍👧 Barn'],['mental','🧠 Mental load'],['training','🏃 Trening'],['closeness','❤️ Nærhet'],['sex','🔥 Sexliv']];
const DAY_LABELS=[[1,'Man'],[2,'Tir'],[3,'Ons'],[4,'Tor'],[5,'Fre'],[6,'Lør'],[7,'Søn']];
let step=0,expanded={},patchTimer=null,legacyObserver=null,contentObserver=null;
const bridge=()=>window.FlytBridge;
const state=()=>bridge()?.getState?.()||null;
const save=s=>{bridge()?.setState?.(s);window.FlytSync?.queueSave?.()};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function category(t){const raw=String(t?.cat||'').trim();if(raw==='Husdyr')return'Dyr';if(raw==='Utearbeid')return'Hage & ute';if(raw==='Periodisk vedlikehold')return'Vedlikehold';if(raw==='Usynlig arbeid')return'Planlegging & admin';if(raw==='Hus'){if(['living','hallway'].includes(t.id))return'Stue';if(t.id==='bed')return'Soverom';if(['laundry','vacuum'].includes(t.id))return'Vask & klær';if(t.id==='trash')return'Vedlikehold'}return raw||'Egendefinert'}
function customCats(s){return [...new Set((s?.custom||[]).map(category).filter(c=>c&&c!=='Egendefinert'&&!ORDER.includes(c)))].sort((a,b)=>a.localeCompare(b,'nb'))}
function allCategories(s){return [...ORDER.filter(c=>c!=='Egendefinert'),...customCats(s),'Egendefinert']}
function members(){const xs=(window.FlytSync?.getContext?.()?.members||[]).map(m=>m.display_name).filter(Boolean);return [...new Set(['Begge',...xs])];}
function ownerOptions(current){return members().map(n=>`<option ${n===current?'selected':''}>${esc(n)}</option>`).join('')}
function snapshot(s,label){return{id:'setup_'+Date.now()+'_'+Math.random().toString(36).slice(2,6),savedAt:new Date().toISOString(),label,tasks:structuredClone(s.tasks||[]),custom:structuredClone(s.custom||[]),areas:structuredClone(s.areas||{}),trainingFor:structuredClone(s.trainingFor||{}),categoryRelevant:structuredClone(s.categoryRelevant||{})}}
function archive(s,label){const hist=Array.isArray(s.setupHistory)?[...s.setupHistory]:[],snap=snapshot(s,label),sig=x=>JSON.stringify({tasks:x.tasks||[],custom:x.custom||[],areas:x.areas||{},trainingFor:x.trainingFor||{},categoryRelevant:x.categoryRelevant||{}});if(!hist[0]||sig(hist[0])!==sig(snap))hist.unshift(snap);return hist.slice(0,5)}
function ensureRoot(){let root=document.querySelector('#flytSetupV2');if(root)return root;root=document.createElement('div');root.id='flytSetupV2';root.className='hidden';root.style.cssText='position:fixed;inset:0;z-index:220;background:#fff7f1;display:grid;grid-template-rows:auto minmax(0,1fr) auto;color:var(--ink)';root.innerHTML=`<div style="padding:max(14px,env(safe-area-inset-top)) 16px 12px;border-bottom:1px solid var(--line);background:#fff"><div class="ey">Husholdningsoppsett</div><strong id="flytSetupV2Title">Oppsett</strong></div><div id="flytSetupV2Body" style="overflow-y:auto;-webkit-overflow-scrolling:touch;touch-action:pan-y;padding:18px 15px"></div><div style="padding:10px 15px max(12px,env(safe-area-inset-bottom));border-top:1px solid var(--line);background:#fff;display:flex;gap:8px;position:relative;z-index:2"><button type="button" id="flytSetupV2Back" class="secondary grow">Tilbake</button><button type="button" id="flytSetupV2Next" class="primary grow">Neste</button></div>`;document.body.appendChild(root);root.querySelector('#flytSetupV2Back').addEventListener('click',()=>{if(step>0){step--;render({resetScroll:true})}else close()});root.querySelector('#flytSetupV2Next').addEventListener('click',()=>{if(step<2){step++;render({resetScroll:true})}else finish()});root.querySelector('#flytSetupV2Body').addEventListener('click',handleBodyClick);root.querySelector('#flytSetupV2Body').addEventListener('change',handleBodyChange);return root}
function hideLegacy(){const old=document.querySelector('#setup');if(old&&!old.classList.contains('hidden'))old.classList.add('hidden');if(old){old.style.pointerEvents='none';old.setAttribute('aria-hidden','true')}}
function taskSource(s,id){return [...LIB,...(s.custom||[])].find(t=>String(t.id)===String(id))}
function frequencyLabel(type){return type==='daily'?'Dager per uke':type==='period'?'Ganger per måned':'Ganger per uke'}
function rhythmName(type){return type==='daily'?'Dager per uke':type==='period'?'Ganger per måned':'Ganger per uke'}
function preferredDays(t){return [...new Set((Array.isArray(t?.preferredDays)?t.preferredDays:[]).map(Number).filter(n=>n>=1&&n<=7))].sort((a,b)=>a-b)}
function effortLevel(t){return Math.min(5,Math.max(1,Math.round(Number(t?.effortLevel)||Number(t?.pts)/10||1)))}
function effortOptions(current){return [1,2,3,4,5].map(level=>`<option value="${level}" ${level===current?'selected':''}>${level} · ${level*10} poeng</option>`).join('')}
function daySelector(t){if(t.type!=='daily')return'';const days=preferredDays(t);return `<div style="margin-top:10px"><span class="label">Bestemte dager (valgfritt)</span><div style="display:grid;grid-template-columns:repeat(7,minmax(0,1fr));gap:4px;margin-top:6px">${DAY_LABELS.map(([n,l])=>`<label style="text-align:center;font-size:11px"><input type="checkbox" data-v2-day="${esc(t.id)}|${n}" ${days.includes(n)?'checked':''} style="display:block;margin:0 auto 4px;accent-color:var(--accent)">${l}</label>`).join('')}</div><div class="taskmeta" style="margin-top:6px">Velg dager hvis oppgaven normalt hører til bestemte ukedager. Det er fortsatt mulig å registrere den på andre dager.</div></div>`}
function taskRow(s,t){const selected=(s.tasks||[]).find(x=>String(x.id)===String(t.id)),type=selected?.type||t.type||'flex',days=preferredDays(selected),max=type==='daily'?7:31,freq=type==='daily'&&days.length?days.length:Math.min(max,Math.max(1,Number(selected?.freq??t.freq)||1)),effort=effortLevel(selected||t);return `<div class="template" style="display:block"><label style="display:flex;gap:10px;align-items:flex-start"><input type="checkbox" data-v2-task="${esc(t.id)}" ${selected?'checked':''} style="margin-top:4px;transform:scale(1.2);accent-color:var(--accent)"><span class="grow"><strong>${esc(t.name)}</strong><div class="taskmeta">${rhythmName(type)} · Nivå ${effort} · ${effort*10} poeng${days.length?` · ${days.map(n=>DAY_LABELS[n-1][1]).join(', ')}`:''}${t.kind==='personal'?' · Personlig investering':''}</div></span></label>${selected?`<div class="config" style="margin-left:28px"><div class="grid2"><label><span class="label">Rytme</span><select class="field" data-v2-type="${esc(t.id)}"><option value="daily" ${type==='daily'?'selected':''}>Dager per uke</option><option value="flex" ${type==='flex'?'selected':''}>Ganger per uke</option><option value="period" ${type==='period'?'selected':''}>Ganger per måned</option></select></label><label><span class="label">${frequencyLabel(type)}</span><input class="field" type="number" min="1" max="${max}" data-v2-freq="${esc(t.id)}" value="${freq}" ${type==='daily'&&days.length?'disabled':''}></label><label><span class="label">Innsatsnivå</span><select class="field" data-v2-effort="${esc(t.id)}" aria-label="Innsatsnivå for ${esc(t.name)}">${effortOptions(effort)}</select></label><label><span class="label">Vanligvis</span><select class="field" data-v2-owner="${esc(t.id)}">${ownerOptions(selected.owner||'Begge')}</select></label></div>${daySelector(selected)}</div>`:''}</div>`}
function step0(s){return `<h1 class="title">Hva skal Flyt hjelpe med?</h1><div class="grid2">${AREAS.map(([k,n])=>`<button type="button" class="need ${s.areas?.[k]?'on':''}" data-v2-area="${k}">${n}</button>`).join('')}</div>`}
function step1(s){const relevant={};for(const c of allCategories(s))relevant[c]=s.categoryRelevant?.[c]!==false;const selectedIds=new Set((s.tasks||[]).map(t=>String(t.id)));const custom=s.custom||[];return `<h1 class="title">Bygg husholdningen</h1><p class="sub">Velg gjøremål, rytme og innsatsnivå. Forslagene er bare et utgangspunkt, og alt kan endres senere under «Rediger oppsett».</p><div class="card"><strong>Områder</strong><div class="grid2" style="margin-top:10px">${allCategories(s).filter(c=>c!=='Egendefinert').map(c=>`<label class="need" style="display:flex;align-items:center;gap:9px;padding:9px 10px;text-align:left"><input type="checkbox" data-v2-category="${encodeURIComponent(c)}" ${relevant[c]?'checked':''} style="width:19px;height:19px;accent-color:var(--accent)"><span>${esc(c)}</span></label>`).join('')}</div></div>${allCategories(s).filter(c=>relevant[c]&&c!=='Egendefinert').map(c=>{const base=LIB.filter(t=>category(t)===c),extra=custom.filter(t=>category(t)===c&&!base.some(b=>String(b.id)===String(t.id))),all=[...base,...extra];if(!all.length)return'';const always=all.filter((t,i)=>i<5||selectedIds.has(String(t.id))),alwaysIds=new Set(always.map(t=>String(t.id))),more=all.filter(t=>!alwaysIds.has(String(t.id))),shown=expanded[c]?[...always,...more]:always,hidden=more.length;return `<div class="section"><div class="row"><strong class="grow">${esc(c)}</strong><button type="button" class="small" data-v2-add-cat="${encodeURIComponent(c)}">+ Legg til</button></div>${shown.map(t=>taskRow(s,t)).join('')}${!expanded[c]&&hidden>0?`<button type="button" class="secondary full" data-v2-expand="${encodeURIComponent(c)}">Vis ${hidden} flere</button>`:''}${expanded[c]&&hidden>0?`<button type="button" class="secondary full" data-v2-collapse="${encodeURIComponent(c)}" style="margin-top:8px">Vis færre</button>`:''}</div>`}).join('')}<div class="section"><div class="row"><strong class="grow">Egendefinert</strong><button type="button" class="small" data-v2-add-general="1">+ Legg til</button></div>${custom.filter(t=>category(t)==='Egendefinert').map(t=>taskRow(s,t)).join('')||'<p class="sub">Ingen egendefinerte gjøremål her ennå.</p>'}</div><div class="card"><strong>Tilbakestill aktive gjøremål</strong><p class="sub">Poeng, gjennomføringer og statistikk beholdes.</p><button type="button" class="secondary full" data-v2-reset="1">Tilbakestill gjøremål</button></div>`}
function historyHtml(s){const hist=s.setupHistory||[];if(!hist.length)return'<p class="sub">Ingen tidligere oppsett lagret ennå.</p>';return hist.map(x=>{const d=new Date(x.savedAt),when=isNaN(d)?'Ukjent tidspunkt':d.toLocaleString('nb-NO',{dateStyle:'short',timeStyle:'short'});return `<div class="card row"><div class="grow"><strong>${esc(x.label||'Lagret oppsett')}</strong><div class="taskmeta">${when} · ${(x.tasks||[]).length} gjøremål</div></div><button type="button" class="small" data-v2-restore="${esc(x.id)}">Gjenopprett</button></div>`}).join('')}
function step2(s){const tasks=s.tasks||[],daily=tasks.filter(t=>t.type==='daily').length,weekly=tasks.filter(t=>t.type==='flex').length,monthly=tasks.filter(t=>t.type==='period').length;return `<h1 class="title">Slik blir Flyt</h1><div class="card hero"><div class="stat"><div><b>${tasks.length}</b><span>aktive</span></div><div><b>${daily}</b><span>dager/uke</span></div><div><b>${weekly+monthly}</b><span>ganger/uke/mnd</span></div></div></div><div class="section"><strong>Oppsettshistorikk</strong>${historyHtml(s)}</div>`}
function render({resetScroll=false,scrollTop=null}={}){const s=state(),root=ensureRoot();if(!s)return;hideLegacy();const title=root.querySelector('#flytSetupV2Title'),body=root.querySelector('#flytSetupV2Body'),back=root.querySelector('#flytSetupV2Back'),next=root.querySelector('#flytSetupV2Next'),previous=scrollTop===null?body.scrollTop:Math.max(0,Number(scrollTop)||0);title.textContent=step===0?'Hva er viktig for dere?':step===1?'Bygg husholdningen':'Slik blir Flyt';back.style.visibility='visible';back.textContent='Tilbake';next.textContent=step===2?'Lagre oppsett':'Neste';body.style.overflowAnchor='none';body.innerHTML=step===0?step0(s):step===1?step1(s):step2(s);const target=resetScroll?0:previous,apply=()=>{body.scrollTop=target};apply();requestAnimationFrame(()=>{apply();requestAnimationFrame(apply)});setTimeout(()=>{apply();body.style.overflowAnchor=''},100)}
function open(start=0){const s=state();if(!s)return false;step=Math.max(0,Math.min(2,Number(start)||0));hideLegacy();const root=ensureRoot();root.classList.remove('hidden');root.setAttribute('aria-hidden','false');render({resetScroll:true});document.activeElement?.blur?.();return true}
function close(){const root=ensureRoot();root.classList.add('hidden');root.setAttribute('aria-hidden','true')}
function finish(){const s=state();if(!s)return;save({...s,setupDone:true,coupleJourney:{...(s.coupleJourney||{}),firstWinStartedAt:s.coupleJourney?.firstWinStartedAt||new Date().toISOString(),firstWinSeenBy:Array.isArray(s.coupleJourney?.firstWinSeenBy)?s.coupleJourney.firstWinSeenBy:[]},setupHistory:archive(s,'Lagret oppsett')});close();const view=bridge()?.getState?.()?.view;if(view==='tasks'){if(window.FlytRecurrenceUI?.render)window.FlytRecurrenceUI.render({resetScroll:true});else window.FlytTasksUI?.render?.({resetScroll:true})}else if(view==='home')window.FlytHomeUI?.render?.({resetScroll:true})}
function updateTask(id,fn){const s=state(),tasks=(s?.tasks||[]).map(t=>({...t})),i=tasks.findIndex(t=>String(t.id)===String(id));if(!s||i<0)return;fn(tasks[i]);save({...s,tasks});render()}
async function askConfirm(opts){if(window.FlytModal?.confirm)return window.FlytModal.confirm(opts);return true}
async function handleBodyClick(e){const b=e.target.closest('button');if(!b)return;if(b.dataset.v2Area){const s=state(),areas={...(s.areas||{})};areas[b.dataset.v2Area]=!areas[b.dataset.v2Area];save({...s,areas});render();return}if(b.dataset.v2Expand){expanded[decodeURIComponent(b.dataset.v2Expand)]=true;render();return}if(b.dataset.v2Collapse){expanded[decodeURIComponent(b.dataset.v2Collapse)]=false;render();return}if(b.dataset.v2AddCat){const pos=document.querySelector('#flytSetupV2Body')?.scrollTop||0,cat=decodeURIComponent(b.dataset.v2AddCat);await window.FlytCustomCategories?.addToCategory?.(cat);render({scrollTop:pos});return}if(b.dataset.v2AddGeneral){const pos=document.querySelector('#flytSetupV2Body')?.scrollTop||0;await window.FlytCustomCategories?.openGeneral?.();render({scrollTop:pos});return}if(b.dataset.v2Reset){const yes=await askConfirm({ey:'Oppsett',title:'Tilbakestille aktive gjøremål?',text:'Poeng, gjennomføringer og statistikk beholdes.',ok:'Tilbakestill'});if(!yes)return;const s=state(),rel=s.categoryRelevant||{},tasks=LIB.filter(t=>DEFAULT_IDS.includes(t.id)&&rel[category(t)]!==false).map(t=>({...t,owner:'Begge'}));save({...s,tasks,setupHistory:archive(s,'Før tilbakestilling')});render();return}if(b.dataset.v2Restore){const s=state(),snap=(s?.setupHistory||[]).find(x=>String(x.id)===String(b.dataset.v2Restore));if(!s||!snap)return;const yes=await askConfirm({ey:'Oppsett',title:'Gjenopprette oppsett?',text:'Poeng, gjennomføringer og statistikk beholdes.',ok:'Gjenopprett'});if(!yes)return;save({...s,tasks:structuredClone(snap.tasks||[]),custom:structuredClone(snap.custom||[]),areas:structuredClone(snap.areas||s.areas||{}),trainingFor:structuredClone(snap.trainingFor||s.trainingFor||{}),categoryRelevant:structuredClone(snap.categoryRelevant||{}),setupHistory:archive(s,'Før gjenoppretting')});render()}}
function handleBodyChange(e){const el=e.target,s=state();if(!s)return;if(el.dataset.v2Category){const cat=decodeURIComponent(el.dataset.v2Category),categoryRelevant={...(s.categoryRelevant||{}),[cat]:el.checked};let tasks=[...(s.tasks||[])];if(!el.checked)tasks=tasks.filter(t=>category(t)!==cat);save({...s,categoryRelevant,tasks,setupHistory:archive(s,el.checked?`${cat} slått på`:`${cat} slått av`)});render();return}if(el.dataset.v2Task){const id=el.dataset.v2Task,base=taskSource(s,id),tasks=[...(s.tasks||[])],i=tasks.findIndex(t=>String(t.id)===String(id));if(el.checked&&i<0&&base){const effort=effortLevel(base);tasks.push({...base,owner:'Begge',freq:Math.max(1,Number(base.freq)||1),effortLevel:effort,pts:effort*10})}if(!el.checked&&i>=0)tasks.splice(i,1);save({...s,tasks});render();return}if(el.dataset.v2Day){const [id,rawDay]=String(el.dataset.v2Day).split('|'),day=Number(rawDay);updateTask(id,t=>{const days=preferredDays(t),set=new Set(days);if(el.checked)set.add(day);else set.delete(day);const next=[...set].sort((a,b)=>a-b);if(next.length){t.preferredDays=next;t.freq=next.length}else{delete t.preferredDays;t.freq=Math.max(1,Math.min(7,Number(t.freq)||1))}});return}if(el.dataset.v2Type){updateTask(el.dataset.v2Type,t=>{t.type=el.value;if(el.value!=='daily')delete t.preferredDays;const days=preferredDays(t);t.freq=days.length?days.length:Math.min(el.value==='daily'?7:31,Math.max(1,Number(t.freq)||1))});return}if(el.dataset.v2Freq){updateTask(el.dataset.v2Freq,t=>{if(t.type==='daily'&&preferredDays(t).length)return;t.freq=Math.min(t.type==='daily'?7:31,Math.max(1,Number(el.value)||1))});return}if(el.dataset.v2Effort){updateTask(el.dataset.v2Effort,t=>{const effort=Math.min(5,Math.max(1,Math.round(Number(el.value)||1)));t.effortLevel=effort;t.pts=effort*10});return}if(el.dataset.v2Owner){updateTask(el.dataset.v2Owner,t=>t.owner=el.value)}}
function patchTopButton(){const old=document.querySelector('#setupBtn');if(old){const clone=old.cloneNode(true);clone.id='setupBtnV2';clone.onclick=null;clone.removeAttribute('data-open-setup');clone.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();open(0)});old.replaceWith(clone)}const top=document.querySelector('#setupBtnV2');if(top&&!top.__flytV2){top.__flytV2=true;top.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();open(0)})}}
function patchContentButtons(){document.querySelectorAll('#content [data-open-new-setup],#content [data-open-setup]').forEach(old=>{const clone=old.cloneNode(true);clone.removeAttribute('data-open-new-setup');clone.removeAttribute('data-open-setup');clone.removeAttribute('onclick');clone.dataset.flytSetupV2='1';clone.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();open(1)});old.replaceWith(clone)});document.querySelectorAll('#content [data-flyt-setup-v2]').forEach(b=>{if(!b.__flytV2){b.__flytV2=true;b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();open(1)})}})}
function patchApis(){if(window.FlytTasksUI){window.FlytTasksUI.openSetup=open;window.FlytTasksUI.__setupV2=true}window.FlytSetupNavGuard={openSetup:open,go:dir=>{if(dir<0){if(step>0){step--;render({resetScroll:true})}else close();return true}if(dir>0&&step<2){step++;render({resetScroll:true});return true}if(dir>0&&step===2){finish();return true}return true},version:'v2'};patchTopButton();patchContentButtons()}
function watchLegacy(){const old=document.querySelector('#setup');if(!old||legacyObserver)return;legacyObserver=new MutationObserver(()=>{if(!old.classList.contains('hidden')){const t=(document.querySelector('#setupTitle')?.textContent||''),n=t.includes('Bygg')?1:t.includes('Slik')?2:0;old.classList.add('hidden');old.style.pointerEvents='none';open(n)}});legacyObserver.observe(old,{attributes:true,attributeFilter:['class']})}
function authBlocksAutoSetup(){const gate=document.querySelector('#betaGate'),app=document.querySelector('.app');return window.FlytSync?.isReady?.()!==true||(gate&&!gate.classList.contains('hidden'))||(app&&app.classList.contains('hidden'))}
function install(){ensureRoot();hideLegacy();patchApis();watchLegacy();const content=document.querySelector('#content');if(content&&!contentObserver){contentObserver=new MutationObserver(()=>queueMicrotask(patchContentButtons));contentObserver.observe(content,{childList:true,subtree:true})}patchTimer=setInterval(()=>{patchApis();watchLegacy();const s=state(),root=ensureRoot();if(!s||s.setupDone)return;if(authBlocksAutoSetup()){if(!root.classList.contains('hidden'))close();return}if(root.classList.contains('hidden'))open(0)},500);setTimeout(()=>{if(patchTimer){clearInterval(patchTimer);patchTimer=null}},30000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
window.FlytSetupV2={open,close,render,effortLevel,version:'20260901-2200'};
})();
