(()=>{
'use strict';
const ORDER=['Barn','Kjøkken','Vask & klær','Stue','Bad','Soverom','Dyr','Hage & ute','Bil','Innkjøp','Vedlikehold','Planlegging & admin','Personlig investering','Egendefinert'];
const LIB=[
{id:'dish_empty',cat:'Kjøkken',name:'Tømme oppvaskmaskin',freq:7,pts:20,type:'daily',kind:'house'},
{id:'dish_fill',cat:'Kjøkken',name:'Fylle oppvaskmaskin',freq:7,pts:20,type:'daily',kind:'house'},
{id:'kitchen',cat:'Kjøkken',name:'Rydde kjøkken',freq:7,pts:25,type:'daily',kind:'house'},
{id:'counter',cat:'Kjøkken',name:'Vaske kjøkkenbenken',freq:7,pts:15,type:'daily',kind:'house'},
{id:'dinner',cat:'Kjøkken',name:'Lage middag',freq:5,pts:40,type:'daily',kind:'house'},
{id:'fridge_clean',cat:'Kjøkken',name:'Vaske kjøleskap',freq:1,pts:40,type:'period',kind:'house'},
{id:'dishwasher_clean',cat:'Kjøkken',name:'Rense oppvaskmaskin',freq:1,pts:30,type:'period',kind:'house'},
{id:'oven_clean',cat:'Kjøkken',name:'Vaske stekeovn',freq:1,pts:50,type:'period',kind:'house'},
{id:'lunch',cat:'Barn',name:'Lage matpakker',freq:5,pts:25,type:'daily',kind:'house'},
{id:'bag',cat:'Barn',name:'Pakke sekk til barna',freq:5,pts:15,type:'daily',kind:'house'},
{id:'bedkids',cat:'Barn',name:'Legging',freq:7,pts:35,type:'daily',kind:'house'},
{id:'school',cat:'Barn',name:'Skole/barnehage-kommunikasjon',freq:2,pts:25,type:'flex',kind:'house'},
{id:'homework',cat:'Barn',name:'Lekser',freq:5,pts:20,type:'flex',kind:'house'},
{id:'kids_clothes_school',cat:'Barn',name:'Skifte klær til barnehage/skole',freq:2,pts:20,type:'flex',kind:'house'},
{id:'kids_clothes_buy',cat:'Barn',name:'Kjøpe nye klær til barna',freq:1,pts:35,type:'period',kind:'house'},
{id:'kids_clothes_sort',cat:'Barn',name:'Sortere klær barna har vokst ut av',freq:1,pts:35,type:'period',kind:'house'},
{id:'laundry',cat:'Vask & klær',name:'Vaske/brette klær',freq:3,pts:45,type:'flex',kind:'house'},
{id:'vacuum',cat:'Vask & klær',name:'Støvsuge',freq:2,pts:50,type:'flex',kind:'house'},
{id:'floors',cat:'Vask & klær',name:'Vaske gulv',freq:2,pts:40,type:'flex',kind:'house'},
{id:'dust',cat:'Vask & klær',name:'Tørke støv',freq:1,pts:30,type:'flex',kind:'house'},
{id:'living',cat:'Stue',name:'Rydde stuen',freq:3,pts:25,type:'flex',kind:'house'},
{id:'hallway',cat:'Stue',name:'Rydde gangen',freq:3,pts:25,type:'flex',kind:'house'},
{id:'sofa_tidy',cat:'Stue',name:'Rydde sofa og oppholdsrom',freq:5,pts:15,type:'daily',kind:'house'},
{id:'bath',cat:'Bad',name:'Vaske bad',freq:1,pts:70,type:'flex',kind:'house'},
{id:'bath_tidy',cat:'Bad',name:'Rydde badet',freq:3,pts:20,type:'flex',kind:'house'},
{id:'bath_drain',cat:'Bad',name:'Rense sluk',freq:1,pts:35,type:'period',kind:'house'},
{id:'bed',cat:'Soverom',name:'Bytte sengetøy',freq:1,pts:60,type:'flex',kind:'house'},
{id:'kids_bedding',cat:'Soverom',name:'Bytte sengetøy på barnas senger',freq:1,pts:45,type:'flex',kind:'house'},
{id:'pet_food',cat:'Dyr',name:'Gi mat og friskt vann',freq:7,pts:15,type:'daily',kind:'house'},
{id:'pet_walk',cat:'Dyr',name:'Lufte hund',freq:7,pts:25,type:'daily',kind:'house'},
{id:'pet_litter',cat:'Dyr',name:'Rense kattekasse',freq:7,pts:20,type:'daily',kind:'house'},
{id:'pet_groom',cat:'Dyr',name:'Stell og børsting',freq:2,pts:20,type:'flex',kind:'house'},
{id:'pet_home_clean',cat:'Dyr',name:'Rengjøre bur/akvarium/dyreområde',freq:1,pts:40,type:'flex',kind:'house'},
{id:'pet_supplies',cat:'Dyr',name:'Kjøpe dyremat og utstyr',freq:1,pts:30,type:'flex',kind:'house'},
{id:'pet_vet',cat:'Dyr',name:'Veterinær, vaksiner og avtaler',freq:1,pts:40,type:'period',kind:'house'},
{id:'pet_meds',cat:'Dyr',name:'Gi medisiner/behandling',freq:7,pts:20,type:'daily',kind:'house'},
{id:'garden_mow',cat:'Hage & ute',name:'Klippe gress',freq:1,pts:50,type:'flex',kind:'house'},
{id:'garden_tidy',cat:'Hage & ute',name:'Rydde uteområde',freq:1,pts:35,type:'flex',kind:'house'},
{id:'garden_snow',cat:'Hage & ute',name:'Måke snø / strø',freq:1,pts:45,type:'flex',kind:'house'},
{id:'car_wash',cat:'Bil',name:'Vaske bilen',freq:1,pts:40,type:'flex',kind:'house'},
{id:'car_fuel',cat:'Bil',name:'Fylle drivstoff / lade',freq:1,pts:20,type:'flex',kind:'house'},
{id:'car_service',cat:'Bil',name:'Bestille service / EU-kontroll',freq:1,pts:40,type:'period',kind:'house'},
{id:'car_tires',cat:'Bil',name:'Skifte / følge opp dekk',freq:1,pts:50,type:'period',kind:'house'},
{id:'shop',cat:'Innkjøp',name:'Handle mat',freq:2,pts:45,type:'flex',kind:'house'},
{id:'shopping_household',cat:'Innkjøp',name:'Fylle på husholdningsvarer',freq:1,pts:25,type:'flex',kind:'house'},
{id:'shopping_returns',cat:'Innkjøp',name:'Returnere varer / pakker',freq:1,pts:25,type:'flex',kind:'house'},
{id:'trash',cat:'Vedlikehold',name:'Søppel/pant',freq:2,pts:25,type:'flex',kind:'house'},
{id:'windows',cat:'Vedlikehold',name:'Vaske vinduer',freq:1,pts:60,type:'period',kind:'house'},
{id:'laundry_machine_clean',cat:'Vedlikehold',name:'Rense vaskemaskin/tørketrommel',freq:1,pts:40,type:'period',kind:'house'},
{id:'maintenance_smoke',cat:'Vedlikehold',name:'Sjekke røykvarslere',freq:1,pts:30,type:'period',kind:'house'},
{id:'maintenance_service',cat:'Vedlikehold',name:'Bestille håndverker / service',freq:1,pts:40,type:'period',kind:'house'},
{id:'admin',cat:'Planlegging & admin',name:'Avtaler, lege og tannlege',freq:1,pts:40,type:'period',kind:'house'},
{id:'gifts',cat:'Planlegging & admin',name:'Gaver og bursdager',freq:1,pts:35,type:'period',kind:'house'},
{id:'weekly_menu',cat:'Planlegging & admin',name:'Lage ukemeny',freq:1,pts:30,type:'flex',kind:'house'},
{id:'weekly_plan',cat:'Planlegging & admin',name:'Planlegge uken',freq:1,pts:35,type:'flex',kind:'house'},
{id:'train',cat:'Personlig investering',name:'Trening',freq:3,pts:40,type:'flex',kind:'personal'}
];
const DEFAULT_IDS=['dish_empty','dish_fill','kitchen','counter','dinner','lunch','bag','bedkids','bath','living','laundry','trash','train'];
const AREAS=[['home','🏠 Hjem'],['children','👨‍👩‍👧 Barn'],['mental','🧠 Mental load'],['training','🏃 Trening'],['closeness','❤️ Nærhet'],['sex','🔥 Sexliv']];
let step=0,expanded={},patchTimer=null,legacyObserver=null,contentObserver=null;
const bridge=()=>window.FlytBridge;
const state=()=>bridge()?.getState?.()||null;
const save=s=>{bridge()?.setState?.(s);window.FlytSync?.queueSave?.()};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function category(t){const raw=String(t?.cat||'').trim();if(raw==='Husdyr')return'Dyr';if(raw==='Utearbeid')return'Hage & ute';if(raw==='Periodisk vedlikehold')return'Vedlikehold';if(raw==='Usynlig arbeid')return'Planlegging & admin';if(raw==='Hus'){if(['living','hallway'].includes(t.id))return'Stue';if(t.id==='bed')return'Soverom';if(['laundry','vacuum'].includes(t.id))return'Vask & klær';if(t.id==='trash')return'Vedlikehold'}return raw||'Egendefinert'}
function customCats(s){return [...new Set((s?.custom||[]).map(category).filter(c=>c&&c!=='Egendefinert'&&!ORDER.includes(c)))].sort((a,b)=>a.localeCompare(b,'nb'))}
function allCategories(s){return [...ORDER.filter(c=>c!=='Egendefinert'),...customCats(s),'Egendefinert']}
function members(){const xs=(window.FlytSync?.getContext?.()?.members||[]).map(m=>m.display_name).filter(Boolean);return [...new Set(['Begge',...xs])];}
function ownerOptions(current){return members().map(n=>`<option ${n===current?'selected':''}>${esc(n)}</option>`).join('')}
function snapshot(s,label){return{id:'setup_'+Date.now()+'_'+Math.random().toString(36).slice(2,6),savedAt:new Date().toISOString(),label,tasks:structuredClone(s.tasks||[]),custom:structuredClone(s.custom||[]),areas:structuredClone(s.areas||{}),trainingFor:structuredClone(s.trainingFor||{}),categoryRelevant:structuredClone(s.categoryRelevant||{})}}
function archive(s,label){const hist=Array.isArray(s.setupHistory)?[...s.setupHistory]:[],snap=snapshot(s,label),sig=x=>JSON.stringify({tasks:x.tasks||[],custom:x.custom||[],areas:x.areas||{},trainingFor:x.trainingFor||{},categoryRelevant:x.categoryRelevant||{}});if(!hist[0]||sig(hist[0])!==sig(snap))hist.unshift(snap);return hist.slice(0,5)}
function ensureRoot(){let root=document.querySelector('#flytSetupV2');if(root)return root;root=document.createElement('div');root.id='flytSetupV2';root.className='hidden';root.style.cssText='position:fixed;inset:0;z-index:220;background:#fff7f1;display:grid;grid-template-rows:auto minmax(0,1fr) auto;color:var(--ink)';root.innerHTML=`<div style="padding:max(14px,env(safe-area-inset-top)) 16px 12px;border-bottom:1px solid var(--line);background:#fff"><div class="ey">Husholdningsoppsett</div><strong id="flytSetupV2Title">Oppsett</strong></div><div id="flytSetupV2Body" style="overflow-y:auto;-webkit-overflow-scrolling:touch;touch-action:pan-y;padding:18px 15px"></div><div style="padding:10px 15px max(12px,env(safe-area-inset-bottom));border-top:1px solid var(--line);background:#fff;display:flex;gap:8px;position:relative;z-index:2"><button type="button" id="flytSetupV2Back" class="secondary grow">Tilbake</button><button type="button" id="flytSetupV2Next" class="primary grow">Neste</button></div>`;document.body.appendChild(root);root.querySelector('#flytSetupV2Back').addEventListener('click',()=>{if(step>0){step--;render({resetScroll:true})}else close()});root.querySelector('#flytSetupV2Next').addEventListener('click',()=>{if(step<2){step++;render({resetScroll:true})}else finish()});root.querySelector('#flytSetupV2Body').addEventListener('click',handleBodyClick);root.querySelector('#flytSetupV2Body').addEventListener('change',handleBodyChange);return root}
function hideLegacy(){const old=document.querySelector('#setup');if(old&&!old.classList.contains('hidden'))old.classList.add('hidden');if(old){old.style.pointerEvents='none';old.setAttribute('aria-hidden','true')}}
function taskSource(s,id){return [...LIB,...(s.custom||[])].find(t=>String(t.id)===String(id))}
function frequencyLabel(type){return type==='daily'?'Dager per uke':type==='period'?'Antall per måned':'Antall per uke'}
function taskRow(s,t){const selected=(s.tasks||[]).find(x=>String(x.id)===String(t.id)),type=selected?.type||t.type||'flex',max=type==='daily'?7:31,freq=Math.min(max,Math.max(1,Number(selected?.freq??t.freq)||1));return `<div class="template" style="display:block"><label style="display:flex;gap:10px;align-items:flex-start"><input type="checkbox" data-v2-task="${esc(t.id)}" ${selected?'checked':''} style="margin-top:4px;transform:scale(1.2);accent-color:var(--accent)"><span class="grow"><strong>${esc(t.name)}</strong><div class="taskmeta">${type==='daily'?'Daglig':type==='period'?'Månedlig':'Ukentlig'}${t.kind==='personal'?' · Personlig investering':''}</div></span></label>${selected?`<div class="config" style="margin-left:28px"><div class="grid2"><label><span class="label">Gjentas</span><select class="field" data-v2-type="${esc(t.id)}"><option value="daily" ${type==='daily'?'selected':''}>Daglig</option><option value="flex" ${type==='flex'?'selected':''}>Ukentlig</option><option value="period" ${type==='period'?'selected':''}>Månedlig</option></select></label><label><span class="label">${frequencyLabel(type)}</span><input class="field" type="number" min="1" max="${max}" data-v2-freq="${esc(t.id)}" value="${freq}"></label><label><span class="label">Poeng</span><input class="field" type="number" min="1" data-v2-pts="${esc(t.id)}" value="${Math.max(1,Number(selected.pts)||1)}"></label><label><span class="label">Vanligvis</span><select class="field" data-v2-owner="${esc(t.id)}">${ownerOptions(selected.owner||'Begge')}</select></label></div></div>`:''}</div>`}
function step0(s){return `<h1 class="title">Hva skal Flyt hjelpe med?</h1><div class="grid2">${AREAS.map(([k,n])=>`<button type="button" class="need ${s.areas?.[k]?'on':''}" data-v2-area="${k}">${n}</button>`).join('')}</div>`}
function step1(s){const relevant={};for(const c of allCategories(s))relevant[c]=s.categoryRelevant?.[c]!==false;const selectedIds=new Set((s.tasks||[]).map(t=>String(t.id)));const custom=s.custom||[];return `<h1 class="title">Bygg husholdningen</h1><p class="sub">Velg det som faktisk gjelder for dere. Endringene lagres fortløpende.</p><div class="card"><strong>Områder</strong><div class="grid2" style="margin-top:10px">${allCategories(s).filter(c=>c!=='Egendefinert').map(c=>`<label class="need" style="display:flex;align-items:center;gap:9px;padding:9px 10px;text-align:left"><input type="checkbox" data-v2-category="${encodeURIComponent(c)}" ${relevant[c]?'checked':''} style="width:19px;height:19px;accent-color:var(--accent)"><span>${esc(c)}</span></label>`).join('')}</div></div>${allCategories(s).filter(c=>relevant[c]&&c!=='Egendefinert').map(c=>{const base=LIB.filter(t=>category(t)===c),extra=custom.filter(t=>category(t)===c&&!base.some(b=>String(b.id)===String(t.id))),all=[...base,...extra];if(!all.length)return'';const shown=expanded[c]?all:all.filter((t,i)=>i<5||selectedIds.has(String(t.id))),hidden=all.length-shown.length;return `<div class="section"><div class="row"><strong class="grow">${esc(c)}</strong><button type="button" class="small" data-v2-add-cat="${encodeURIComponent(c)}">+ Legg til</button></div>${shown.map(t=>taskRow(s,t)).join('')}${hidden>0?`<button type="button" class="secondary full" data-v2-expand="${encodeURIComponent(c)}">Vis ${hidden} flere</button>`:''}${expanded[c]&&all.length>5?`<button type="button" class="secondary full" data-v2-collapse="${encodeURIComponent(c)}" style="margin-top:8px">Vis færre</button>`:''}</div>`}).join('')}<div class="section"><div class="row"><strong class="grow">Egendefinert</strong><button type="button" class="small" data-v2-add-general="1">+ Legg til</button></div>${custom.filter(t=>category(t)==='Egendefinert').map(t=>taskRow(s,t)).join('')||'<p class="sub">Ingen egendefinerte gjøremål her ennå.</p>'}</div><div class="card"><strong>Tilbakestill aktive gjøremål</strong><p class="sub">Poeng, gjennomføringer og statistikk beholdes.</p><button type="button" class="secondary full" data-v2-reset="1">Tilbakestill gjøremål</button></div>`}
function historyHtml(s){const hist=s.setupHistory||[];if(!hist.length)return'<p class="sub">Ingen tidligere oppsett lagret ennå.</p>';return hist.map(x=>{const d=new Date(x.savedAt),when=isNaN(d)?'Ukjent tidspunkt':d.toLocaleString('nb-NO',{dateStyle:'short',timeStyle:'short'});return `<div class="card row"><div class="grow"><strong>${esc(x.label||'Lagret oppsett')}</strong><div class="taskmeta">${when} · ${(x.tasks||[]).length} gjøremål</div></div><button type="button" class="small" data-v2-restore="${esc(x.id)}">Gjenopprett</button></div>`}).join('')}
function step2(s){const tasks=s.tasks||[],daily=tasks.filter(t=>t.type==='daily').length,weekly=tasks.filter(t=>t.type==='flex').length,monthly=tasks.filter(t=>t.type==='period').length;return `<h1 class="title">Slik blir Flyt</h1><div class="card hero"><div class="stat"><div><b>${tasks.length}</b><span>aktive</span></div><div><b>${daily}</b><span>daglige</span></div><div><b>${weekly+monthly}</b><span>uke/måned</span></div></div></div><div class="section"><strong>Oppsettshistorikk</strong>${historyHtml(s)}</div>`}
function render({resetScroll=false,scrollTop=null}={}){const s=state(),root=ensureRoot();if(!s)return;hideLegacy();const title=root.querySelector('#flytSetupV2Title'),body=root.querySelector('#flytSetupV2Body'),back=root.querySelector('#flytSetupV2Back'),next=root.querySelector('#flytSetupV2Next'),previous=scrollTop===null?body.scrollTop:Math.max(0,Number(scrollTop)||0);title.textContent=step===0?'Hva er viktig for dere?':step===1?'Bygg husholdningen':'Slik blir Flyt';back.style.visibility='visible';back.textContent='Tilbake';next.textContent=step===2?'Lagre oppsett':'Neste';body.style.overflowAnchor='none';body.innerHTML=step===0?step0(s):step===1?step1(s):step2(s);const target=resetScroll?0:previous,apply=()=>{body.scrollTop=target};apply();requestAnimationFrame(()=>{apply();requestAnimationFrame(apply)});setTimeout(()=>{apply();body.style.overflowAnchor=''},100)}
function open(start=0){const s=state();if(!s)return false;step=Math.max(0,Math.min(2,Number(start)||0));hideLegacy();const root=ensureRoot();root.classList.remove('hidden');root.setAttribute('aria-hidden','false');render({resetScroll:true});document.activeElement?.blur?.();return true}
function close(){const root=ensureRoot();root.classList.add('hidden');root.setAttribute('aria-hidden','true')}
function finish(){const s=state();if(!s)return;save({...s,setupDone:true,setupHistory:archive(s,'Lagret oppsett')});close();const view=bridge()?.getState?.()?.view;if(view==='tasks'){if(window.FlytRecurrenceUI?.render)window.FlytRecurrenceUI.render({resetScroll:true});else window.FlytTasksUI?.render?.({resetScroll:true})}else if(view==='home')window.FlytHomeUI?.render?.({resetScroll:true})}
function updateTask(id,fn){const s=state(),tasks=(s?.tasks||[]).map(t=>({...t})),i=tasks.findIndex(t=>String(t.id)===String(id));if(!s||i<0)return;fn(tasks[i]);save({...s,tasks});render()}
async function askConfirm(opts){if(window.FlytModal?.confirm)return window.FlytModal.confirm(opts);return true}
async function handleBodyClick(e){const b=e.target.closest('button');if(!b)return;if(b.dataset.v2Area){const s=state(),areas={...(s.areas||{})};areas[b.dataset.v2Area]=!areas[b.dataset.v2Area];save({...s,areas});render();return}if(b.dataset.v2Expand){expanded[decodeURIComponent(b.dataset.v2Expand)]=true;render();return}if(b.dataset.v2Collapse){expanded[decodeURIComponent(b.dataset.v2Collapse)]=false;render();return}if(b.dataset.v2AddCat){const pos=document.querySelector('#flytSetupV2Body')?.scrollTop||0,cat=decodeURIComponent(b.dataset.v2AddCat);await window.FlytCustomCategories?.addToCategory?.(cat);render({scrollTop:pos});return}if(b.dataset.v2AddGeneral){const pos=document.querySelector('#flytSetupV2Body')?.scrollTop||0;await window.FlytCustomCategories?.openGeneral?.();render({scrollTop:pos});return}if(b.dataset.v2Reset){const yes=await askConfirm({ey:'Oppsett',title:'Tilbakestille aktive gjøremål?',text:'Poeng, gjennomføringer og statistikk beholdes.',ok:'Tilbakestill'});if(!yes)return;const s=state(),rel=s.categoryRelevant||{},tasks=LIB.filter(t=>DEFAULT_IDS.includes(t.id)&&rel[category(t)]!==false).map(t=>({...t,owner:'Begge'}));save({...s,tasks,setupHistory:archive(s,'Før tilbakestilling')});render();return}if(b.dataset.v2Restore){const s=state(),snap=(s?.setupHistory||[]).find(x=>String(x.id)===String(b.dataset.v2Restore));if(!s||!snap)return;const yes=await askConfirm({ey:'Oppsett',title:'Gjenopprette oppsett?',text:'Poeng, gjennomføringer og statistikk beholdes.',ok:'Gjenopprett'});if(!yes)return;save({...s,tasks:structuredClone(snap.tasks||[]),custom:structuredClone(snap.custom||[]),areas:structuredClone(snap.areas||s.areas||{}),trainingFor:structuredClone(snap.trainingFor||s.trainingFor||{}),categoryRelevant:structuredClone(snap.categoryRelevant||{}),setupHistory:archive(s,'Før gjenoppretting')});render()}}
function handleBodyChange(e){const el=e.target,s=state();if(!s)return;if(el.dataset.v2Category){const cat=decodeURIComponent(el.dataset.v2Category),categoryRelevant={...(s.categoryRelevant||{}),[cat]:el.checked};let tasks=[...(s.tasks||[])];if(!el.checked)tasks=tasks.filter(t=>category(t)!==cat);save({...s,categoryRelevant,tasks,setupHistory:archive(s,el.checked?`${cat} slått på`:`${cat} slått av`)});render();return}if(el.dataset.v2Task){const id=el.dataset.v2Task,base=taskSource(s,id),tasks=[...(s.tasks||[])],i=tasks.findIndex(t=>String(t.id)===String(id));if(el.checked&&i<0&&base)tasks.push({...base,owner:'Begge',freq:Math.max(1,Number(base.freq)||1)});if(!el.checked&&i>=0)tasks.splice(i,1);save({...s,tasks});render();return}if(el.dataset.v2Type){updateTask(el.dataset.v2Type,t=>{t.type=el.value;t.freq=Math.min(el.value==='daily'?7:31,Math.max(1,Number(t.freq)||1))});return}if(el.dataset.v2Freq){updateTask(el.dataset.v2Freq,t=>t.freq=Math.min(t.type==='daily'?7:31,Math.max(1,Number(el.value)||1)));return}if(el.dataset.v2Pts){updateTask(el.dataset.v2Pts,t=>t.pts=Math.max(1,Number(el.value)||1));return}if(el.dataset.v2Owner){updateTask(el.dataset.v2Owner,t=>t.owner=el.value)}}
function patchTopButton(){const old=document.querySelector('#setupBtn');if(old){const clone=old.cloneNode(true);clone.id='setupBtnV2';clone.onclick=null;clone.removeAttribute('data-open-setup');clone.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();open(0)});old.replaceWith(clone)}const top=document.querySelector('#setupBtnV2');if(top&&!top.__flytV2){top.__flytV2=true;top.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();open(0)})}}
function patchContentButtons(){document.querySelectorAll('#content [data-open-new-setup],#content [data-open-setup]').forEach(old=>{const clone=old.cloneNode(true);clone.removeAttribute('data-open-new-setup');clone.removeAttribute('data-open-setup');clone.removeAttribute('onclick');clone.dataset.flytSetupV2='1';clone.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();open(1)});old.replaceWith(clone)});document.querySelectorAll('#content [data-flyt-setup-v2]').forEach(b=>{if(!b.__flytV2){b.__flytV2=true;b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();open(1)})}})}
function patchApis(){if(window.FlytTasksUI){window.FlytTasksUI.openSetup=open;window.FlytTasksUI.__setupV2=true}window.FlytSetupNavGuard={openSetup:open,go:dir=>{if(dir<0){if(step>0){step--;render({resetScroll:true})}else close();return true}if(dir>0&&step<2){step++;render({resetScroll:true});return true}if(dir>0&&step===2){finish();return true}return true},version:'v2'};patchTopButton();patchContentButtons()}
function watchLegacy(){const old=document.querySelector('#setup');if(!old||legacyObserver)return;legacyObserver=new MutationObserver(()=>{if(!old.classList.contains('hidden')){const t=(document.querySelector('#setupTitle')?.textContent||''),n=t.includes('Bygg')?1:t.includes('Slik')?2:0;old.classList.add('hidden');old.style.pointerEvents='none';open(n)}});legacyObserver.observe(old,{attributes:true,attributeFilter:['class']})}
function install(){ensureRoot();hideLegacy();patchApis();watchLegacy();const content=document.querySelector('#content');if(content&&!contentObserver){contentObserver=new MutationObserver(()=>queueMicrotask(patchContentButtons));contentObserver.observe(content,{childList:true,subtree:true})}patchTimer=setInterval(()=>{patchApis();watchLegacy();const s=state(),login=document.querySelector('#login');if(s&&!s.setupDone&&login?.classList.contains('hidden')&&!document.querySelector('#flytSetupV2')?.classList.contains('hidden'))return;if(s&&!s.setupDone&&login?.classList.contains('hidden'))open(0)},500);setTimeout(()=>{if(patchTimer){clearInterval(patchTimer);patchTimer=null}},30000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
window.FlytSetupV2={open,close,render,version:'20260826-1352'};
})();
