((root,factory)=>{
'use strict';
const api=factory(root);
if(typeof module==='object'&&module.exports)module.exports=api;
if(root)root.FlytSummaryCore=api;
})(typeof window!=='undefined'?window:globalThis,root=>{
'use strict';
const VERSION='20260917-summaryhistory1',ZONE='Europe/Oslo';
const validDate=value=>/^\d{4}-\d{2}-\d{2}$/.test(String(value||''));
function dateKey(value=new Date()){const parts=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:ZONE,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(value).filter(part=>part.type!=='literal').map(part=>[part.type,part.value]));return`${parts.year}-${parts.month}-${parts.day}`}
function addDays(key,amount){const [year,month,day]=String(key).split('-').map(Number);return new Date(Date.UTC(year,month-1,day+Number(amount||0),12)).toISOString().slice(0,10)}
function weekRange(key){const day=new Date(`${key}T12:00:00Z`),offset=(day.getUTCDay()+6)%7,start=addDays(key,-offset);return{start,end:addDays(start,6)}}
function dates(start,end){const out=[];for(let key=start;key<=end;key=addDays(key,1))out.push(key);return out}
function currentTask(state,id){return root?.FlytDayPlan?.resolveTask?.(state,id)||[...(root?.FlytTaskLanguage?.catalog||[]),...(state?.custom||[]),...(state?.tasks||[])].find(task=>String(task?.id)===String(id))||null}
function normalizeTask(task,id){return{id:String(task?.id??id??''),name:String(task?.name||task?.taskName||'Gjøremål'),cat:String(root?.FlytDayPlan?.category?.(task)||task?.cat||'Egendefinert'),kind:String(task?.kind||'house'),type:String(task?.type||'flex')}}
function completionTask(state,item){const stored=state?.summaryArchive?.completionSnapshots?.[String(item?.id)],snapshot=stored||item?.taskSnapshot,current=currentTask(state,item?.taskId);return normalizeTask(snapshot?.name?{...current,...snapshot,id:item.taskId}:current||{id:item?.taskId,name:item?.taskName,cat:snapshot?.cat,kind:item?.kind},item?.taskId)}
function planFor(state,key){const stored=state?.summaryArchive?.planSnapshots?.[key];if(Array.isArray(stored))return stored.map(item=>normalizeTask(item,item?.id));const live=root?.FlytDayPlan?.planTasks?.(state,key)||(state?.tasks||[]).filter(task=>task?.type==='daily');return live.map(item=>normalizeTask(item,item?.id))}
function completionRows(state,start,end){return(state?.completions||[]).filter(item=>validDate(item?.date)&&item.date>=start&&item.date<=end).map(item=>({...item,task:completionTask(state,item)}))}
function isTogether(item){return item?.by==='Sammen'||Array.isArray(item?.contributors)&&item.contributors.filter(Boolean).length>1}
function actor(item){return isTogether(item)?'Sammen':String(item?.by||item?.contributors?.[0]||'Ukjent')}
function moveRows(state,start,end){const exact=(state?.taskMoves||[]).filter(item=>validDate(item?.fromDate)&&item.fromDate>=start&&item.fromDate<=end),seen=new Set(),out=[];for(const item of exact){const key=`${item.fromDate}|${item.toDate}|${item.taskId}`;if(seen.has(key))continue;seen.add(key);out.push(item)}const plans=state?.dayPlans||{};for(const [from,plan]of Object.entries(plans)){if(from<start||from>end)continue;for(const id of plan?.removedTaskIds||[]){const to=Object.keys(plans).filter(day=>day>from&&(plans[day]?.addedTaskIds||[]).some(value=>String(value)===String(id))).sort()[0];if(!to)continue;const key=`${from}|${to}|${id}`;if(seen.has(key))continue;seen.add(key);out.push({fromDate:from,toDate:to,taskId:id,inferred:true})}}return out}
function stats(state,start,end){const plans=new Map(),plannedKeys=new Set();for(const day of dates(start,end)){const tasks=planFor(state,day);plans.set(day,tasks);for(const task of tasks)plannedKeys.add(`${day}|${task.id}`)}const rows=completionRows(state,start,end),doneKeys=new Set(),actors={},tasks={},categories={};let together=0;for(const item of rows){const key=`${item.date}|${item.task.id}`;if(plannedKeys.has(key))doneKeys.add(key);const who=actor(item);actors[who]=(actors[who]||0)+1;if(isTogether(item))together++;const task=tasks[item.task.id]||(tasks[item.task.id]={...item.task,count:0,actors:{}});task.count++;task.actors[who]=(task.actors[who]||0)+1;categories[item.task.cat]=(categories[item.task.cat]||0)+1}const recognitions=(state?.recognitions||[]).filter(item=>item?.date>=start&&item?.date<=end).length,planned=plannedKeys.size,completed=doneKeys.size;return{start,end,planned,completed,percent:planned?Math.round(completed/planned*100):0,registered:rows.length,together,moved:moveRows(state,start,end).length,recognitions,actors,tasks:Object.values(tasks).sort((a,b)=>b.count-a.count||a.name.localeCompare(b.name,'nb')),categories:Object.entries(categories).map(([name,count])=>({name,count})).sort((a,b)=>b.count-a.count||a.name.localeCompare(b.name,'nb')),plans}}
function weeks(state,count=6,before=dateKey()){const current=weekRange(before),out=[];for(let index=count;index>=1;index--){const start=addDays(current.start,-7*index);out.push(stats(state,start,addDays(start,6)))}return out}
function taskTrend(state,taskId,count=4,before=dateKey()){return weeks(state,count,before).map(week=>({start:week.start,value:week.tasks.find(task=>String(task.id)===String(taskId))?.count||0}))}
function archivePatch(state,today=dateKey()){const current=state?.summaryArchive||{},completionSnapshots={...(current.completionSnapshots||{})},planSnapshots={...(current.planSnapshots||{})};let changed=false;for(const item of state?.completions||[]){const id=String(item?.id||'');if(!id||completionSnapshots[id]||item?.taskSnapshot?.name)continue;completionSnapshots[id]=completionTask({...state,summaryArchive:{...current,completionSnapshots}},item);changed=true}const recent=Array.from({length:57},(_,index)=>addDays(today,-index)),candidates=new Set([...recent,...(state?.completions||[]).map(item=>item?.date).filter(validDate),...Object.keys(state?.dayPlans||{}).filter(validDate)]);for(const key of candidates){if(planSnapshots[key]&&key!==today)continue;const snapshot=planFor({...state,summaryArchive:{...current,planSnapshots:key===today?{...planSnapshots,[key]:undefined}:planSnapshots}},key).map(task=>({id:String(task.id)}));if(JSON.stringify(planSnapshots[key]||null)===JSON.stringify(snapshot))continue;planSnapshots[key]=snapshot;changed=true}return changed?{...current,completionSnapshots,planSnapshots}:null}
return{VERSION,ZONE,actor,addDays,archivePatch,completionRows,dateKey,dates,isTogether,moveRows,planFor,stats,taskTrend,validDate,weekRange,weeks};
});
