(()=>{
'use strict';
const VERSION='20260917-summaries1',OSLO='Europe/Oslo';
const $=selector=>document.querySelector(selector),bridge=()=>window.FlytBridge;
const state=()=>bridge()?.getState?.()||null;
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
function dateKey(value=new Date()){const parts=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:OSLO,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(value).filter(part=>part.type!=='literal').map(part=>[part.type,part.value]));return `${parts.year}-${parts.month}-${parts.day}`}
function addDays(key,amount){const [year,month,day]=String(key).split('-').map(Number);return new Date(Date.UTC(year,month-1,day+Number(amount||0),12)).toISOString().slice(0,10)}
function weekRange(key){const day=new Date(`${key}T12:00:00Z`),offset=(day.getUTCDay()+6)%7,start=addDays(key,-offset);return{start,end:addDays(start,6)}}
function dates(start,end){const list=[];for(let key=start;key<=end;key=addDays(key,1))list.push(key);return list}
function identity(s){return String(window.FlytSync?.getContext?.()?.user_id||s?.user||'meg')}
function preference(path,fallback){const value=window.FlytSettingsUI?.enabled?.(path,fallback);return typeof value==='boolean'?value:fallback}
function seen(s){return s?.appPreferences?.personal?.[identity(s)]?.summarySeen||{}}
function planFor(s,key){return window.FlytDayPlan?.planTasks?.(s,key)||(s.tasks||[]).filter(task=>task?.type==='daily')}
function movedCount(s,start,end){const plans=s?.dayPlans||{},entries=Object.entries(plans).filter(([date])=>date>=start&&date<=end);let count=0;for(const [from,plan] of entries){for(const id of plan?.removedTaskIds||[]){const moved=Object.entries(plans).some(([to,next])=>to>from&&to<=end&&(next?.addedTaskIds||[]).some(item=>String(item)===String(id)));if(moved)count++}}return count}
function members(s){const names=new Set([s?.user,...Object.keys(s?.points||{}),...Object.keys(s?.status||{})].filter(Boolean));for(const item of s?.completions||[]){if(item?.by&&item.by!=='Sammen')names.add(item.by)}return [...names]}
function stats(s,start,end){const actors=Object.fromEntries(members(s).map(name=>[name,0]));let planned=0,completed=0,together=0;for(const date of dates(start,end)){const tasks=planFor(s,date),ids=new Set(tasks.map(task=>String(task.id)));planned+=ids.size;const done=new Map;for(const item of s?.completions||[]){if(item?.date!==date||!ids.has(String(item?.taskId))||done.has(String(item.taskId)))continue;done.set(String(item.taskId),item)}completed+=done.size;for(const item of done.values()){if(item?.by==='Sammen'||Array.isArray(item?.contributors)&&item.contributors.length>1){together++;continue}if(item?.by)actors[item.by]=(actors[item.by]||0)+1}}
const recognitions=(s?.recognitions||[]).filter(item=>item?.date>=start&&item?.date<=end).length;return{planned,completed,together,moved:movedCount(s,start,end),recognitions,actors}}
function copy(kind,data){if(kind==='day'){if(data.completed>=Math.max(3,Math.ceil(data.planned*.7)))return'Dere fikk mye gjort i går.';if(data.completed)return'Dere fikk tatt noen viktige ting sammen i går.';return'En rolig dag teller også.'}if(data.completed>=Math.max(5,Math.ceil(data.planned*.7)))return'Dere fikk mye til å flyte forrige uke.';if(data.completed)return'Små handlinger bygger en lettere hverdag.';return'En ny uke gir en ny start.'}
function rows(kind,data){const first=`<div><span>Gjennomført</span><strong>${data.completed} av ${data.planned}</strong></div>`,pct=kind==='week'?`<div><span>Fullført</span><strong>${data.planned?Math.round(data.completed/data.planned*100):0} %</strong></div>`:'',shared=`<div><span>Gjort sammen</span><strong>${data.together}</strong></div>`,moved=`<div><span>Flyttet videre</span><strong>${data.moved}</strong></div>`,recognitions=`<div><span>Anerkjennelser sendt</span><strong>${data.recognitions}</strong></div>`;return `<dl class="flytSummaryFacts">${first}${pct}${shared}${moved}${recognitions}</dl>`}
function distribution(data){const people=Object.entries(data.actors).filter(([,count])=>count>0);if(!people.length&&!data.together)return'';return `<div class="flytSummaryDistribution"><span class="ey">Bidrag i perioden</span>${people.map(([name,count])=>`<span>${esc(name)}: <strong>${count}</strong></span>`).join('')}${data.together?`<span>Sammen: <strong>${data.together}</strong></span>`:''}</div>`}
function markShown(kind,key){const s=state();if(!s)return;const user=identity(s),personal={...(s.appPreferences?.personal||{})},current={...(personal[user]||{}),summarySeen:{...(personal[user]?.summarySeen||{}),[kind]:key}};personal[user]=current;bridge()?.setState?.({...s,appPreferences:{...(s.appPreferences||{}),personal}});window.FlytSync?.queueSave?.()}
function close(kind,key){$('#flytSummaryDialog')?.remove();markShown(kind,key);queueMicrotask(check)}
function show(kind,key,data){const id=kind==='day'?'I går':'Forrige uke',layer=document.createElement('div');layer.id='flytSummaryDialog';layer.className='flytSummaryLayer';layer.innerHTML=`<section class="flytSummaryCard" role="dialog" aria-modal="true" aria-labelledby="flytSummaryTitle"><span class="ey">OPPSUMMERING</span><h2 id="flytSummaryTitle">${id}</h2><p>${esc(copy(kind,data))}</p>${rows(kind,data)}${kind==='week'?distribution(data):''}<button type="button" class="primary full" data-summary-close>Ferdig</button></section>`;layer.addEventListener('click',event=>{if(event.target.closest('[data-summary-close]'))close(kind,key)});document.body.appendChild(layer)}
function blocked(){return !!document.querySelector('[aria-modal="true"]:not(#flytSummaryDialog)')}
function check(){if($('#flytSummaryDialog')||blocked())return false;const s=state();if(!s?.user)return false;const today=dateKey(),yesterday=addDays(today,-1),lastWeek=weekRange(addDays(weekRange(today).start,-1));if(preference('summaries.daily',false)&&seen(s).daily!==yesterday){show('day',yesterday,stats(s,yesterday,yesterday));return true}if(preference('summaries.weekly',true)&&seen(s).weekly!==lastWeek.start){show('week',lastWeek.start,stats(s,lastWeek.start,lastWeek.end));return true}return false}
function install(){const style=document.createElement('style');style.id='flytSummaryStyles';style.textContent='.flytSummaryLayer{position:fixed;inset:0;z-index:1750;display:grid;place-items:center;padding:24px;background:#3a211b70;backdrop-filter:blur(5px);-webkit-backdrop-filter:blur(5px)}.flytSummaryCard{width:min(100%,390px);padding:24px 20px 20px;border:1px solid #eadbd2;border-radius:26px;background:linear-gradient(145deg,#fffaf7,#fff3ec);color:var(--ink);box-shadow:0 24px 70px #3b211b55;text-align:center}.flytSummaryCard>.ey{color:#b85e43}.flytSummaryCard h2{margin:8px 0 7px;font:600 31px/1.1 Georgia,serif}.flytSummaryCard>p{margin:0 0 17px;color:var(--muted);line-height:1.4}.flytSummaryFacts{display:grid;grid-template-columns:1fr 1fr;margin:0;border:1px solid #eadbd5;border-radius:17px;background:#fffdf9;overflow:hidden;text-align:left}.flytSummaryFacts>div{padding:11px 12px;border-right:1px solid #eee0da;border-bottom:1px solid #eee0da}.flytSummaryFacts>div:nth-child(2n){border-right:0}.flytSummaryFacts>div:nth-last-child(-n+2){border-bottom:0}.flytSummaryFacts span,.flytSummaryFacts strong{display:block}.flytSummaryFacts span{color:var(--muted);font-size:10px;font-weight:800;text-transform:uppercase;letter-spacing:.06em}.flytSummaryFacts strong{margin-top:3px;font:600 20px/1.1 Georgia,serif}.flytSummaryDistribution{display:grid;gap:5px;margin:14px 3px 0;color:var(--muted);font-size:13px;text-align:left}.flytSummaryDistribution .ey{margin-bottom:2px;color:#b85e43}.flytSummaryDistribution strong{color:var(--ink)}.flytSummaryCard .primary{margin-top:18px;min-height:48px}';if(!$('#flytSummaryStyles'))document.head.appendChild(style);[100,500,1300,3000,6000].forEach(delay=>setTimeout(check,delay));new MutationObserver(()=>setTimeout(check,80)).observe(document.body,{childList:true,subtree:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();window.addEventListener('pageshow',()=>setTimeout(check,200));window.FlytSummaryUI={version:VERSION,check,stats};
})();
