(()=>{
'use strict';
const SUPABASE_URL='https://uopzveejnztbovncqbpq.supabase.co';
const SUPABASE_KEY='sb_publishable_uK6xd8TJhN2MY10qHSQ2GQ_7hSIr2gv';
const APP_URL='https://almenning.github.io/Flyt-app/';
const RESET_URL='https://almenning.github.io/Flyt-app/reset.html';
if(!window.supabase){console.error('Flyt: Supabase-biblioteket mangler');return}
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
let ctx=null,pollTimer=null,saveTimer=null,applying=false,dirty=false,saving=false,authName='';
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const bridge=()=>window.FlytBridge;
function sharedState(){const s=structuredClone(bridge()?.getState?.()||{});delete s.user;delete s.view;return s}
function ensureBetaUi(){
  $('#login')?.classList.add('hidden');
  if(!$('#betaGate')){const g=document.createElement('div');g.id='betaGate';g.className='login';g.innerHTML='<div class="loginbox" id="betaGateBox"></div>';document.body.appendChild(g)}
  document.querySelector('.app')?.classList.add('hidden');
}
function showGate(html){ensureBetaUi();$('#betaGateBox').innerHTML=html;$('#betaGate').classList.remove('hidden');document.querySelector('.app')?.classList.add('hidden')}
function showApp(){ensureBetaUi();$('#betaGate').classList.add('hidden');document.querySelector('.app')?.classList.remove('hidden');updateChrome();const s=bridge()?.getState?.();if(s)bridge().setState({...s,user:myName(),view:s.view||'home'})}
function status(msg,bad=false){const e=$('#betaStatus');if(e){e.textContent=msg||'';e.style.color=bad?'#a63c31':'var(--muted)'}}
function shell(inner){return `<div class="logo">fl<b>y</b>t</div><div class="ey">Privat beta</div><h1 style="font:500 30px Georgia;margin:12px 0 6px">Flyt for to</h1>${inner}`}
function authChoice(){showGate(shell(`<p class="sub">Felles rytme for hjem, kommunikasjon og nærhet. Velg hvordan du vil fortsette.</p><button id="chooseSignin" class="primary full" style="margin-top:14px">Logg inn</button><button id="chooseSignup" class="secondary full" style="margin-top:10px">Opprett konto</button>`));$('#chooseSignin').onclick=()=>loginScreen();$('#chooseSignup').onclick=()=>signupScreen()}
function loginScreen(message=''){showGate(shell(`<div class="ey" style="margin-top:16px">Logg inn</div><p class="sub">For deg som allerede har en Flyt-konto.</p><input id="betaEmail" class="field" type="email" autocomplete="email" placeholder="E-post"><input id="betaPassword" class="field" type="password" autocomplete="current-password" placeholder="Passord"><button id="betaSignin" class="primary full" style="margin-top:6px">Logg inn</button><button id="betaForgot" class="secondary full" style="margin-top:10px">Glemt passord?</button><button id="backAuth" class="secondary full" style="margin-top:10px">Tilbake</button><p id="betaStatus" class="sub" style="min-height:42px">${esc(message)}</p>`));$('#betaSignin').onclick=signin;$('#betaForgot').onclick=forgotPassword;$('#backAuth').onclick=authChoice}
function signupScreen(message=''){showGate(shell(`<div class="ey" style="margin-top:16px">Opprett konto</div><p class="sub">Lag din egen konto. Etterpå oppretter du en husholdning eller blir med hos partneren din.</p><input id="betaName" class="field" placeholder="Fornavn"><input id="betaEmail" class="field" type="email" autocomplete="email" placeholder="E-post"><input id="betaPassword" class="field" type="password" minlength="6" autocomplete="new-password" placeholder="Passord, minst 6 tegn"><button id="betaSignup" class="primary full" style="margin-top:6px">Opprett konto</button><button id="backAuth" class="secondary full" style="margin-top:10px">Tilbake</button><p id="betaStatus" class="sub" style="min-height:42px">${esc(message)}</p>`));$('#betaSignup').onclick=signup;$('#backAuth').onclick=authChoice}
async function forgotPassword(){const email=$('#betaEmail').value.trim();if(!email){status('Skriv inn e-postadressen din først.',true);return}status('Sender lenke for nytt passord…');const {error}=await sb.auth.resetPasswordForEmail(email,{redirectTo:RESET_URL});if(error){status(error.message,true);return}status('Vi har sendt en lenke for å lage nytt passord. Sjekk innboksen og søppelpost.')}
async function signup(){const name=$('#betaName').value.trim(),email=$('#betaEmail').value.trim(),password=$('#betaPassword').value;if(!name){status('Skriv inn fornavnet ditt.',true);return}if(!email||password.length<6){status('Skriv inn gyldig e-post og minst 6 tegn i passordet.',true);return}status('Oppretter konto…');authName=name;const {data,error}=await sb.auth.signUp({email,password,options:{data:{display_name:name},emailRedirectTo:APP_URL}});if(error){status(error.message,true);return}if(data.session){await sb.rpc('set_my_display_name',{p_name:name});await bootstrap();return}signupScreen('Kontoen er opprettet. Bekreft e-posten, gå tilbake hit og logg inn.')}
async function signin(){const email=$('#betaEmail').value.trim(),password=$('#betaPassword').value;if(!email||!password){status('Skriv inn e-post og passord.',true);return}status('Logger inn…');const {data,error}=await sb.auth.signInWithPassword({email,password});if(error){status(error.message,true);return}authName=String(data?.user?.user_metadata?.display_name||data?.user?.user_metadata?.name||'').trim();await bootstrap()}
function householdScreen(message=''){showGate(shell(`<div class="ey" style="margin-top:16px">Koble dere sammen</div><h2 style="margin:8px 0">Lag deres Flyt</h2><p class="sub">Én oppretter husholdningen. Den andre blir med med invitasjonskoden.</p><div class="card"><strong>Opprett ny husholdning</strong><p class="sub">Velg dette hvis du er først ute.</p><input id="houseName" class="field" placeholder="Navn, f.eks. Hjemme hos oss"><button id="createHouse" class="primary full">Opprett husholdning</button></div><div class="card"><strong>Bli med hos partner</strong><p class="sub">Skriv inn koden partneren har fått.</p><input id="joinCode" class="field" maxlength="8" autocapitalize="characters" placeholder="Invitasjonskode"><button id="joinHouse" class="secondary full">Bli med</button></div><button id="betaSignout" class="secondary full">Logg ut</button><p id="betaStatus" class="sub">${esc(message)}</p>`));$('#createHouse').onclick=createHouse;$('#joinHouse').onclick=joinHouse;$('#betaSignout').onclick=async()=>{await sb.auth.signOut();ctx=null;authName='';authChoice()}}
async function createHouse(){status('Oppretter husholdning…');const {data,error}=await sb.rpc('create_household',{p_name:$('#houseName').value.trim()||'Vårt hjem'});if(error){status(error.message,true);return}await loadContext();await sb.rpc('save_my_flyt_state',{p_data:sharedState()});await loadContext();inviteScreen(ctx?.household?.invite_code||data?.[0]?.invite_code||'')}
function inviteScreen(code){showGate(shell(`<div class="ey" style="margin-top:16px">Husholdningen er opprettet</div><h2 style="margin:8px 0">Inviter partneren din</h2><p class="sub">Partneren oppretter sin egen konto og bruker koden under.</p><div class="card hero" style="text-align:center"><div class="ey">Invitasjonskode</div><div style="font-size:38px;font-weight:900;letter-spacing:.13em;margin:10px 0">${esc(code)}</div></div><button id="continueSetup" class="primary full">Sett opp husholdningen</button><p class="sub">Du kan gjøre oppsettet nå. Partneren får se samme oppsett når hen kobler seg til.</p>`));$('#continueSetup').onclick=()=>openHouseSetup(false)}
async function joinHouse(){const code=$('#joinCode').value.trim().toUpperCase();if(code.length<4){status('Skriv inn invitasjonskoden.',true);return}status('Kobler til…');const {error}=await sb.rpc('join_household',{p_code:code});if(error){status(error.message,true);return}await loadContext();applyRemote();reviewPartnerSetup()}
function reviewPartnerSetup(){const p=partnerMember();const s=ctx?.state||{};const tasks=Array.isArray(s.tasks)?s.tasks:[];showGate(shell(`<div class="ey" style="margin-top:16px">Dere er koblet</div><h2 style="margin:8px 0">Se gjennom oppsettet først</h2><p class="sub">${esc(p?.display_name||'Partneren din')} har satt opp husholdningen. Se gjennom og juster det dere vil før dere går videre.</p><div class="card hero"><strong>${esc(ctx?.household?.name||'Vårt hjem')}</strong><p class="sub">${tasks.length} valgte gjøremål</p></div><div class="card"><strong>Dette kan dere tilpasse</strong><p class="sub">Oppgaver, daglig/ukentlig/månedlig rytme, poeng, ansvar og hva som er viktig for dere.</p></div><button id="reviewSetup" class="primary full">Gå gjennom oppsettet</button>`));$('#reviewSetup').onclick=()=>openHouseSetup(true)}
function openHouseSetup(joiner){showApp();let tries=0;const open=()=>{if(window.FlytSetupV2?.open){window.FlytSetupV2.open(0);if(joiner)bridge()?.toast?.('Se gjennom og juster oppsettet før dere starter');return true}const b=$('#setupBtnV2,#setupBtn');if(b){b.click();if(joiner)bridge()?.toast?.('Se gjennom og juster oppsettet før dere starter');return true}return false};if(open())return;const timer=setInterval(()=>{if(open()||++tries>40)clearInterval(timer)},50)}
async function loadContext(){const {data,error}=await sb.rpc('get_my_flyt_context');if(error)throw error;ctx=data;if(!myMember()?.display_name&&authName){try{await sb.rpc('set_my_display_name',{p_name:authName});const retry=await sb.rpc('get_my_flyt_context');if(!retry.error)ctx=retry.data}catch(e){}}return ctx}
function myMember(){return ctx?.members?.find(m=>m.id===ctx?.user_id)||null}function myName(){return String(myMember()?.display_name||authName||'Meg').trim()||'Meg'}function partnerMember(){return ctx?.members?.find(m=>m.id!==ctx?.user_id)||null}
function updateChrome(){const me=myMember(),p=partnerMember(),sw=$('#switchUser');if(sw){sw.textContent=p?`${myName()} + ${p.display_name}`:myName();sw.disabled=true}const syn=$('#syncBtn');if(syn){syn.textContent=p?'Koblet':'Inviter';syn.onclick=()=>p?connectionSheet():inviteScreen(ctx?.household?.invite_code||'')}const lock=$('#lock');if(lock){lock.textContent='Logg ut';lock.onclick=async()=>{await sb.auth.signOut();ctx=null;authName='';dirty=false;authChoice()}}}
function ensureSheet(){if($('#syncModal'))return;const el=document.createElement('div');el.id='syncModal';el.className='syncModal hidden';el.style.zIndex='280';el.innerHTML='<div class="syncSheet"><div class="row"><div class="grow"><div class="ey">Par-kobling</div><h2 style="margin:4px 0">Flyt sammen</h2></div><button id="syncClose" class="pill">Lukk</button></div><div id="syncBody" style="margin-top:16px"></div></div>';document.body.appendChild(el);$('#syncClose').onclick=()=>el.classList.add('hidden')}
function connectionSheet(){ensureSheet();const p=partnerMember();$('#syncBody').innerHTML=`<div class="card hero"><strong>Dere er koblet</strong><p class="sub">${esc(myName())} og ${esc(p?.display_name||'partner')} deler ${esc(ctx?.household?.name||'samme husholdning')}.</p></div><div class="card"><div class="ey">Synkronisering</div><p class="sub" style="margin-bottom:0">Oppsett, gjennomføringer, poeng, behov og fristelser deles mellom dere.</p></div><button id="syncNow" class="secondary full">Synkroniser nå</button>`;$('#syncNow').onclick=async()=>{await pull(true);bridge()?.toast?.('Flyt er oppdatert')};$('#syncModal').classList.remove('hidden')}
function restoreActiveModule(view){if(view==='home'&&window.FlytHomeUI?.render){window.FlytHomeUI.render();return}if(view==='us'&&window.FlytOss?.render){window.FlytOss.render({refresh:false});return}if(view==='tasks'&&window.FlytTasksUI?.render){window.FlytTasksUI.render()}}
function applyRemote(){if(!ctx?.state||!Object.keys(ctx.state).length||!bridge())return;const local=bridge().getState(),view=local.view||'home';applying=true;try{bridge().setState({...local,...ctx.state,user:myName(),view});setTimeout(()=>restoreActiveModule(view),0)}catch(e){console.error('Flyt remote state ignored:',e)}finally{applying=false}}
async function pull(force=false){if(!ctx?.household)return;if((dirty||saving)&&!force)return;try{await loadContext();applyRemote();updateChrome()}catch(e){}}
async function push(){if(applying||!ctx?.household||saving)return;saving=true;try{const {error}=await sb.rpc('save_my_flyt_state',{p_data:sharedState()});if(error)throw error;dirty=false;await loadContext()}catch(e){console.error('Flyt save failed:',e);dirty=true}finally{saving=false}}
function queueSave(){if(applying||!ctx?.household)return;dirty=true;clearTimeout(saveTimer);saveTimer=setTimeout(push,650)}
function startPolling(){clearInterval(pollTimer);pollTimer=setInterval(()=>pull(false),5000)}
async function bootstrap(){ensureBetaUi();let session=null;try{const r=await sb.auth.getSession();session=r.data.session;authName=String(session?.user?.user_metadata?.display_name||session?.user?.user_metadata?.name||authName||'').trim()}catch(e){authChoice();return}if(!session){authChoice();return}try{await loadContext()}catch(e){loginScreen('Kunne ikke hente kontoen. Logg inn på nytt.');return}if(!ctx?.household){householdScreen();return}showApp();try{applyRemote()}catch(e){console.error('Flyt startup sync ignored:',e)}startPolling()}
window.FlytSync={queueSave,pull,bootstrap,myName,rpc:(name,args)=>sb.rpc(name,args),getContext:()=>ctx};window.addEventListener('DOMContentLoaded',bootstrap);
})();
