(()=>{
'use strict';
const $=s=>document.querySelector(s);
const bridge=()=>window.FlytBridge;
const ORDER=['Barn','Kjøkken','Vask & klær','Stue','Bad','Soverom','Dyr','Hage & ute','Bil','Innkjøp','Vedlikehold','Planlegging & admin','Personlig investering','Egendefinert'];
const LIB=[
{id:'dish_empty',cat:'Kjøkken',name:'Tømme oppvaskmaskin',freq:7,pts:20,type:'daily',kind:'house'},
{id:'dish_fill',cat:'Kjøkken',name:'Fylle oppvaskmaskin',freq:7,pts:20,type:'daily',kind:'house'},
{id:'kitchen',cat:'Kjøkken',name:'Rydde kjøkken',freq:7,pts:25,type:'daily',kind:'house'},
{id:'counter',cat:'Kjøkken',name:'Vaske kjøkkenbenken',freq:7,pts:15,type:'daily',kind:'house'},
{id:'dinner',cat:'Kjøkken',name:'Lage middag',freq:5,pts:40,type:'daily',kind:'house'},
{id:'fridge_clean',cat:'Kjøkken',name:'Vaske kjøleskap',freq:1,pts:40,type:'period',kind:'house'},
{id:'dishwasher_clean',cat:'Kjøkken',name:'Rense oppvaskmaskin',freq:1,pts:30,type:'period',kind:'house'},
{id:'oven_clean',cat:'Kjøkken',name:'Vaske stekeovn',freq:1,pts:50,type:'period',kind:'house'},
{id:'lunch',cat:'Barn',name:'Lage matpakker',freq:5,pts:25,type:'daily',kind:'house'},
{id:'bag',cat:'Barn',name:'Pakke sekk til barna',freq:5,pts:15,type:'daily',kind:'house'},
{id:'bedkids',cat:'Barn',name:'Legging',freq:7,pts:35,type:'daily',kind:'house'},
{id:'school',cat:'Barn',name:'Skole/barnehage-kommunikasjon',freq:2,pts:25,type:'flex',kind:'house'},
{id:'homework',cat:'Barn',name:'Lekser',freq:5,pts:20,type:'flex',kind:'house'},
{id:'kids_clothes_school',cat:'Barn',name:'Skifte klær til barnehage/skole',freq:2,pts:20,type:'flex',kind:'house'},
{id:'kids_clothes_buy',cat:'Barn',name:'Kjøpe nye klær til barna',freq:1,pts:35,type:'period',kind:'house'},
{id:'kids_clothes_sort',cat:'Barn',name:'Sortere klær barna har vokst ut av',freq:1,pts:35,type:'period',kind:'house'},
{id:'laundry',cat:'Vask & klær',name:'Vaske/brette klær',freq:3,pts:45,type:'flex',kind:'house'},
{id:'vacuum',cat:'Vask & klær',name:'Støvsuge',freq:2,pts:50,type:'flex',kind:'house'},
{id:'floors',cat:'Vask & klær',name:'Vaske gulv',freq:2,pts:40,type:'flex',kind:'house'},
{id:'dust',cat:'Vask & klær',name:'Tørke støv',freq:1,pts:30,type:'flex',kind:'house'},
{id:'living',cat:'Stue',name:'Rydde stuen',freq:3,pts:25,type:'flex',kind:'house'},
{id:'hallway',cat:'Stue',name:'Rydde gangen',freq:3,pts:25,type:'flex',kind:'house'},
{id:'sofa_tidy',cat:'Stue',name:'Rydde sofa og oppholdsrom',freq:5,pts:15,type:'daily',kind:'house'},
{id:'bath',cat:'Bad',name:'Vaske bad',freq:1,pts:70,type:'flex',kind:'house'},
{id:'bath_tidy',cat:'Bad',name:'Rydde badet',freq:3,pts:20,type:'flex',kind:'house'},
{id:'bath_drain',cat:'Bad',name:'Rense sluk',freq:1,pts:35,type:'period',kind:'house'},
{id:'bed',cat:'Soverom',name:'Bytte sengetøy',freq:1,pts:60,type:'flex',kind:'house'},
{id:'kids_bedding',cat:'Soverom',name:'Bytte sengetøy på barnas senger',freq:1,pts:45,type:'flex',kind:'house'},
{id:'pet_food',cat:'Dyr',name:'Gi mat og friskt vann',freq:7,pts:15,type:'daily',kind:'house'},
{id:'pet_walk',cat:'Dyr',name:'Lufte hund',freq:7,pts:25,type:'daily',kind:'house'},
{id:'pet_litter',cat:'Dyr',name:'Rense kattekasse',freq:7,pts:20,type:'daily',kind:'house'},
{id:'pet_groom',cat:'Dyr',name:'Stell og børsting',freq:2,pts:20,type:'flex',kind:'house'},
{id:'pet_home_clean',cat:'Dyr',name:'Rengjøre bur/akvarium/dyreområde',freq:1,pts:40,type:'flex',kind:'house'},
{id:'pet_supplies',cat:'Dyr',name:'Kjøpe dyremat og utstyr',freq:1,pts:30,type:'flex',kind:'house'},
{id:'pet_vet',cat:'Dyr',name:'Veterinær, vaksiner og avtaler',freq:1,pts:40,type:'period',kind:'house'},
{id:'pet_meds',cat:'Dyr',name:'Gi medisiner/behandling',freq:7,pts:20,type:'daily',kind:'house'},
{id:'garden_mow',cat:'Hage & ute',name:'Klippe gress',freq:1,pts:50,type:'flex',kind:'house'},
{id:'garden_tidy',cat:'Hage & ute',name:'Rydde uteområde',freq:1,pts:35,type:'flex',kind:'house'},
{id:'garden_snow',cat:'Hage & ute',name:'Måke snø / strø',freq:1,pts:45,type:'flex',kind:'house'},
{id:'car_wash',cat:'Bil',name:'Vaske bilen',freq:1,pts:40,type:'flex',kind:'house'},
{id:'car_fuel',cat:'Bil',name:'Fylle drivstoff / lade',freq:1,pts:20,type:'flex',kind:'house'},
{id:'car_service',cat:'Bil',name:'Bestille service / EU-kontroll',freq:1,pts:40,type:'period',kind:'house'},
{id:'car_tires',cat:'Bil',name:'Skifte / følge opp dekk',freq:1,pts:50,type:'period',kind:'house'},
{id:'shop',cat:'Innkjøp',name:'Handle mat',freq:2,pts:45,type:'flex',kind:'house'},
{id:'shopping_household',cat:'Innkjøp',name:'Fylle på husholdningsvarer',freq:1,pts:25,type:'flex',kind:'house'},
{id:'shopping_returns',cat:'Innkjøp',name:'Returnere varer / pakker',freq:1,pts:25,type:'flex',kind:'house'},
{id:'trash',cat:'Vedlikehold',name:'Søppel/pant',freq:2,pts:25,type:'flex',kind:'house'},
{id:'windows',cat:'Vedlikehold',name:'Vaske vinduer',freq:1,pts:60,type:'period',kind:'house'},
{id:'laundry_machine_clean',cat:'Vedlikehold',name:'Rense vaskemaskin/tørketrommel',freq:1,pts:40,type:'period',kind:'house'},
{id:'maintenance_smoke',cat:'Vedlikehold',name:'Sjekke røykvarslere',freq:1,pts:30,type:'period',kind:'house'},
{id:'maintenance_service',cat:'Vedlikehold',name:'Bestille håndverker / service',freq:1,pts:40,type:'period',kind:'house'},
{id:'admin',cat:'Planlegging & admin',name:'Avtaler, lege og tannlege',freq:1,pts:40,type:'period',kind:'house'},
{id:'gifts',cat:'Planlegging & admin',name:'Gaver og bursdager',freq:1,pts:35,type:'period',kind:'house'},
{id:'weekly_menu',cat:'Planlegging & admin',name:'Lage ukemeny',freq:1,pts:30,type:'flex',kind:'house'},
{id:'weekly_plan',cat:'Planlegging & admin',name:'Planlegge uken',freq:1,pts:35,type:'flex',kind:'house'},
{id:'train',cat:'Personlig investering',name:'Trening',freq:3,pts:40,type:'flex',kind:'personal'}
];
const DEFAULT_IDS=['dish_empty','dish_fill','kitchen','counter','dinner','lunch','bag','bedkids','bath','living','laundry','trash','train'];
let mode='day',setupStep=0,expanded={};
const getState=()=>bridge()?.getState?.()||null;
const saveState=s=>{bridge()?.setState?.(s);window.FlytSync?.queueSave?.()};
function localDate(){const d=new Date(),y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`}
function monday(){const x=new Date(),n=(x.getDay()+6)%7;x.setHours(0,0,0,0);x.setDate(x.getDate()-n);return x}
function weekComps(s){const m=monday();return (s.completions||[]).filter(c=>new Date(c.date)>=m)}
function todayComps(s){return (s.completions||[]).filter(c=>c.date===localDate())}
function dayIndex(){return ((new Date().getDay()+6)%7)+1}
function dayName(){return new Intl.DateTimeFormat('nb-NO',{weekday:'long'}).format(new Date()).replace(/^./,c=>c.toUpperCase())}
function dueToday(t){return t.type==='daily'&&dayIndex()<=Math.min(7,Math.max(0,Number(t.freq||0)))}
function category(t){const raw=(t.cat||'').trim();if(raw==='Husdyr')return 'Dyr';if(raw==='Utearbeid')return 'Hage & ute';if(raw==='Periodisk vedlikehold')return 'Vedlikehold';if(raw==='Usynlig arbeid')return 'Planlegging & admin';if(raw==='Hus'){if(['living','hallway'].includes(t.id))return 'Stue';if(t.id==='bed')return 'Soverom';if(['laundry','vacuum'].includes(t.id))return 'Vask & klær';if(t.id==='trash')return 'Vedlikehold'}return raw||'Hus'}
function relevantMap(s){const map={};for(const c of ORDER)map[c]=s.categoryRelevant?.[c]!==false;return map}
function count(s,id,day=false){const list=day?todayComps(s):weekComps(s);return list.filter(c=>c.taskId===id).length}
function ownCount(s,id,day=false){const list=day?todayComps(s):weekComps(s);return list.filter(c=>c.taskId===id&&c.by===s.user).length}
function complete(id){const s=getState(),t=(s?.tasks||[]).find(x=>x.id===id);if(!s||!t)return;const now=Date.now(),housePts=t.kind==='house'?t.pts:Math.round(t.pts*.2),points={...(s.points||{})};points[s.user]=(points[s.user]||0)+t.pts;saveState({...s,view:'tasks',points,completions:[...(s.completions||[]),{id:now,taskId:t.id,date:localDate(),by:s.user,kind:t.kind,housePts}]});bridge()?.toast?.(`${t.name} registrert · +${t.pts} poeng`)}
function undo(id){const s=getState(),t=(s?.tasks||[]).find(x=>x.id===id);if(!s||!t)return;const comps=[...(s.completions||[])],day=mode==='day';let ix=-1;for(let i=comps.length-1;i>=0;i--){const ok=day?comps[i].date===localDate():new Date(comps[i].date)>=monday();if(ok&&comps[i].taskId===id&&comps[i].by===s.user){ix=i;break}}if(ix<0)return;comps.splice(ix,1);const points={...(s.points||{})};points[s.user]=Math.max(0,(points[s.user]||0)-t.pts);saveState({...s,view:'tasks',points,completions:comps});bridge()?.toast?.('Registreringen er trukket tilbake')}
function taskCard(s,t){const day=mode==='day',n=count(s,t.id,day),goal=day?1:Number(t.freq||0),done=n>=goal;return `<div class="card"><div class="row"><div class="grow"><strong>${t.name}</strong><div class="taskmeta">${day?`${n}/1 i dag`:`${n}/${t.freq} denne uken`} · ${t.pts} poeng${t.owner?' · '+t.owner:''}</div></div>${done?`<span class="tag">${day?'Ferdig i dag ✓':'Mål nådd ✓'}</span>`:''}</div><div class="row" style="margin-top:10px"><button type="button" class="small" data-task-complete="${t.id}">+ Gjort</button>${ownCount(s,t.id,day)>0?`<button type="button" class="small" data-task-undo="${t.id}">− Angre</button>`:''}</div></div>`}
function render({resetScroll=false}={}){const s=getState(),c=$('#content');if(!s||!c)return;const pos=resetScroll?0:c.scrollTop,rel=relevantMap(s);let tasks=Array.isArray(s.tasks)?s.tasks.filter(t=>rel[category(t)]!==false):[];if(mode==='day')tasks=tasks.filter(dueToday);const groups=new Map();for(const t of tasks){const k=category(t);if(!groups.has(k))groups.set(k,[]);groups.get(k).push(t)}const keys=[...groups.keys()].sort((a,b)=>{const ai=ORDER.indexOf(a),bi=ORDER.indexOf(b);return (ai<0?999:ai)-(bi<0?999:bi)||a.localeCompare(b,'nb')});c.innerHTML=`<div class="ey">Gjøremål</div><h1 class="title">${mode==='day'?dayName():'Denne uken'}</h1><div class="segments" style="margin:14px 0 18px"><button type="button" data-task-mode="day" class="${mode==='day'?'on':''}">Dag · ${dayName()}</button><button type="button" data-task-mode="week" class="${mode==='week'?'on':''}">Uke</button></div><p class="sub">${mode==='day'?'Her teller det som faktisk gjelder i dag. Dagsmålet er et mål, ikke et tak.':'Her ser du hele ukemålet. Ukesmålet er en forventning, ikke et tak.'}</p>${mode==='day'&&!tasks.length?'<div class="card">Ingen faste gjøremål i dag.</div>':''}${keys.map(k=>`<div class="section"><div class="ey">${k}</div>${groups.get(k).map(t=>taskCard(s,t)).join('')}</div>`).join('')}<button type="button" class="primary full" data-open-new-setup="1" style="margin-top:18px">Rediger oppsett</button>`;document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('on',b.dataset.view==='tasks'));c.scrollTop=pos;requestAnimationFrame(()=>c.scrollTop=pos)}
function ownerOptions(sel){const ctx=window.FlytSync?.getContext?.(),names=Array.isArray(ctx?.members)?ctx.members.map(m=>m.display_name).filter(Boolean):[];return [...new Set(['Begge',...names,'Ingen fast'])].map(o=>`<option ${sel===o?'selected':''}>${o}</option>`).join('')}
function row(s,t){const sel=(s.tasks||[]).find(x=>x.id===t.id);return `<div class="template"><input type="checkbox" data-setup-task="${t.id}" ${sel?'checked':''}><div class="grow"><strong>${t.name}</strong><div class="taskmeta">${t.kind==='personal'?'Personlig investering':t.type==='daily'?'Dagsbundet':t.type==='flex'?'Fleksibel':'Periodebundet'}</div>${sel?`<div class="config"><div class="grid2"><label><span class="label">Ganger/uke</span><input class="field" type="number" min="1" max="21" data-setup-freq="${t.id}" value="${sel.freq}"></label><label><span class="label">Poeng</span><input class="field" type="number" min="1" data-setup-pts="${t.id}" value="${sel.pts}"></label><label><span class="label">Vanligvis</span><select class="field" data-setup-owner="${t.id}">${ownerOptions(sel.owner)}</select></label><label><span class="label">Timing</span><select class="field" data-setup-type="${t.id}"><option value="daily" ${sel.type==='daily'?'selected':''}>Dagsbundet</option><option value="flex" ${sel.type==='flex'?'selected':''}>Fleksibel</option><option value="period" ${sel.type==='period'?'selected':''}>Periodebundet</option></select></label></div></div>`:''}</div></div>`}
function snapshot(s,label){return{id:Date.now()+'_'+Math.random().toString(36).slice(2,6),savedAt:new Date().toISOString(),label,tasks:structuredClone(s.tasks||[]),custom:structuredClone(s.custom||[]),areas:structuredClone(s.areas||{}),trainingFor:structuredClone(s.trainingFor||{}),categoryRelevant:structuredClone(s.categoryRelevant||{})}}
function archive(s,label){const hist=Array.isArray(s.setupHistory)?[...s.setupHistory]:[],snap=snapshot(s,label);const sig=x=>JSON.stringify({tasks:x.tasks||[],custom:x.custom||[],areas:x.areas||{},trainingFor:x.trainingFor||{},categoryRelevant:x.categoryRelevant||{}});if(!hist[0]||sig(hist[0])!==sig(snap))hist.unshift(snap);return hist.slice(0,5)}
function historyHtml(s){const hist=Array.isArray(s.setupHistory)?s.setupHistory:[];if(!hist.length)return '<p class="sub">Ingen tidligere oppsett lagret ennå.</p>';return hist.map(x=>{const d=new Date(x.savedAt),when=isNaN(d)?'Ukjent tidspunkt':d.toLocaleString('nb-NO',{dateStyle:'short',timeStyle:'short'});return `<div class="card row"><div class="grow"><strong>${x.label||'Lagret oppsett'}</strong><div class="taskmeta">${when} · ${(x.tasks||[]).length} gjøremål</div></div><button type="button" class="small" data-setup-restore="${x.id}">Gjenopprett</button></div>`}).join('')}
function categoryChoices(s){const rel=relevantMap(s);return `<div class="card"><strong>Hva er relevant for dere?</strong><p class="sub">Fjern haken på områder dere ikke har eller ikke ønsker å bruke i Flyt.</p><div class="grid2" style="margin-top:10px">${ORDER.filter(c=>c!=='Egendefinert').map(c=>`<label class="need" style="display:flex;align-items:center;gap:10px;padding:10px 12px;text-align:left"><input type="checkbox" data-category-relevant="${encodeURIComponent(c)}" ${rel[c]?'checked':''} style="width:20px;height:20px;accent-color:var(--accent)"><span>${c}</span></label>`).join('')}</div></div>`}
function openSetup(step=0){setupStep=step;$('#setup')?.classList.remove('hidden');renderSetup()}
function closeSetup(){const s=getState();if(!s)return;saveState({...s,setupDone:true,setupHistory:archive(s,'Lagret oppsett')});$('#setup')?.classList.add('hidden');render()}
function renderSetup(){const s=getState(),body=$('#setupBody'),title=$('#setupTitle'),back=$('#setupBack'),next=$('#setupNext');if(!s||!body||!title||!back||!next)return;back.style.visibility=setupStep===0?'hidden':'visible';next.textContent=setupStep===2?'Lagre oppsett':'Neste';if(setupStep===0){title.textContent='Hva er viktig for dere?';body.innerHTML=`<h1 class="title">Hva skal Flyt hjelpe med?</h1><div class="grid2">${[['home','🏠 Hjem'],['children','👨‍👩‍👧 Barn'],['mental','🧠 Mental load'],['training','🏃 Trening'],['closeness','❤️ Nærhet'],['sex','🔥 Sexliv']].map(([k,n])=>`<button type="button" class="need ${s.areas?.[k]?'on':''}" data-area-choice="${k}">${n}</button>`).join('')}</div>`;return}if(setupStep===2){title.textContent='Slik blir Flyt';const weekly=(s.tasks||[]).reduce((a,t)=>a+(t.kind==='house'?Number(t.freq||0)*Number(t.pts||0):0),0);body.innerHTML=`<h1 class="title">Dette er deres oppsett</h1><div class="card hero"><div class="stat"><div><b>${(s.tasks||[]).filter(t=>t.kind==='house').length}</b><span>husoppgaver</span></div><div><b>${weekly}</b><span>ukepoeng</span></div><div><b>${Math.round(weekly/7)}</b><span>dagssnitt</span></div></div></div><div class="section"><strong>Oppsettshistorikk</strong>${historyHtml(s)}</div>`;return}title.textContent='Bygg husholdningen';const rel=relevantMap(s),selected=new Set((s.tasks||[]).map(t=>t.id));body.innerHTML=`<h1 class="title">Hva gjør dere i løpet av en uke?</h1><p class="sub">Start med å velge hvilke områder som faktisk gjelder for dere.</p>${categoryChoices(s)}${ORDER.filter(c=>c!=='Egendefinert'&&rel[c]&&LIB.some(t=>t.cat===c)).map(c=>{const all=LIB.filter(t=>t.cat===c),shown=expanded[c]?all:all.filter((t,i)=>i<6||selected.has(t.id)),hidden=all.length-shown.length;return `<div class="section"><strong>${c}</strong>${shown.map(t=>row(s,t)).join('')}${hidden>0?`<button type="button" class="secondary full" data-expand-cat="${encodeURIComponent(c)}">Vis ${hidden} flere forslag</button>`:''}${expanded[c]&&all.length>6?`<button type="button" class="secondary full" data-collapse-cat="${encodeURIComponent(c)}" style="margin-top:8px">Vis færre</button>`:''}</div>`}).join('')}<div class="section"><strong>Egendefinerte</strong>${(s.custom||[]).map(t=>row(s,t)).join('')}<button type="button" id="addCustomTask" class="secondary full">+ Legg til egendefinert oppgave</button></div><div class="section"><strong>Oppsettshistorikk</strong>${historyHtml(s)}</div><div class="card"><strong>Tilbakestill aktivt oppsett</strong><p class="sub">Tidligere gjennomføringer, poeng og statistikk beholdes.</p><button type="button" id="resetActiveTasks" class="secondary full">Tilbakestill gjøremål</button></div>`}
function updateTask(id,fn){const s=getState(),tasks=[...(s?.tasks||[])],i=tasks.findIndex(t=>t.id===id);if(!s||i<0)return;tasks[i]={...tasks[i]};fn(tasks[i]);saveState({...s,tasks});renderSetup()}
document.addEventListener('click',e=>{const setupBtn=e.target.closest('#setupBtn,[data-open-setup],[data-open-new-setup]');if(setupBtn){e.preventDefault();e.stopImmediatePropagation();openSetup(setupBtn.id==='setupBtn'?0:1);return}if(!$('#setup')?.classList.contains('hidden')){const b=e.target.closest('button');if(b?.id==='setupBack'){e.preventDefault();e.stopImmediatePropagation();if(setupStep>0){setupStep--;renderSetup()}return}if(b?.id==='setupNext'){e.preventDefault();e.stopImmediatePropagation();setupStep<2?(setupStep++,renderSetup()):closeSetup();return}if(b?.dataset.areaChoice){e.preventDefault();e.stopImmediatePropagation();const s=getState(),areas={...(s.areas||{})};areas[b.dataset.areaChoice]=!areas[b.dataset.areaChoice];saveState({...s,areas});renderSetup();return}if(b?.dataset.expandCat){e.preventDefault();e.stopImmediatePropagation();expanded[decodeURIComponent(b.dataset.expandCat)]=true;renderSetup();return}if(b?.dataset.collapseCat){e.preventDefault();e.stopImmediatePropagation();expanded[decodeURIComponent(b.dataset.collapseCat)]=false;renderSetup();return}if(b?.dataset.setupRestore){e.preventDefault();e.stopImmediatePropagation();const s=getState(),snap=(s.setupHistory||[]).find(x=>x.id===b.dataset.setupRestore);if(snap&&confirm('Gjenopprette dette oppsettet? Historikk og statistikk beholdes.'))saveState({...s,tasks:structuredClone(snap.tasks||[]),custom:structuredClone(snap.custom||[]),areas:structuredClone(snap.areas||s.areas||{}),trainingFor:structuredClone(snap.trainingFor||s.trainingFor||{}),categoryRelevant:structuredClone(snap.categoryRelevant||{}),setupHistory:archive(s,'Før gjenoppretting')});renderSetup();return}if(b?.id==='resetActiveTasks'){e.preventDefault();e.stopImmediatePropagation();if(confirm('Tilbakestille aktive gjøremål? Historikk, poeng og statistikk beholdes.')){const s=getState(),rel=relevantMap(s),tasks=LIB.filter(t=>DEFAULT_IDS.includes(t.id)&&rel[t.cat]!==false).map(t=>({...t,owner:'Begge'}));saveState({...s,tasks,setupHistory:archive(s,'Før tilbakestilling')});renderSetup()}return}if(b?.id==='addCustomTask'){e.preventDefault();e.stopImmediatePropagation();const name=prompt('Navn på oppgaven');if(name){const s=getState(),x={id:'custom_'+Date.now(),cat:'Egendefinert',name:name.trim(),freq:1,pts:30,type:'flex',kind:'house'};saveState({...s,custom:[...(s.custom||[]),x],tasks:[...(s.tasks||[]),{...x,owner:'Begge'}]});renderSetup()}return}}
const nav=e.target.closest('#nav button[data-view="tasks"]');if(nav){e.preventDefault();e.stopImmediatePropagation();const s=getState();if(s&&s.view!=='tasks')saveState({...s,view:'tasks'});render({resetScroll:true});return}const m=e.target.closest('[data-task-mode]');if(m){e.preventDefault();e.stopImmediatePropagation();mode=m.dataset.taskMode==='week'?'week':'day';render({resetScroll:true});return}const add=e.target.closest('[data-task-complete]');if(add){e.preventDefault();e.stopImmediatePropagation();complete(add.dataset.taskComplete);return}const undoBtn=e.target.closest('[data-task-undo]');if(undoBtn){e.preventDefault();e.stopImmediatePropagation();undo(undoBtn.dataset.taskUndo);return}},true);
document.addEventListener('change',e=>{if($('#setup')?.classList.contains('hidden'))return;const el=e.target;if(el.dataset.categoryRelevant){e.stopImmediatePropagation();const s=getState(),cat=decodeURIComponent(el.dataset.categoryRelevant),categoryRelevant={...(s.categoryRelevant||{}),[cat]:el.checked},hist=archive(s,el.checked?`${cat} slått på`:`${cat} slått av`);let tasks=[...(s.tasks||[])];if(!el.checked)tasks=tasks.filter(t=>category(t)!==cat);saveState({...s,categoryRelevant,tasks,setupHistory:hist});renderSetup();return}if(el.dataset.setupTask){e.stopImmediatePropagation();const s=getState(),id=el.dataset.setupTask,base=[...LIB,...(s.custom||[])].find(t=>t.id===id),tasks=[...(s.tasks||[])],i=tasks.findIndex(t=>t.id===id);if(el.checked&&i<0&&base)tasks.push({...base,owner:'Begge'});if(!el.checked&&i>=0)tasks.splice(i,1);saveState({...s,tasks});renderSetup();return}if(el.dataset.setupFreq){e.stopImmediatePropagation();updateTask(el.dataset.setupFreq,t=>t.freq=Math.max(1,Number(el.value)||1));return}if(el.dataset.setupPts){e.stopImmediatePropagation();updateTask(el.dataset.setupPts,t=>t.pts=Math.max(1,Number(el.value)||1));return}if(el.dataset.setupOwner){e.stopImmediatePropagation();updateTask(el.dataset.setupOwner,t=>t.owner=el.value);return}if(el.dataset.setupType){e.stopImmediatePropagation();updateTask(el.dataset.setupType,t=>t.type=el.value);return}},true);
window.FlytTasksUI={render,openSetup,version:'20260824-1120'};
})();