(()=>{
'use strict';
const $=s=>document.querySelector(s);
const bridge=()=>window.FlytBridge;
const ORDER=['Barn','Kjøkken','Bad','Hus','Utearbeid','Usynlig arbeid','Personlig investering','Egendefinert'];
function monday(){const d=new Date(),x=new Date(d),day=(x.getDay()+6)%7;x.setHours(0,0,0,0);x.setDate(x.getDate()-day);return x}
function weekComps(s){const m=monday();return (s.completions||[]).filter(c=>new Date(c.date)>=m)}
function countTask(s,id){return weekComps(s).filter(c=>c.taskId===id).length}
function ownCount(s,id){return weekComps(s).filter(c=>c.taskId===id&&c.by===s.user).length}
function cat(t){const raw=(t.cat||'').trim(),name=(t.name||'').toLowerCase();if(raw==='Barn'||raw==='Unger')return 'Barn';if(raw==='Kjøkken')return 'Kjøkken';if(raw==='Bad'||t.id==='bath'||name.includes('bad'))return 'Bad';if(raw==='Usynlig arbeid')return 'Usynlig arbeid';if(raw==='Personlig investering')return 'Personlig investering';if(raw==='Utearbeid'||/(hage|gress|snø|ute|hekk|løv|gårdsplass)/.test(name))return 'Utearbeid';if(raw==='Egendefinert')return 'Egendefinert';return raw||'Hus'}
function today(){return new Date().toISOString().slice(0,10)}
function sync(next){bridge().setState(next);window.FlytSync?.queueSave?.();setTimeout(render,0)}
function complete(id){const s=bridge()?.getState?.();if(!s)return;const t=(s.tasks||[]).find(x=>x.id===id);if(!t)return;const now=Date.now(),housePts=t.kind==='house'?t.pts:Math.round(t.pts*.2);const next={...s,completions:[...(s.completions||[]),{id:now,taskId:t.id,date:today(),by:s.user,kind:t.kind,housePts}],points:{...(s.points||{})},work:[{id:now+1,title:t.name,by:s.user,seen:false},...(s.work||[])]};next.points[s.user]=(next.points[s.user]||0)+t.pts;sync(next);bridge()?.toast?.('+'+t.pts+' poeng')}
function undo(id){const s=bridge()?.getState?.();if(!s)return;const t=(s.tasks||[]).find(x=>x.id===id);if(!t)return;const comps=[...(s.completions||[])];let idx=-1;for(let i=comps.length-1;i>=0;i--){if(comps[i].taskId===id&&comps[i].by===s.user&&new Date(comps[i].date)>=monday()){idx=i;break}}if(idx<0)return;comps.splice(idx,1);const work=[...(s.work||[])];for(let i=0;i<work.length;i++){if(work[i].title===t.name&&work[i].by===s.user){work.splice(i,1);break}}const next={...s,completions:comps,work,points:{...(s.points||{})}};next.points[s.user]=Math.max(0,(next.points[s.user]||0)-t.pts);sync(next);bridge()?.toast?.('Registreringen er trukket tilbake')}
function taskCard(s,t){const n=countTask(s,t.id),own=ownCount(s,t.id),done=n>=Number(t.freq||0);return `<div class="card"><div class="row"><div class="grow"><strong>${t.name}</strong><div class="taskmeta">${n}/${t.freq} denne uken · ${t.pts} poeng${t.owner?' · '+t.owner:''}</div></div>${done?'<span class="tag">Mål nådd ✓</span>':''}</div><div class="row" style="margin-top:10px"><button type="button" class="small" data-taskui-complete="${t.id}">+ Gjort</button>${own>0?`<button type="button" class="small" data-taskui-undo="${t.id}">− Angre</button>`:''}</div></div>`}
function render(){const s=bridge()?.getState?.(),c=$('#content');if(!s||!c)return;const tasks=Array.isArray(s.tasks)?s.tasks:[];const groups=new Map();for(const t of tasks){const k=cat(t);if(!groups.has(k))groups.set(k,[]);groups.get(k).push(t)}const keys=[...groups.keys()].sort((a,b)=>{const ai=ORDER.indexOf(a),bi=ORDER.indexOf(b);return (ai<0?999:ai)-(bi<0?999:bi)||a.localeCompare(b,'nb')});c.innerHTML=`<div class="ey">Gjøremål</div><h1 class="title">Denne uken</h1><p class="sub">Ukemålet er en forventning, ikke et tak. Registreringer kan også trekkes tilbake hvis du trykker feil.</p>${keys.map(k=>`<div class="section"><div class="ey">${k}</div>${groups.get(k).map(t=>taskCard(s,t)).join('')}</div>`).join('')}<button class="primary full" data-open-setup="1" style="margin-top:18px">Rediger oppsett</button>`;document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('on',b.dataset.view==='tasks'));c.scrollTop=0}
document.addEventListener('click',e=>{const nav=e.target.closest('#nav button[data-view="tasks"]');if(nav){e.preventDefault();e.stopImmediatePropagation();render();return}const add=e.target.closest('[data-taskui-complete]');if(add){e.preventDefault();e.stopImmediatePropagation();complete(add.dataset.taskuiComplete);return}const undoBtn=e.target.closest('[data-taskui-undo]');if(undoBtn){e.preventDefault();e.stopImmediatePropagation();undo(undoBtn.dataset.taskuiUndo);return}},true);
window.FlytTasksUI={render};
})();
